import type { LocaleCode } from "../locales";

const allDemoSlugs = ["restaurant", "consultant", "local-service", "shopify-consultant-portfolio", "jenifer-ciuciu-kiss", "ai-assistant", "analytics-dashboard"] as const;
export const demoSlugs = ["shopify-consultant-portfolio", "jenifer-ciuciu-kiss"] as const;
export type DemoSlug = (typeof allDemoSlugs)[number];

export type DemoContent = {
  slug: DemoSlug;
  type: string;
  title: string;
  shortDescription: string;
  previewImage?: string;
  websiteUrl?: string;
  category?: string;
  industry?: string;
  country?: string;
  clientName?: string;
  technologies?: string[];
  servicesProvided?: string[];
  seoImprovements?: string[];
  performanceImprovements?: string[];
  launchDate?: string;
  recommendedPackage: "Growth Setup" | "AI/Data Upgrade";
  features: string[];
  forText: string;
  challenges: string[];
  included: string[];
  whyItMatters: string;
  relatedProject:
    | "restaurant-visibility"
    | "consultant-lead-generation"
    | "cold-outreach-verifiable-brand"
    | "personal-brand-portfolio"
    | "ai-customer-assistant"
    | "analytics-visibility";
};

type DemoPageContent = {
  seo: {
    title: string;
    description: string;
    keywords: string;
  };
  eyebrow: string;
  title: string;
  text: string;
  labels: {
    recommendedPackage: string;
    features: string;
    learnMore: string;
    for: string;
    commonChallenges: string;
    included: string;
    businessImpact: string;
    viewLiveDemo: string;
    requestSimilar: string;
    viewAnalysis: string;
    primaryCta: string;
    secondaryCta: string;
    visitDemo: string;
    viewCaseStudy: string;
    industry: string;
    country: string;
    servicesProvided: string;
    technologies: string;
    seoImprovements: string;
    performanceImprovements: string;
    launchDate: string;
  };
  packageNames: Record<DemoContent["recommendedPackage"], string>;
  items: Record<DemoSlug, DemoContent>;
};

type LocalizedDemoPageContent = Partial<Omit<DemoPageContent, "items">> & {
  items?: Partial<Record<DemoSlug, Partial<DemoContent>>>;
};

const en: DemoPageContent = {
  seo: {
    title: "Website Demos and AI Automation Examples - Websiteli",
    description:
      "Explore Websiteli demos for small business websites, AI automation, analytics dashboards, SEO, lead generation, and digital transformation.",
    keywords: "website design, digital transformation, small business websites, AI automation, analytics, SEO, lead generation",
  },
  eyebrow: "Demos",
  title: "See what Websiteli can build.",
  text: "Practical demo concepts for websites, automation, analytics and lead generation. Each demo connects to an illustrative business opportunity analysis.",
  labels: {
    recommendedPackage: "Recommended Package",
    features: "Technologies and features",
    learnMore: "Learn More",
    for: "For",
    commonChallenges: "Common Challenges",
    included: "Included",
    businessImpact: "Business Impact",
    viewLiveDemo: "View Live Demo",
    requestSimilar: "Request Similar Website",
    viewAnalysis: "View Opportunity Analysis",
    primaryCta: "Request a Free Digital Audit",
    secondaryCta: "Book a Discovery Call",
    visitDemo: "Visit Demo",
    viewCaseStudy: "View Case Study",
    industry: "Industry",
    country: "Country",
    servicesProvided: "Services provided",
    technologies: "Technologies",
    seoImprovements: "SEO improvements",
    performanceImprovements: "Performance improvements",
    launchDate: "Launch date",
  },
  packageNames: {
    "Growth Setup": "Growth Setup",
    "AI/Data Upgrade": "AI/Data Upgrade",
  },
  items: {
    restaurant: {
      slug: "restaurant",
      type: "restaurant",
      title: "Restaurant / Café Website",
      shortDescription:
        "Modern restaurant website with online reservations, SEO optimization, analytics, reviews, maps and contact forms.",
      recommendedPackage: "Growth Setup",
      features: ["Responsive website", "Online reservation flow", "Menu sections", "Reviews", "Maps", "Analytics", "SEO setup"],
      forText: "Restaurants, cafés, bakeries and local food businesses.",
      challenges: ["Customers cannot book online", "Menu is hard to find", "Poor mobile experience", "Weak search visibility"],
      included: ["Responsive website", "Booking integration", "Contact forms", "Google Analytics", "Search Console", "Review section", "Maps integration"],
      whyItMatters: "A professional website can improve visibility and make reservations easier for customers.",
      relatedProject: "restaurant-visibility",
    },
    consultant: {
      slug: "consultant",
      type: "consultant",
      title: "Consultant / Coach Website",
      shortDescription:
        "Professional service website with positioning, booking, lead capture, newsletter signup, analytics and SEO foundations.",
      recommendedPackage: "Growth Setup",
      features: ["Service pages", "Booking flow", "Lead capture", "Newsletter signup", "Analytics", "SEO setup"],
      forText: "Consultants, coaches, advisors and independent professional service providers.",
      challenges: ["LinkedIn traffic does not convert", "No owned contact funnel", "Booking requires manual messages", "Expertise is hard to evaluate quickly"],
      included: ["Responsive website", "Offer pages", "Booking integration", "Lead-capture form", "Newsletter setup", "Google Analytics", "Search Console"],
      whyItMatters: "A focused website can turn interest into booked calls and make the offer easier to understand.",
      relatedProject: "consultant-lead-generation",
    },
    "local-service": {
      slug: "local-service",
      type: "local_service",
      title: "Local Service Business Website",
      shortDescription:
        "Local business website with service areas, quote requests, trust signals, Google Business support, SEO and conversion tracking.",
      recommendedPackage: "Growth Setup",
      features: ["Service pages", "Quote forms", "Service areas", "Trust sections", "Maps", "Analytics", "Local SEO"],
      forText: "Trades, repair services, beauty studios, wellness providers and other local service businesses.",
      challenges: ["Customers cannot quickly request a quote", "Service areas are unclear", "Trust signals are scattered", "Local SEO is weak"],
      included: ["Responsive website", "Service area pages", "Quote request form", "Google Business Profile support", "Reviews", "Maps", "Conversion tracking"],
      whyItMatters: "A local service website can make it easier for nearby customers to understand, trust and contact the business.",
      relatedProject: "restaurant-visibility",
    },
    "shopify-consultant-portfolio": {
      slug: "shopify-consultant-portfolio",
      type: "shopify_consultant_portfolio",
      title: "Shopify Consultant Portfolio Website",
      shortDescription:
        "Convert cold outreach into trust with a professional portfolio website.",
      previewImage: "/assets/shopify-consultant-portfolio-demo-preview.svg",
      websiteUrl: "https://kuefmz.github.io/websiteli-portfolio-demo/",
      category: "Live demo",
      industry: "Shopify consulting / marketing services",
      country: "International",
      clientName: "Websiteli demo",
      technologies: ["Astro", "HTML", "CSS", "JavaScript", "GitHub Pages"],
      servicesProvided: ["Website strategy & Portfolio design", "Lead generation CTA & SEO structure", "Trust-building content"],
      seoImprovements: ["Search-friendly page structure", "Service-focused headings", "Clear metadata", "Internal conversion path"],
      performanceImprovements: ["Static hosting", "Optimized SVG preview", "Responsive layout", "Low layout shift"],
      launchDate: "2026-06-26",
      recommendedPackage: "Growth Setup",
      features: ["Personal brand website", "Services showcase", "Testimonials", "Case studies", "Lead generation CTA", "SEO setup"],
      forText:
        "Shopify consultants, marketing agencies, SEO specialists, CRO experts, email marketing consultants, paid ads specialists, and freelancers selling services through outreach.",
      challenges: [
        "Prospects cannot easily verify the sender",
        "Cold outreach has low trust",
        "Services and proof are scattered",
        "LinkedIn alone does not show the full offer",
      ],
      included: [
        "Responsive website",
        "Service sections",
        "Testimonials section",
        "Case study structure",
        "Lead-generation CTA",
        "Search-friendly page structure",
      ],
      whyItMatters:
        "A premium portfolio website gives outreach prospects a credible place to verify expertise, understand the offer, and decide whether to continue the conversation.",
      relatedProject: "cold-outreach-verifiable-brand",
    },
    "jenifer-ciuciu-kiss": {
      slug: "jenifer-ciuciu-kiss",
      type: "personal_brand_portfolio",
      title: "Personal Brand / Portfolio Website",
      shortDescription:
        "A personal brand and portfolio website for showcasing projects, research, experience, and contact options.",
      previewImage: "/assets/jenifer-ciuciu-kiss-portfolio-preview.png",
      websiteUrl: "https://jeniferciuciukiss.com/?utm_source=websiteli&utm_medium=portfolio&utm_campaign=demo_project",
      category: "Live website",
      industry: "Personal brand / portfolio",
      country: "International",
      clientName: "Jenifer Ciuciu Kiss",
      technologies: ["Portfolio website", "Responsive design", "SEO structure", "Contact paths"],
      servicesProvided: ["Personal brand positioning", "Portfolio structure", "Contact conversion path"],
      seoImprovements: ["Clear personal-brand metadata", "Project-focused content structure", "Readable internal navigation"],
      performanceImprovements: ["Responsive layout", "Focused content structure", "Lightweight browsing experience"],
      launchDate: "2026-06-30",
      recommendedPackage: "Growth Setup",
      features: ["Personal brand website", "Portfolio showcase", "Research overview", "Experience sections", "Contact options", "SEO setup"],
      forText: "Founders, researchers, consultants, specialists and professionals who need a credible owned profile beyond social platforms.",
      challenges: [
        "Projects and experience are scattered",
        "Social profiles do not show the full story",
        "Contact options are not centralized",
        "Personal credibility is hard to evaluate quickly",
      ],
      included: [
        "Responsive website",
        "Portfolio sections",
        "Research and experience structure",
        "Contact options",
        "Search-friendly page structure",
      ],
      whyItMatters:
        "A personal brand website gives visitors one trusted place to understand expertise, review projects and choose the right contact path.",
      relatedProject: "personal-brand-portfolio",
    },
    "ai-assistant": {
      slug: "ai-assistant",
      type: "ai_assistant",
      title: "AI Customer Assistant",
      shortDescription:
        "AI assistant demo for repeated customer questions, lead qualification, FAQ search, contact handoff and simple support automation.",
      recommendedPackage: "AI/Data Upgrade",
      features: ["FAQ assistant", "Lead qualification", "Contact handoff", "Knowledge base", "Conversation tracking"],
      forText: "SMEs that answer repeated questions and want a faster first response for customers.",
      challenges: ["Repetitive questions interrupt daily work", "Leads arrive without enough context", "Customers wait for basic answers", "Support knowledge is not centralized"],
      included: ["Customer assistant", "FAQ knowledge base", "Lead qualification prompts", "Contact handoff", "Conversation analytics", "Basic workflow automation"],
      whyItMatters: "An AI assistant can reduce repetitive interruptions and help qualify inquiries before a human follows up.",
      relatedProject: "ai-customer-assistant",
    },
    "analytics-dashboard": {
      slug: "analytics-dashboard",
      type: "analytics_dashboard",
      title: "Analytics Dashboard",
      shortDescription:
        "Dashboard demo for website performance, conversion tracking, best pages, inquiry sources, marketing insights and reporting.",
      recommendedPackage: "AI/Data Upgrade",
      features: ["Traffic overview", "Conversion tracking", "Page insights", "Inquiry sources", "Reports", "Marketing decisions"],
      forText: "Growing companies that need clearer insight into website and marketing performance.",
      challenges: ["Website activity is hard to interpret", "No conversion tracking", "Best-performing pages are unknown", "Marketing decisions rely on guesswork"],
      included: ["Analytics dashboard", "Conversion events", "Source tracking", "Page performance view", "Monthly reporting structure", "Decision-focused metrics"],
      whyItMatters: "A dashboard can make website performance visible and help prioritize better marketing decisions.",
      relatedProject: "analytics-visibility",
    },
  },
};

const localized: Partial<Record<LocaleCode, LocalizedDemoPageContent>> = {
  de: {
    seo: { title: "Website-Demos und KI-Automation - Websiteli", description: "Websiteli-Demos für KMU-Websites, KI-Automation, Analytics, SEO und Leadgenerierung.", keywords: en.seo.keywords },
    eyebrow: "Demos",
    title: "Sehen Sie, was Websiteli bauen kann.",
    text: "Praktische Demo-Konzepte für Websites, Automation, Analytics und Leadgenerierung.",
    labels: { ...en.labels, recommendedPackage: "Empfohlenes Paket", features: "Technologien und Funktionen", learnMore: "Mehr erfahren", for: "Für", commonChallenges: "Typische Herausforderungen", included: "Enthalten", businessImpact: "Geschäftlicher Nutzen", viewLiveDemo: "Live-Demo ansehen", requestSimilar: "Ähnliche Website anfragen", viewAnalysis: "Chancenanalyse ansehen", primaryCta: "Kostenlosen Digital-Audit anfragen", secondaryCta: "Discovery Call buchen" },
    packageNames: { "Growth Setup": "Wachstums-Setup", "AI/Data Upgrade": "KI- und Daten-Upgrade" },
    items: {
      restaurant: { title: "Restaurant- / Café-Website", shortDescription: "Moderne Restaurant-Website mit Online-Reservierungen, SEO, Analytics, Bewertungen, Karten und Kontaktformularen.", forText: "Für Restaurants, Cafés, Bäckereien und lokale Food-Unternehmen.", challenges: ["Kunden können nicht online reservieren", "Die Speisekarte ist schwer zu finden", "Schwache mobile Erfahrung", "Geringe Sichtbarkeit in der Suche"], whyItMatters: "Eine professionelle Website kann die Sichtbarkeit verbessern und Reservierungen für Kunden einfacher machen." },
      consultant: { title: "Website für Berater / Coaches", shortDescription: "Professionelle Dienstleister-Website mit Positionierung, Buchung, Lead-Erfassung, Newsletter-Anmeldung, Analytics und SEO-Grundlagen.", forText: "Für Berater, Coaches, Experten und unabhängige Dienstleister.", challenges: ["LinkedIn-Traffic konvertiert nicht", "Kein eigener Kontakt-Funnel", "Buchungen laufen manuell", "Expertise ist schwer schnell einzuschätzen"], whyItMatters: "Eine fokussierte Website kann Interesse in gebuchte Gespräche verwandeln und das Angebot verständlicher machen." },
      "local-service": { title: "Website für lokale Dienstleister", shortDescription: "Lokale Unternehmenswebsite mit Leistungsgebieten, Angebotsanfragen, Vertrauenselementen, Google-Business-Unterstützung, SEO und Conversion-Tracking.", forText: "Für Handwerk, Reparaturdienste, Beauty-Studios, Wellness-Anbieter und lokale Services.", challenges: ["Kunden können kein Angebot schnell anfragen", "Leistungsgebiete sind unklar", "Vertrauenssignale sind verstreut", "Lokale SEO ist schwach"], whyItMatters: "Eine lokale Service-Website hilft Kunden in der Nähe, das Angebot zu verstehen, Vertrauen aufzubauen und Kontakt aufzunehmen." },
      "shopify-consultant-portfolio": { title: "Portfolio-Website für Shopify-Berater", shortDescription: "Verwandeln Sie kalte Akquise in Vertrauen mit einer professionellen Portfolio-Website.", features: ["Persönliche Markenwebsite", "Leistungsübersicht", "Testimonials", "Fallstudien", "Lead-CTA", "SEO-Grundlagen"], forText: "Für Shopify-Berater, Marketingagenturen, SEO-Spezialisten, CRO-Experten, E-Mail-Marketing-Berater, Paid-Ads-Spezialisten und Freelancer, die Services über Outreach verkaufen.", challenges: ["Interessenten können den Absender nicht leicht prüfen", "Kalte Akquise hat wenig Vertrauen", "Services und Nachweise sind verstreut", "LinkedIn allein zeigt nicht das ganze Angebot"], included: ["Responsive Website", "Leistungssektionen", "Testimonials-Bereich", "Fallstudien-Struktur", "Lead-CTA", "Suchfreundliche Seitenstruktur"], whyItMatters: "Eine hochwertige Portfolio-Website gibt Outreach-Interessenten einen glaubwürdigen Ort, um Expertise zu prüfen, das Angebot zu verstehen und über den nächsten Schritt zu entscheiden." },
      "ai-assistant": { title: "KI-Kundenassistent", shortDescription: "KI-Assistent für wiederkehrende Kundenfragen, Lead-Qualifizierung, FAQ-Suche, Kontaktübergabe und einfache Support-Automatisierung.", forText: "Für KMU, die wiederkehrende Fragen beantworten und schneller auf Kunden reagieren möchten.", challenges: ["Wiederholte Fragen unterbrechen die Arbeit", "Leads kommen ohne genug Kontext", "Kunden warten auf einfache Antworten", "Support-Wissen ist nicht zentralisiert"], whyItMatters: "Ein KI-Assistent kann wiederkehrende Unterbrechungen reduzieren und Anfragen vorqualifizieren." },
      "analytics-dashboard": { title: "Analytics-Dashboard", shortDescription: "Dashboard für Website-Leistung, Conversion-Tracking, beste Seiten, Anfragequellen, Marketingeinblicke und Reporting.", forText: "Für wachsende Unternehmen, die mehr Klarheit über Website- und Marketing-Performance brauchen.", challenges: ["Website-Aktivität ist schwer zu interpretieren", "Kein Conversion-Tracking", "Beste Seiten sind unbekannt", "Marketingentscheidungen beruhen auf Vermutungen"], whyItMatters: "Ein Dashboard macht Website-Performance sichtbar und hilft, bessere Marketingprioritäten zu setzen." },
    },
  },
  hu: {
    seo: { title: "Weboldal demók és AI automatizálási példák - Websiteli", description: "Websiteli demók kisvállalati weboldalakhoz, AI automatizáláshoz, analitikához, SEO-hoz és lead generáláshoz.", keywords: en.seo.keywords },
    eyebrow: "Demók",
    title: "Nézd meg, mit tud építeni a Websiteli.",
    text: "Gyakorlati demók weboldalakhoz, automatizáláshoz, analitikához és érdeklődőszerzéshez.",
    labels: { ...en.labels, recommendedPackage: "Ajánlott csomag", features: "Technológiák és funkciók", learnMore: "Részletek", for: "Kinek szól", commonChallenges: "Gyakori kihívások", included: "Tartalmazza", businessImpact: "Üzleti hatás", viewLiveDemo: "Élő demó megnyitása", requestSimilar: "Hasonló weboldalt kérek", viewAnalysis: "Lehetőségelemzés megtekintése", primaryCta: "Ingyenes digitális audit kérése", secondaryCta: "Discovery call foglalása" },
    packageNames: { "Growth Setup": "Növekedési csomag", "AI/Data Upgrade": "AI/adat fejlesztés" },
    items: {
      restaurant: { title: "Étterem / kávézó weboldal", shortDescription: "Modern éttermi weboldal online foglalással, SEO-val, analitikával, értékelésekkel, térképpel és kapcsolati űrlapokkal.", forText: "Éttermeknek, kávézóknak, pékségeknek és helyi vendéglátó vállalkozásoknak.", challenges: ["Az ügyfelek nem tudnak online foglalni", "A menü nehezen található", "Gyenge mobilélmény", "Gyenge keresőbeli láthatóság"], whyItMatters: "Egy professzionális weboldal javíthatja a láthatóságot és egyszerűbbé teheti a foglalást." },
      consultant: { title: "Tanácsadó / coach weboldal", shortDescription: "Professzionális szolgáltatói weboldal pozicionálással, foglalással, leadgyűjtéssel, hírlevél-feliratkozással, analitikával és SEO alapokkal.", forText: "Tanácsadóknak, coachoknak, szakértőknek és független szolgáltatóknak.", challenges: ["A LinkedIn forgalom nem konvertál", "Nincs saját kapcsolatfelvételi tölcsér", "A foglalás kézi üzeneteket igényel", "A szakértelem nehezen értékelhető gyorsan"], whyItMatters: "Egy fókuszált weboldal az érdeklődést lefoglalt hívásokká alakíthatja, és érthetőbbé teszi az ajánlatot." },
      "local-service": { title: "Helyi szolgáltató weboldal", shortDescription: "Helyi üzleti weboldal szolgáltatási területekkel, ajánlatkéréssel, bizalmi elemekkel, Google Business támogatással, SEO-val és konverzióméréssel.", forText: "Szakembereknek, javítószolgálatoknak, szépségszalonoknak, wellness szolgáltatóknak és más helyi vállalkozásoknak.", challenges: ["Az ügyfelek nem tudnak gyorsan ajánlatot kérni", "A szolgáltatási területek nem egyértelműek", "A bizalmi elemek szétszórtak", "A helyi SEO gyenge"], whyItMatters: "Egy helyi szolgáltatói weboldal megkönnyíti, hogy a közeli ügyfelek megértsék, megbízzanak benne és kapcsolatba lépjenek." },
      "shopify-consultant-portfolio": { title: "Shopify tanácsadói portfólió weboldal", shortDescription: "Alakítsd a hideg megkereséseket bizalommá egy professzionális portfólió weboldallal.", features: ["Személyes márka weboldal", "Szolgáltatásbemutató", "Ügyfélvélemények", "Esettanulmányok", "Leadgeneráló CTA", "SEO alapok"], forText: "Shopify tanácsadóknak, marketingügynökségeknek, SEO szakértőknek, CRO szakértőknek, e-mail marketing tanácsadóknak, fizetett hirdetési szakértőknek és outreachből szolgáltatásokat értékesítő freelancereknek.", challenges: ["A potenciális ügyfelek nehezen tudják ellenőrizni a megkeresőt", "A hideg outreach kevés bizalmat épít", "A szolgáltatások és bizonyítékok szétszórtak", "A LinkedIn önmagában nem mutatja meg a teljes ajánlatot"], included: ["Reszponzív weboldal", "Szolgáltatási szekciók", "Ügyfélvélemények szekció", "Esettanulmány-struktúra", "Leadgeneráló CTA", "Keresőbarát oldalstruktúra"], whyItMatters: "Egy prémium portfólió weboldal hiteles helyet ad az outreachből érkező érdeklődőknek, ahol ellenőrizhetik a szakértelmet, megérthetik az ajánlatot és dönthetnek a folytatásról." },
      "ai-assistant": { title: "AI ügyfélasszisztens", shortDescription: "AI asszisztens ismétlődő ügyfélkérdésekhez, lead minősítéshez, FAQ kereséshez, kapcsolatátadáshoz és egyszerű ügyféltámogatási automatizáláshoz.", forText: "KKV-knak, amelyek ismétlődő kérdésekre válaszolnak, és gyorsabb első választ szeretnének.", challenges: ["Az ismétlődő kérdések megszakítják a napi munkát", "A leadek kevés kontextussal érkeznek", "Az ügyfelek alapválaszokra várnak", "A támogatási tudás nincs központosítva"], whyItMatters: "Egy AI asszisztens csökkentheti az ismétlődő megszakításokat, és előminősítheti az érdeklődéseket." },
      "analytics-dashboard": { title: "Analitikai irányítópult", shortDescription: "Irányítópult weboldal-teljesítményhez, konverzióméréshez, legjobb oldalakhoz, érdeklődési forrásokhoz, marketing insightokhoz és riportokhoz.", forText: "Növekvő cégeknek, amelyek tisztább képet szeretnének a weboldal és marketing teljesítményéről.", challenges: ["A weboldal aktivitása nehezen értelmezhető", "Nincs konverziómérés", "Nem láthatóak a legjobb oldalak", "A marketingdöntések találgatáson alapulnak"], whyItMatters: "Egy irányítópult láthatóvá teszi a weboldal teljesítményét, és segít jobb marketingprioritásokat választani." },
    },
  },
  pl: {
    seo: { title: "Dema stron i automatyzacji AI - Websiteli", description: "Dema Websiteli dla stron małych firm, automatyzacji AI, analityki, SEO i lead generation.", keywords: en.seo.keywords },
    eyebrow: "Demo", title: "Zobacz, co Websiteli może zbudować.", text: "Praktyczne dema stron, automatyzacji, analityki i pozyskiwania leadów.",
    labels: { ...en.labels, recommendedPackage: "Rekomendowany pakiet", features: "Technologie i funkcje", learnMore: "Dowiedz się więcej", for: "Dla kogo", commonChallenges: "Typowe wyzwania", included: "W pakiecie", businessImpact: "Wpływ biznesowy", viewLiveDemo: "Zobacz live demo", requestSimilar: "Poproś o podobną stronę", viewAnalysis: "Zobacz analizę możliwości", primaryCta: "Poproś o bezpłatny audyt cyfrowy", secondaryCta: "Umów rozmowę discovery" },
    packageNames: { "Growth Setup": "Pakiet wzrostu", "AI/Data Upgrade": "Rozbudowa AI i danych" },
    items: {
      restaurant: { title: "Strona restauracji / kawiarni", shortDescription: "Nowoczesna strona restauracji z rezerwacjami online, SEO, analityką, opiniami, mapami i formularzami kontaktu.", forText: "Dla restauracji, kawiarni, piekarni i lokalnych firm gastronomicznych.", challenges: ["Klienci nie mogą rezerwować online", "Menu trudno znaleźć", "Słabe doświadczenie mobilne", "Niska widoczność w wyszukiwarce"], whyItMatters: "Profesjonalna strona może poprawić widoczność i ułatwić klientom rezerwację." },
      consultant: { title: "Strona konsultanta / coacha", shortDescription: "Profesjonalna strona usługowa z pozycjonowaniem oferty, rezerwacjami, zbieraniem leadów, newsletterem, analityką i podstawami SEO.", forText: "Dla konsultantów, coachów, doradców i niezależnych usługodawców.", challenges: ["Ruch z LinkedIn nie konwertuje", "Brak własnego lejka kontaktu", "Rezerwacje wymagają ręcznych wiadomości", "Ekspertyzę trudno szybko ocenić"], whyItMatters: "Skupiona strona może zamienić zainteresowanie w umówione rozmowy i uprościć zrozumienie oferty." },
      "local-service": { title: "Strona lokalnej firmy usługowej", shortDescription: "Strona lokalnej firmy z obszarami usług, zapytaniami ofertowymi, elementami zaufania, wsparciem Google Business, SEO i trackingiem konwersji.", forText: "Dla fachowców, serwisów naprawczych, salonów beauty, wellness i innych lokalnych usług.", challenges: ["Klienci nie mogą szybko poprosić o wycenę", "Obszary usług są niejasne", "Elementy zaufania są rozproszone", "Lokalne SEO jest słabe"], whyItMatters: "Strona lokalnej usługi ułatwia pobliskim klientom zrozumienie, zaufanie i kontakt." },
      "shopify-consultant-portfolio": { title: "Strona portfolio konsultanta Shopify", shortDescription: "Zamień cold outreach w zaufanie dzięki profesjonalnej stronie portfolio.", features: ["Strona marki osobistej", "Prezentacja usług", "Opinie klientów", "Case studies", "CTA do pozyskiwania leadów", "Podstawy SEO"], forText: "Dla konsultantów Shopify, agencji marketingowych, specjalistów SEO, ekspertów CRO, konsultantów e-mail marketingu, specjalistów płatnych reklam i freelancerów sprzedających usługi przez outreach.", challenges: ["Prospekci nie mogą łatwo zweryfikować nadawcy", "Cold outreach budzi mało zaufania", "Usługi i dowody są rozproszone", "Sam LinkedIn nie pokazuje pełnej oferty"], included: ["Responsywna strona", "Sekcje usług", "Sekcja opinii", "Struktura case studies", "CTA do leadów", "Struktura przyjazna wyszukiwarkom"], whyItMatters: "Premium strona portfolio daje prospektom z outreachu wiarygodne miejsce do sprawdzenia ekspertyzy, zrozumienia oferty i decyzji o dalszej rozmowie." },
      "ai-assistant": { title: "Asystent klienta AI", shortDescription: "Demo asystenta AI do powtarzalnych pytań klientów, kwalifikacji leadów, wyszukiwania FAQ, przekazania kontaktu i prostej automatyzacji supportu.", forText: "Dla MŚP, które odpowiadają na powtarzalne pytania i chcą szybszej pierwszej odpowiedzi.", challenges: ["Powtarzalne pytania przerywają codzienną pracę", "Leady przychodzą bez kontekstu", "Klienci czekają na podstawowe odpowiedzi", "Wiedza supportu nie jest scentralizowana"], whyItMatters: "Asystent AI może ograniczyć powtarzalne przerwy i pomóc kwalifikować zapytania przed kontaktem człowieka." },
      "analytics-dashboard": { title: "Panel analityczny", shortDescription: "Demo panelu do wyników strony, konwersji, najlepszych stron, źródeł zapytań, insightów marketingowych i raportowania.", forText: "Dla rosnących firm, które potrzebują jasnego wglądu w wyniki strony i marketingu.", challenges: ["Aktywność strony trudno interpretować", "Brak trackingu konwersji", "Nie wiadomo, które strony działają najlepiej", "Decyzje marketingowe opierają się na domysłach"], whyItMatters: "Panel pokazuje wyniki strony i pomaga lepiej ustalać priorytety marketingowe." },
    },
  },
  es: {
    seo: { title: "Demos web y automatización IA - Websiteli", description: "Demos de Websiteli para webs de pequeñas empresas, automatización IA, analítica, SEO y generación de leads.", keywords: en.seo.keywords },
    eyebrow: "Demos", title: "Mira lo que Websiteli puede crear.", text: "Conceptos demo para webs, automatización, analítica y generación de leads.",
    labels: { ...en.labels, recommendedPackage: "Paquete recomendado", features: "Tecnologías y funciones", learnMore: "Saber más", for: "Para", commonChallenges: "Retos comunes", included: "Incluido", businessImpact: "Impacto empresarial", viewLiveDemo: "Ver demo en vivo", requestSimilar: "Solicitar una web similar", viewAnalysis: "Ver análisis de oportunidad", primaryCta: "Solicitar auditoría digital gratuita", secondaryCta: "Reservar llamada discovery" },
    packageNames: { "Growth Setup": "Configuración de crecimiento", "AI/Data Upgrade": "Mejora de IA y datos" },
    items: {
      restaurant: { title: "Web para restaurante / cafetería", shortDescription: "Web moderna para restaurante con reservas online, SEO, analítica, reseñas, mapas y formularios de contacto.", forText: "Para restaurantes, cafeterías, panaderías y negocios locales de comida.", challenges: ["Los clientes no pueden reservar online", "El menú es difícil de encontrar", "Mala experiencia móvil", "Poca visibilidad en buscadores"], whyItMatters: "Una web profesional puede mejorar la visibilidad y facilitar las reservas para los clientes." },
      consultant: { title: "Web para consultor / coach", shortDescription: "Web profesional de servicios con posicionamiento, reservas, captación de leads, suscripción a boletín, analítica y base SEO.", forText: "Para consultores, coaches, asesores y profesionales independientes.", challenges: ["El tráfico de LinkedIn no convierte", "No hay embudo de contacto propio", "Las reservas requieren mensajes manuales", "La experiencia es difícil de evaluar rápido"], whyItMatters: "Una web enfocada puede convertir el interés en llamadas reservadas y aclarar la oferta." },
      "local-service": { title: "Web para negocio local de servicios", shortDescription: "Web local con zonas de servicio, solicitudes de presupuesto, señales de confianza, soporte para Google Business, SEO y seguimiento de conversiones.", forText: "Para oficios, reparaciones, estudios de belleza, bienestar y otros servicios locales.", challenges: ["Los clientes no pueden pedir presupuesto rápido", "Las zonas de servicio no están claras", "Las señales de confianza están dispersas", "El SEO local es débil"], whyItMatters: "Una web local facilita que clientes cercanos entiendan, confíen y contacten con el negocio." },
      "shopify-consultant-portfolio": { title: "Web portfolio para consultor Shopify", shortDescription: "Convierte el cold outreach en confianza con una web portfolio profesional.", features: ["Web de marca personal", "Presentación de servicios", "Testimonios", "Casos de estudio", "CTA de generación de leads", "Base SEO"], forText: "Para consultores Shopify, agencias de marketing, especialistas SEO, expertos CRO, consultores de email marketing, especialistas en paid ads y freelancers que venden servicios mediante outreach.", challenges: ["Los prospectos no pueden verificar fácilmente al remitente", "El cold outreach genera poca confianza", "Servicios y pruebas están dispersos", "LinkedIn por sí solo no muestra toda la oferta"], included: ["Web responsive", "Secciones de servicios", "Sección de testimonios", "Estructura de casos de estudio", "CTA para leads", "Estructura apta para buscadores"], whyItMatters: "Una web portfolio premium da a los prospectos de outreach un lugar creíble para verificar experiencia, entender la oferta y decidir si continuar la conversación." },
      "ai-assistant": { title: "Asistente de clientes con IA", shortDescription: "Demo de asistente con IA para preguntas repetitivas, cualificación de leads, búsqueda FAQ, traspaso a contacto y automatización básica de soporte.", forText: "Para pymes que responden preguntas repetidas y quieren una primera respuesta más rápida.", challenges: ["Las preguntas repetitivas interrumpen el trabajo diario", "Los leads llegan sin suficiente contexto", "Los clientes esperan respuestas básicas", "El conocimiento de soporte no está centralizado"], whyItMatters: "Un asistente con IA puede reducir interrupciones repetitivas y cualificar consultas antes del seguimiento humano." },
      "analytics-dashboard": { title: "Panel de analítica", shortDescription: "Demo de panel para rendimiento web, conversiones, mejores páginas, fuentes de consultas, insights de marketing e informes.", forText: "Para empresas en crecimiento que necesitan más claridad sobre el rendimiento web y de marketing.", challenges: ["La actividad web es difícil de interpretar", "No hay seguimiento de conversiones", "No se conocen las mejores páginas", "Las decisiones de marketing se basan en suposiciones"], whyItMatters: "Un panel puede hacer visible el rendimiento web y ayudar a priorizar mejores decisiones de marketing." },
    },
  },
  fr: {
    seo: { title: "Démos de sites et automatisation IA - Websiteli", description: "Démos Websiteli pour sites de PME, automatisation IA, analytics, SEO et génération de leads.", keywords: en.seo.keywords },
    eyebrow: "Démos", title: "Voyez ce que Websiteli peut construire.", text: "Concepts démo pour sites, automatisation, analytics et génération de leads.",
    labels: { ...en.labels, recommendedPackage: "Offre recommandée", features: "Technologies et fonctions", learnMore: "En savoir plus", for: "Pour", commonChallenges: "Défis fréquents", included: "Inclus", businessImpact: "Impact métier", viewLiveDemo: "Voir la démo live", requestSimilar: "Demander un site similaire", viewAnalysis: "Voir l'analyse d'opportunité", primaryCta: "Demander un audit digital gratuit", secondaryCta: "Réserver un appel découverte" },
    packageNames: { "Growth Setup": "Configuration croissance", "AI/Data Upgrade": "Amélioration IA et données" },
    items: {
      restaurant: { title: "Site restaurant / café", shortDescription: "Site moderne pour restaurant avec réservations en ligne, SEO, analytics, avis, cartes et formulaires de contact.", forText: "Pour restaurants, cafés, boulangeries et commerces alimentaires locaux.", challenges: ["Les clients ne peuvent pas réserver en ligne", "Le menu est difficile à trouver", "Mauvaise expérience mobile", "Faible visibilité dans la recherche"], whyItMatters: "Un site professionnel peut améliorer la visibilité et faciliter les réservations." },
      consultant: { title: "Site consultant / coach", shortDescription: "Site professionnel avec positionnement, réservation, capture de leads, inscription newsletter, analytics et bases SEO.", forText: "Pour consultants, coachs, conseillers et prestataires indépendants.", challenges: ["Le trafic LinkedIn ne convertit pas", "Pas de funnel de contact propriétaire", "La réservation demande des messages manuels", "L'expertise est difficile à évaluer rapidement"], whyItMatters: "Un site ciblé peut transformer l'intérêt en appels réservés et clarifier l'offre." },
      "local-service": { title: "Site pour entreprise locale de services", shortDescription: "Site local avec zones de service, demandes de devis, preuves de confiance, support Google Business, SEO et suivi des conversions.", forText: "Pour artisans, réparateurs, instituts beauté, bien-être et autres services locaux.", challenges: ["Les clients ne peuvent pas demander un devis rapidement", "Les zones de service sont floues", "Les preuves de confiance sont dispersées", "Le SEO local est faible"], whyItMatters: "Un site local aide les clients proches à comprendre, faire confiance et contacter l'entreprise." },
      "shopify-consultant-portfolio": { title: "Site portfolio pour consultant Shopify", shortDescription: "Transformez la prospection à froid en confiance avec un site portfolio professionnel.", features: ["Site de marque personnelle", "Présentation des services", "Témoignages", "Études de cas", "CTA de génération de leads", "Bases SEO"], forText: "Pour consultants Shopify, agences marketing, spécialistes SEO, experts CRO, consultants email marketing, spécialistes paid ads et freelances qui vendent leurs services par outreach.", challenges: ["Les prospects ne peuvent pas vérifier facilement l'expéditeur", "La prospection à froid inspire peu confiance", "Les services et preuves sont dispersés", "LinkedIn seul ne montre pas toute l'offre"], included: ["Site responsive", "Sections services", "Section témoignages", "Structure d'études de cas", "CTA de génération de leads", "Structure adaptée aux moteurs de recherche"], whyItMatters: "Un site portfolio premium donne aux prospects issus de l'outreach un lieu crédible pour vérifier l'expertise, comprendre l'offre et décider de poursuivre l'échange." },
      "ai-assistant": { title: "Assistant client IA", shortDescription: "Démo d'assistant IA pour questions répétitives, qualification de leads, recherche FAQ, transfert de contact et automatisation simple du support.", forText: "Pour PME qui répondent à des questions répétitives et veulent une première réponse plus rapide.", challenges: ["Les questions répétitives interrompent le travail", "Les leads arrivent sans contexte suffisant", "Les clients attendent des réponses simples", "La connaissance support n'est pas centralisée"], whyItMatters: "Un assistant IA peut réduire les interruptions répétitives et qualifier les demandes avant le suivi humain." },
      "analytics-dashboard": { title: "Tableau de bord analytics", shortDescription: "Démo de tableau de bord pour performance du site, conversions, meilleures pages, sources de demandes, insights marketing et reporting.", forText: "Pour entreprises en croissance qui ont besoin d'une meilleure visibilité sur site et marketing.", challenges: ["L'activité du site est difficile à interpréter", "Pas de suivi des conversions", "Les meilleures pages sont inconnues", "Les décisions marketing reposent sur des suppositions"], whyItMatters: "Un tableau de bord rend la performance visible et aide à prioriser les bonnes actions marketing." },
    },
  },
  it: {
    seo: { title: "Demo siti web e automazione AI - Websiteli", description: "Demo Websiteli per siti di piccole imprese, automazione AI, analytics, SEO e lead generation.", keywords: en.seo.keywords },
    eyebrow: "Demo", title: "Scopri cosa può costruire Websiteli.", text: "Concept demo per siti, automazione, analytics e generazione di lead.",
    labels: { ...en.labels, recommendedPackage: "Pacchetto consigliato", features: "Tecnologie e funzionalità", learnMore: "Scopri di più", for: "Per", commonChallenges: "Sfide comuni", included: "Incluso", businessImpact: "Impatto business", viewLiveDemo: "Apri demo live", requestSimilar: "Richiedi un sito simile", viewAnalysis: "Vedi analisi opportunità", primaryCta: "Richiedi audit digitale gratuito", secondaryCta: "Prenota una discovery call" },
    packageNames: { "Growth Setup": "Pacchetto crescita", "AI/Data Upgrade": "Upgrade AI e dati" },
    items: {
      restaurant: { title: "Sito per ristorante / bar", shortDescription: "Sito moderno per ristorante con prenotazioni online, SEO, analytics, recensioni, mappe e moduli di contatto.", forText: "Per ristoranti, bar, panetterie e attività food locali.", whyItMatters: "Un sito professionale può migliorare la visibilità e rendere le prenotazioni più semplici." },
      consultant: { title: "Sito per consulente / coach", shortDescription: "Sito professionale con posizionamento, prenotazioni, acquisizione lead, newsletter, analytics e basi SEO.", forText: "Per consulenti, coach, advisor e professionisti indipendenti.", whyItMatters: "Un sito focalizzato può trasformare l'interesse in chiamate prenotate e rendere l'offerta più chiara." },
      "local-service": { title: "Sito per attività locale di servizi", shortDescription: "Sito locale con aree servite, richieste preventivo, segnali di fiducia, supporto Google Business, SEO e tracciamento conversioni.", forText: "Per artigiani, riparazioni, studi beauty, wellness e altri servizi locali.", whyItMatters: "Un sito locale aiuta i clienti vicini a capire, fidarsi e contattare l'attività." },
      "shopify-consultant-portfolio": { title: "Sito portfolio per consulente Shopify", shortDescription: "Trasforma il cold outreach in fiducia con un sito portfolio professionale.", features: ["Sito di personal brand", "Vetrina servizi", "Testimonianze", "Case study", "CTA lead generation", "Basi SEO"], forText: "Per consulenti Shopify, agenzie marketing, specialisti SEO, esperti CRO, consulenti email marketing, specialisti paid ads e freelance che vendono servizi tramite outreach.", challenges: ["I prospect non possono verificare facilmente il mittente", "Il cold outreach genera poca fiducia", "Servizi e prove sono sparsi", "LinkedIn da solo non mostra l'offerta completa"], included: ["Sito responsive", "Sezioni servizi", "Sezione testimonianze", "Struttura case study", "CTA per lead", "Struttura adatta ai motori di ricerca"], whyItMatters: "Un sito portfolio premium offre ai prospect dell'outreach un luogo credibile per verificare competenza, capire l'offerta e decidere se continuare la conversazione." },
      "ai-assistant": { title: "Assistente clienti AI", shortDescription: "Demo di assistente AI per domande ripetitive, qualificazione lead, ricerca FAQ, passaggio al contatto e semplice automazione del supporto.", forText: "Per PMI che rispondono a domande ripetitive e vogliono una prima risposta più veloce.", whyItMatters: "Un assistente AI può ridurre le interruzioni ripetitive e qualificare le richieste prima del follow-up umano." },
      "analytics-dashboard": { title: "Dashboard analytics", shortDescription: "Demo dashboard per performance del sito, conversioni, pagine migliori, fonti delle richieste, insight marketing e report.", forText: "Per aziende in crescita che vogliono più chiarezza su sito e marketing.", whyItMatters: "Una dashboard rende visibili le performance e aiuta a scegliere priorità marketing migliori." },
    },
  },
  cz: {
    seo: { title: "Dema webů a AI automatizace - Websiteli", description: "Dema Websiteli pro weby malých firem, AI automatizaci, analytiku, SEO a získávání leadů.", keywords: en.seo.keywords },
    eyebrow: "Dema", title: "Podívejte se, co Websiteli umí vytvořit.", text: "Praktická dema webů, automatizace, analytiky a získávání poptávek.",
    labels: { ...en.labels, recommendedPackage: "Doporučený balíček", features: "Technologie a funkce", learnMore: "Zjistit více", for: "Pro koho", commonChallenges: "Typické výzvy", included: "Součástí", businessImpact: "Business dopad", viewLiveDemo: "Zobrazit live demo", requestSimilar: "Poptat podobný web", viewAnalysis: "Zobrazit analýzu příležitosti", primaryCta: "Požádat o bezplatný digitální audit", secondaryCta: "Rezervovat discovery call" },
    packageNames: { "Growth Setup": "Růstový balíček", "AI/Data Upgrade": "AI a datové rozšíření" },
    items: {
      restaurant: { title: "Web restaurace / kavárny", shortDescription: "Moderní web restaurace s online rezervacemi, SEO, analytikou, recenzemi, mapami a kontaktními formuláři.", forText: "Pro restaurace, kavárny, pekárny a lokální gastro podniky.", whyItMatters: "Profesionální web může zlepšit viditelnost a usnadnit zákazníkům rezervace." },
      consultant: { title: "Web konzultanta / kouče", shortDescription: "Profesionální web služeb s pozicováním, rezervacemi, sběrem leadů, newsletterem, analytikou a SEO základy.", forText: "Pro konzultanty, kouče, poradce a nezávislé profesionály.", whyItMatters: "Zaměřený web může převést zájem na rezervované hovory a zpřehlednit nabídku." },
      "local-service": { title: "Web lokální služby", shortDescription: "Lokální web se službami, poptávkami, prvky důvěry, podporou Google Business, SEO a měřením konverzí.", forText: "Pro řemeslníky, opravy, beauty studia, wellness a další lokální služby.", whyItMatters: "Lokální web pomáhá blízkým zákazníkům pochopit, důvěřovat a kontaktovat firmu." },
      "shopify-consultant-portfolio": { title: "Portfolio web pro Shopify konzultanta", shortDescription: "Proměňte cold outreach v důvěru pomocí profesionálního portfolio webu.", features: ["Web osobní značky", "Přehled služeb", "Reference", "Případové studie", "CTA pro leady", "SEO základy"], forText: "Pro Shopify konzultanty, marketingové agentury, SEO specialisty, CRO experty, konzultanty e-mail marketingu, specialisty na placenou reklamu a freelancery prodávající služby přes outreach.", challenges: ["Prospekti nemohou snadno ověřit odesílatele", "Cold outreach má nízkou důvěru", "Služby a důkazy jsou roztříštěné", "LinkedIn sám neukáže celou nabídku"], included: ["Responzivní web", "Sekce služeb", "Sekce referencí", "Struktura případových studií", "CTA pro získávání leadů", "Struktura vhodná pro vyhledávače"], whyItMatters: "Prémiový portfolio web dává prospektům z outreachu důvěryhodné místo, kde si ověří odbornost, pochopí nabídku a rozhodnou se, zda pokračovat v konverzaci." },
      "ai-assistant": { title: "AI zákaznický asistent", shortDescription: "Demo AI asistenta pro opakované dotazy, kvalifikaci leadů, FAQ vyhledávání, předání kontaktu a jednoduchou automatizaci podpory.", forText: "Pro malé a střední firmy, které řeší opakované otázky a chtějí rychlejší první odpověď.", whyItMatters: "AI asistent může snížit opakovaná vyrušení a předkvalifikovat poptávky." },
      "analytics-dashboard": { title: "Analytický dashboard", shortDescription: "Demo dashboardu pro výkon webu, konverze, nejlepší stránky, zdroje poptávek, marketingové poznatky a reporty.", forText: "Pro rostoucí firmy, které potřebují jasnější pohled na výkon webu a marketingu.", whyItMatters: "Dashboard zviditelní výkon webu a pomůže lépe prioritizovat marketing." },
    },
  },
  pt: {
    seo: { title: "Demos de sites e automação AI - Websiteli", description: "Demos Websiteli para sites de pequenas empresas, automação AI, analytics, SEO e geração de leads.", keywords: en.seo.keywords },
    eyebrow: "Demos", title: "Veja o que a Websiteli pode criar.", text: "Conceitos demo para sites, automação, analytics e geração de leads.",
    labels: { ...en.labels, recommendedPackage: "Pacote recomendado", features: "Tecnologias e funcionalidades", learnMore: "Saber mais", for: "Para", commonChallenges: "Desafios comuns", included: "Incluído", businessImpact: "Impacto no negócio", viewLiveDemo: "Ver demo ao vivo", requestSimilar: "Pedir site semelhante", viewAnalysis: "Ver análise de oportunidade", primaryCta: "Pedir auditoria digital gratuita", secondaryCta: "Marcar discovery call" },
    packageNames: { "Growth Setup": "Pacote de crescimento", "AI/Data Upgrade": "Upgrade de IA e dados" },
    items: {
      restaurant: { title: "Site para restaurante / café", shortDescription: "Site moderno para restaurante com reservas online, SEO, analytics, avaliações, mapas e formulários de contacto.", forText: "Para restaurantes, cafés, pastelarias e negócios locais de comida.", whyItMatters: "Um site profissional pode melhorar a visibilidade e facilitar reservas." },
      consultant: { title: "Site para consultor / coach", shortDescription: "Site profissional com posicionamento, marcações, captação de leads, newsletter, analytics e bases SEO.", forText: "Para consultores, coaches, assessores e profissionais independentes.", whyItMatters: "Um site focado pode transformar interesse em chamadas marcadas e tornar a oferta mais clara." },
      "local-service": { title: "Site para negócio local de serviços", shortDescription: "Site local com áreas de serviço, pedidos de orçamento, sinais de confiança, apoio Google Business, SEO e tracking de conversões.", forText: "Para serviços técnicos, reparações, beleza, wellness e outros serviços locais.", whyItMatters: "Um site local ajuda clientes próximos a compreender, confiar e contactar o negócio." },
      "shopify-consultant-portfolio": { title: "Site portefólio para consultor Shopify", shortDescription: "Transforme cold outreach em confiança com um site portefólio profissional.", features: ["Site de marca pessoal", "Apresentação de serviços", "Testemunhos", "Estudos de caso", "CTA de geração de leads", "Bases SEO"], forText: "Para consultores Shopify, agências de marketing, especialistas SEO, especialistas CRO, consultores de email marketing, especialistas em anúncios pagos e freelancers que vendem serviços por outreach.", challenges: ["Os prospects não conseguem verificar facilmente o remetente", "O cold outreach gera pouca confiança", "Serviços e provas estão dispersos", "LinkedIn sozinho não mostra a oferta completa"], included: ["Site responsivo", "Secções de serviços", "Secção de testemunhos", "Estrutura de estudos de caso", "CTA para leads", "Estrutura adequada a motores de busca"], whyItMatters: "Um site portefólio premium dá aos prospects de outreach um lugar credível para verificar experiência, compreender a oferta e decidir se continuam a conversa." },
      "ai-assistant": { title: "Assistente de clientes com IA", shortDescription: "Demo de assistente IA para perguntas repetitivas, qualificação de leads, pesquisa FAQ, passagem para contacto e automação simples de apoio.", forText: "Para PME que respondem a perguntas repetidas e querem uma primeira resposta mais rápida.", whyItMatters: "Um assistente IA pode reduzir interrupções repetitivas e qualificar pedidos antes do seguimento humano." },
      "analytics-dashboard": { title: "Dashboard analytics", shortDescription: "Demo de dashboard para desempenho do site, conversões, melhores páginas, fontes de pedidos, insights de marketing e relatórios.", forText: "Para empresas em crescimento que precisam de mais clareza sobre website e marketing.", whyItMatters: "Um dashboard torna o desempenho visível e ajuda a definir melhores prioridades de marketing." },
    },
  },
  da: {
    seo: { title: "Website-demoer og AI-automatisering - Websiteli", description: "Websiteli-demoer til små virksomheders websites, AI-automatisering, analytics, SEO og leadgenerering.", keywords: en.seo.keywords },
    eyebrow: "Demoer", title: "Se hvad Websiteli kan bygge.", text: "Praktiske demoer til websites, automatisering, analytics og leadgenerering.",
    labels: { ...en.labels, recommendedPackage: "Anbefalet pakke", features: "Teknologier og funktioner", learnMore: "Læs mere", for: "For", commonChallenges: "Typiske udfordringer", included: "Inkluderet", businessImpact: "Forretningsværdi", viewLiveDemo: "Se live demo", requestSimilar: "Anmod om lignende website", viewAnalysis: "Se mulighedsanalyse", primaryCta: "Anmod om gratis digital audit", secondaryCta: "Book discovery call" },
    packageNames: { "Growth Setup": "Vækstpakke", "AI/Data Upgrade": "AI- og dataopgradering" },
    items: {
      restaurant: { title: "Restaurant- / caféwebsite", shortDescription: "Moderne restaurantwebsite med online reservationer, SEO, analytics, anmeldelser, kort og kontaktformularer.", forText: "For restauranter, caféer, bagerier og lokale madvirksomheder.", whyItMatters: "Et professionelt website kan forbedre synlighed og gøre reservationer lettere." },
      consultant: { title: "Website til konsulent / coach", shortDescription: "Professionelt servicewebsite med positionering, booking, leadopsamling, nyhedsbrev, analytics og SEO-basics.", forText: "For konsulenter, coaches, rådgivere og selvstændige specialister.", whyItMatters: "Et fokuseret website kan gøre interesse til bookede samtaler og gøre tilbuddet lettere at forstå." },
      "local-service": { title: "Website til lokal servicevirksomhed", shortDescription: "Lokalt website med serviceområder, tilbudsforespørgsler, tillidssignaler, Google Business-support, SEO og konverteringssporing.", forText: "For håndværkere, reparationsservices, beauty-studier, wellness og andre lokale services.", whyItMatters: "Et lokalt servicewebsite gør det lettere for nærliggende kunder at forstå, stole på og kontakte virksomheden." },
      "shopify-consultant-portfolio": { title: "Portfolio-website til Shopify-konsulent", shortDescription: "Gør kold outreach til tillid med et professionelt portfolio-website.", features: ["Personligt brand-website", "Servicepræsentation", "Testimonials", "Cases", "Leadgenererende CTA", "SEO-grundlag"], forText: "For Shopify-konsulenter, marketingbureauer, SEO-specialister, CRO-eksperter, e-mailmarketingkonsulenter, paid ads-specialister og freelancere, der sælger services via outreach.", challenges: ["Prospects kan ikke nemt verificere afsenderen", "Kold outreach skaber lav tillid", "Services og beviser er spredte", "LinkedIn alene viser ikke hele tilbuddet"], included: ["Responsivt website", "Servicesektioner", "Testimonials-sektion", "Casestruktur", "Leadgenererende CTA", "Søgevenlig sidestruktur"], whyItMatters: "Et premium portfolio-website giver outreach-prospects et troværdigt sted at verificere ekspertise, forstå tilbuddet og beslutte, om dialogen skal fortsætte." },
      "ai-assistant": { title: "AI-kundeassistent", shortDescription: "Demo af AI-assistent til gentagne kundespørgsmål, leadkvalificering, FAQ-søgning, kontakt-overdragelse og enkel supportautomatisering.", forText: "For SMV'er, der besvarer gentagne spørgsmål og ønsker hurtigere første svar.", whyItMatters: "En AI-assistent kan reducere gentagne afbrydelser og kvalificere henvendelser før menneskelig opfølgning." },
      "analytics-dashboard": { title: "Analytics-dashboard", shortDescription: "Dashboard-demo til website-performance, konverteringer, bedste sider, henvendelseskilder, marketingindsigter og rapportering.", forText: "For voksende virksomheder, der ønsker mere klarhed over website- og marketingperformance.", whyItMatters: "Et dashboard gør performance synlig og hjælper med bedre marketingprioriteringer." },
    },
  },
  nl: {
    seo: { title: "Website-demo's en AI-automatisering - Websiteli", description: "Websiteli-demo's voor websites van kleine bedrijven, AI-automatisering, analytics, SEO en leadgeneratie.", keywords: en.seo.keywords },
    eyebrow: "Demo's", title: "Bekijk wat Websiteli kan bouwen.", text: "Praktische demo's voor websites, automatisering, analytics en leadgeneratie.",
    labels: { ...en.labels, recommendedPackage: "Aanbevolen pakket", features: "Technologieën en functies", learnMore: "Meer informatie", for: "Voor", commonChallenges: "Veelvoorkomende uitdagingen", included: "Inbegrepen", businessImpact: "Zakelijke impact", viewLiveDemo: "Bekijk live demo", requestSimilar: "Vraag vergelijkbare website aan", viewAnalysis: "Bekijk kansenanalyse", primaryCta: "Vraag een gratis digitale audit aan", secondaryCta: "Boek een discovery call" },
    packageNames: { "Growth Setup": "Groeipakket", "AI/Data Upgrade": "AI- en data-upgrade" },
    items: {
      restaurant: { title: "Website voor restaurant / café", shortDescription: "Moderne restaurantwebsite met online reserveringen, SEO, analytics, reviews, kaarten en contactformulieren.", forText: "Voor restaurants, cafés, bakkerijen en lokale foodbedrijven.", whyItMatters: "Een professionele website kan zichtbaarheid verbeteren en reserveringen makkelijker maken." },
      consultant: { title: "Website voor consultant / coach", shortDescription: "Professionele dienstenwebsite met positionering, boeking, leadcapture, nieuwsbrief, analytics en SEO-basis.", forText: "Voor consultants, coaches, adviseurs en zelfstandige dienstverleners.", whyItMatters: "Een gerichte website kan interesse omzetten in geboekte gesprekken en het aanbod duidelijker maken." },
      "local-service": { title: "Website voor lokaal servicebedrijf", shortDescription: "Lokale bedrijfswebsite met servicegebieden, offerteaanvragen, vertrouwen, Google Business-ondersteuning, SEO en conversietracking.", forText: "Voor vakmensen, reparatieservices, beautystudio's, wellness en andere lokale diensten.", whyItMatters: "Een lokale servicewebsite helpt klanten in de buurt het bedrijf te begrijpen, vertrouwen en contacteren." },
      "shopify-consultant-portfolio": { title: "Portfolio-website voor Shopify-consultant", shortDescription: "Zet koude outreach om in vertrouwen met een professionele portfolio-website.", features: ["Website voor persoonlijk merk", "Servicepresentatie", "Testimonials", "Cases", "Leadgeneratie-CTA", "SEO-basis"], forText: "Voor Shopify-consultants, marketingbureaus, SEO-specialisten, CRO-experts, e-mailmarketingconsultants, paid ads-specialisten en freelancers die diensten verkopen via outreach.", challenges: ["Prospects kunnen de afzender niet makkelijk verifiëren", "Koude outreach wekt weinig vertrouwen", "Services en bewijs zijn verspreid", "LinkedIn alleen toont niet het volledige aanbod"], included: ["Responsive website", "Servicesecties", "Testimonials-sectie", "Casestructuur", "Leadgeneratie-CTA", "Zoekvriendelijke paginastructuur"], whyItMatters: "Een premium portfolio-website geeft outreach-prospects een geloofwaardige plek om expertise te verifiëren, het aanbod te begrijpen en te beslissen of ze het gesprek voortzetten." },
      "ai-assistant": { title: "AI-klantassistent", shortDescription: "Demo van AI-assistent voor herhalende klantvragen, leadkwalificatie, FAQ-zoekfunctie, contactoverdracht en eenvoudige supportautomatisering.", forText: "Voor MKB-bedrijven die herhaalde vragen beantwoorden en sneller eerste antwoord willen geven.", whyItMatters: "Een AI-assistent kan herhaalde onderbrekingen verminderen en aanvragen kwalificeren voordat een mens opvolgt." },
      "analytics-dashboard": { title: "Analytics-dashboard", shortDescription: "Dashboarddemo voor websiteprestaties, conversies, beste pagina's, aanvraagbronnen, marketinginzichten en rapportage.", forText: "Voor groeiende bedrijven die meer inzicht willen in website- en marketingprestaties.", whyItMatters: "Een dashboard maakt prestaties zichtbaar en helpt betere marketingprioriteiten te stellen." },
    },
  },
  ja: {
    seo: { title: "WebサイトデモとAI自動化例 - Websiteli", description: "小規模ビジネス向けWebサイト、AI自動化、分析、SEO、リード獲得のWebsiteliデモ。", keywords: en.seo.keywords },
    eyebrow: "デモ", title: "Websiteliで構築できるもの。", text: "Webサイト、自動化、分析、リード獲得の実用的なデモです。",
    labels: { ...en.labels, recommendedPackage: "推奨パッケージ", features: "技術と機能", learnMore: "詳しく見る", for: "対象", commonChallenges: "よくある課題", included: "含まれる内容", businessImpact: "ビジネス効果", viewLiveDemo: "ライブデモを見る", requestSimilar: "同様のサイトを相談する", viewAnalysis: "機会分析を見る", primaryCta: "無料デジタル監査を依頼", secondaryCta: "ディスカバリーコールを予約" },
    packageNames: { "Growth Setup": "成長支援パッケージ", "AI/Data Upgrade": "AI・データ強化" },
    items: {
      restaurant: { title: "レストラン / カフェWebサイト", shortDescription: "オンライン予約、SEO、分析、レビュー、地図、問い合わせフォームを備えたモダンなレストランサイト。", forText: "レストラン、カフェ、ベーカリー、地域の飲食ビジネス向け。", whyItMatters: "専門的なWebサイトは可視性を高め、顧客の予約を簡単にできます。" },
      consultant: { title: "コンサルタント / コーチWebサイト", shortDescription: "ポジショニング、予約、リード獲得、ニュースレター登録、分析、SEO基盤を備えた専門サービスサイト。", forText: "コンサルタント、コーチ、アドバイザー、独立系専門サービス向け。", whyItMatters: "焦点を絞ったWebサイトは関心を予約済みの相談へ変え、提供内容を分かりやすくします。" },
      "local-service": { title: "地域サービス事業Webサイト", shortDescription: "サービスエリア、見積依頼、信頼要素、Google Business支援、SEO、コンバージョン計測を備えた地域向けサイト。", forText: "修理、職人、ビューティー、ウェルネスなど地域サービス事業向け。", whyItMatters: "地域サービスサイトは近隣の顧客が事業を理解し、信頼し、連絡しやすくします。" },
      "shopify-consultant-portfolio": { title: "Shopifyコンサルタント向けポートフォリオサイト", shortDescription: "プロフェッショナルなポートフォリオサイトで、コールドアウトリーチを信頼につなげます。", features: ["パーソナルブランドサイト", "サービス紹介", "お客様の声", "ケーススタディ", "リード獲得CTA", "SEO基盤"], forText: "Shopifyコンサルタント、マーケティング代理店、SEO専門家、CRO専門家、メールマーケティングコンサルタント、広告運用専門家、アウトリーチでサービスを販売するフリーランス向け。", challenges: ["見込み客が送信者を簡単に確認できない", "コールドアウトリーチは信頼を得にくい", "サービス内容と実績が散らばっている", "LinkedInだけでは提案全体を示しきれない"], included: ["レスポンシブWebサイト", "サービスセクション", "お客様の声セクション", "ケーススタディ構成", "リード獲得CTA", "検索に適したページ構成"], whyItMatters: "プレミアムなポートフォリオサイトは、アウトリーチ先の見込み客が専門性を確認し、提案を理解し、会話を続けるか判断できる信頼性のある場所になります。" },
      "ai-assistant": { title: "AI顧客アシスタント", shortDescription: "反復的な顧客質問、リード判定、FAQ検索、問い合わせ引き継ぎ、簡単なサポート自動化のAIアシスタントデモ。", forText: "繰り返しの質問に対応し、より速い初回回答を望む中小企業向け。", whyItMatters: "AIアシスタントは反復的な中断を減らし、人が対応する前に問い合わせを整理できます。" },
      "analytics-dashboard": { title: "分析ダッシュボード", shortDescription: "Webサイト成果、コンバージョン、上位ページ、問い合わせ元、マーケティング洞察、レポート用のダッシュボードデモ。", forText: "Webサイトとマーケティング成果をより明確に把握したい成長企業向け。", whyItMatters: "ダッシュボードは成果を見える化し、より良いマーケティング優先順位を決める助けになります。" },
    },
  },
};

const termTranslations: Partial<Record<LocaleCode, Record<string, string>>> = {
  de: {
    "Responsive website": "Responsive Website",
    "Online reservation flow": "Online-Reservierungsablauf",
    "Menu sections": "Menübereiche",
    Reviews: "Bewertungen",
    Maps: "Karten",
    Analytics: "Analytics",
    "SEO setup": "SEO-Einrichtung",
    "Booking integration": "Buchungsintegration",
    "Contact forms": "Kontaktformulare",
    "Customer assistant": "Kundenassistent",
    "FAQ knowledge base": "FAQ-Wissensbasis",
    "Lead qualification prompts": "Prompts zur Lead-Qualifizierung",
    "Contact handoff": "Kontaktübergabe",
    "Conversation analytics": "Konversationsanalyse",
    "Basic workflow automation": "Einfache Workflow-Automatisierung",
  },
  hu: {
    "Responsive website": "Reszponzív weboldal",
    "Online reservation flow": "Online foglalási folyamat",
    "Menu sections": "Menü szekciók",
    Reviews: "Értékelések",
    Maps: "Térkép",
    Analytics: "Analitika",
    "SEO setup": "SEO beállítás",
    "Booking integration": "Foglalási integráció",
    "Contact forms": "Kapcsolati űrlapok",
    "Customer assistant": "Ügyfélasszisztens",
    "FAQ knowledge base": "FAQ tudásbázis",
    "Lead qualification prompts": "Lead minősítési promptok",
    "Contact handoff": "Kapcsolatátadás",
    "Conversation analytics": "Beszélgetésanalitika",
    "Basic workflow automation": "Alap workflow automatizálás",
  },
  pl: {
    "Responsive website": "Responsywna strona",
    "Online reservation flow": "Proces rezerwacji online",
    "Menu sections": "Sekcje menu",
    Reviews: "Opinie",
    Maps: "Mapy",
    Analytics: "Analityka",
    "SEO setup": "Konfiguracja SEO",
    "Booking integration": "Integracja rezerwacji",
    "Contact forms": "Formularze kontaktowe",
    "Customer assistant": "Asystent klienta",
    "FAQ knowledge base": "Baza wiedzy FAQ",
    "Lead qualification prompts": "Prompty kwalifikacji leadów",
    "Contact handoff": "Przekazanie kontaktu",
    "Conversation analytics": "Analityka rozmów",
    "Basic workflow automation": "Podstawowa automatyzacja workflow",
  },
  es: {
    "Responsive website": "Web responsive",
    "Online reservation flow": "Flujo de reservas online",
    "Menu sections": "Secciones de menú",
    Reviews: "Reseñas",
    Maps: "Mapas",
    Analytics: "Analítica",
    "SEO setup": "Configuración SEO",
    "Booking integration": "Integración de reservas",
    "Contact forms": "Formularios de contacto",
    "Customer assistant": "Asistente de clientes",
    "FAQ knowledge base": "Base de conocimiento FAQ",
    "Lead qualification prompts": "Indicaciones para cualificar leads",
    "Contact handoff": "Traspaso a contacto",
    "Conversation analytics": "Analítica de conversaciones",
    "Basic workflow automation": "Automatización básica de flujos",
  },
  fr: {
    "Responsive website": "Site responsive",
    "Online reservation flow": "Parcours de réservation en ligne",
    "Menu sections": "Sections menu",
    Reviews: "Avis",
    Maps: "Cartes",
    Analytics: "Analytics",
    "SEO setup": "Configuration SEO",
    "Booking integration": "Intégration réservation",
    "Contact forms": "Formulaires de contact",
    "Customer assistant": "Assistant client",
    "FAQ knowledge base": "Base de connaissances FAQ",
    "Lead qualification prompts": "Prompts de qualification des leads",
    "Contact handoff": "Transfert vers le contact",
    "Conversation analytics": "Analytics des conversations",
    "Basic workflow automation": "Automatisation simple de workflow",
  },
  it: {
    "Responsive website": "Sito responsive",
    "Online reservation flow": "Flusso prenotazioni online",
    "Menu sections": "Sezioni menù",
    Reviews: "Recensioni",
    Maps: "Mappe",
    Analytics: "Analytics",
    "SEO setup": "Configurazione SEO",
    "Booking integration": "Integrazione prenotazioni",
    "Contact forms": "Moduli di contatto",
    "Repetitive questions interrupt daily work": "Le domande ripetitive interrompono il lavoro quotidiano",
    "Leads arrive without enough context": "I lead arrivano senza contesto sufficiente",
    "Customers wait for basic answers": "I clienti aspettano risposte di base",
    "Support knowledge is not centralized": "La conoscenza di supporto non è centralizzata",
    "Customer assistant": "Assistente clienti",
    "FAQ knowledge base": "Base FAQ",
    "Lead qualification prompts": "Prompt di qualificazione lead",
    "Contact handoff": "Passaggio al contatto",
    "Conversation analytics": "Analisi conversazioni",
    "Basic workflow automation": "Automazione workflow di base",
  },
  cz: {
    "Responsive website": "Responzivní web",
    "Online reservation flow": "Online rezervační proces",
    "Menu sections": "Sekce menu",
    Reviews: "Recenze",
    Maps: "Mapy",
    Analytics: "Analytika",
    "SEO setup": "Nastavení SEO",
    "Booking integration": "Integrace rezervací",
    "Contact forms": "Kontaktní formuláře",
    "Repetitive questions interrupt daily work": "Opakované otázky přerušují každodenní práci",
    "Leads arrive without enough context": "Leady přicházejí bez dostatečného kontextu",
    "Customers wait for basic answers": "Zákazníci čekají na základní odpovědi",
    "Support knowledge is not centralized": "Znalosti podpory nejsou centralizované",
    "Customer assistant": "Zákaznický asistent",
    "FAQ knowledge base": "FAQ znalostní báze",
    "Lead qualification prompts": "Podklady pro kvalifikaci leadů",
    "Contact handoff": "Předání kontaktu",
    "Conversation analytics": "Analytika konverzací",
    "Basic workflow automation": "Základní automatizace workflow",
  },
  pt: {
    "Responsive website": "Site responsivo",
    "Online reservation flow": "Fluxo de reservas online",
    "Menu sections": "Secções de menu",
    Reviews: "Avaliações",
    Maps: "Mapas",
    Analytics: "Analytics",
    "SEO setup": "Configuração SEO",
    "Booking integration": "Integração de reservas",
    "Contact forms": "Formulários de contacto",
    "Repetitive questions interrupt daily work": "Perguntas repetitivas interrompem o trabalho diário",
    "Leads arrive without enough context": "Leads chegam sem contexto suficiente",
    "Customers wait for basic answers": "Clientes esperam por respostas básicas",
    "Support knowledge is not centralized": "O conhecimento de apoio não está centralizado",
    "Customer assistant": "Assistente de clientes",
    "FAQ knowledge base": "Base de conhecimento FAQ",
    "Lead qualification prompts": "Prompts de qualificação de leads",
    "Contact handoff": "Passagem para contacto",
    "Conversation analytics": "Analítica de conversas",
    "Basic workflow automation": "Automação básica de workflows",
  },
  da: {
    "Responsive website": "Responsivt website",
    "Online reservation flow": "Online reservationsflow",
    "Menu sections": "Menusektioner",
    Reviews: "Anmeldelser",
    Maps: "Kort",
    Analytics: "Analytics",
    "SEO setup": "SEO-opsætning",
    "Booking integration": "Bookingintegration",
    "Contact forms": "Kontaktformularer",
    "Repetitive questions interrupt daily work": "Gentagne spørgsmål afbryder det daglige arbejde",
    "Leads arrive without enough context": "Leads kommer uden nok kontekst",
    "Customers wait for basic answers": "Kunder venter på grundlæggende svar",
    "Support knowledge is not centralized": "Supportviden er ikke samlet ét sted",
    "Customer assistant": "Kundeassistent",
    "FAQ knowledge base": "FAQ-vidensbase",
    "Lead qualification prompts": "Prompts til leadkvalificering",
    "Contact handoff": "Overdragelse til kontakt",
    "Conversation analytics": "Samtaleanalyse",
    "Basic workflow automation": "Grundlæggende workflowautomatisering",
  },
  nl: {
    "Responsive website": "Responsieve website",
    "Online reservation flow": "Online reserveringsflow",
    "Menu sections": "Menusecties",
    Reviews: "Reviews",
    Maps: "Kaarten",
    Analytics: "Analytics",
    "SEO setup": "SEO-instelling",
    "Booking integration": "Boekingsintegratie",
    "Contact forms": "Contactformulieren",
    "Repetitive questions interrupt daily work": "Herhalende vragen onderbreken het dagelijkse werk",
    "Leads arrive without enough context": "Leads komen binnen zonder genoeg context",
    "Customers wait for basic answers": "Klanten wachten op basisantwoorden",
    "Support knowledge is not centralized": "Supportkennis is niet gecentraliseerd",
    "Customer assistant": "Klantassistent",
    "FAQ knowledge base": "FAQ-kennisbank",
    "Lead qualification prompts": "Prompts voor leadkwalificatie",
    "Contact handoff": "Overdracht naar contact",
    "Conversation analytics": "Gespreksanalyse",
    "Basic workflow automation": "Basis workflowautomatisering",
  },
  ja: {
    "Responsive website": "レスポンシブWebサイト",
    "Online reservation flow": "オンライン予約導線",
    "Menu sections": "メニューセクション",
    Reviews: "レビュー",
    Maps: "地図",
    Analytics: "分析",
    "SEO setup": "SEO設定",
    "Booking integration": "予約連携",
    "Contact forms": "問い合わせフォーム",
    "Repetitive questions interrupt daily work": "繰り返しの質問が日常業務を中断する",
    "Leads arrive without enough context": "リードが十分な文脈なしで届く",
    "Customers wait for basic answers": "顧客が基本的な回答を待つ",
    "Support knowledge is not centralized": "サポート知識が一元化されていない",
    "Customer assistant": "顧客アシスタント",
    "FAQ knowledge base": "FAQナレッジベース",
    "Lead qualification prompts": "リード判定プロンプト",
    "Contact handoff": "問い合わせ引き継ぎ",
    "Conversation analytics": "会話分析",
    "Basic workflow automation": "基本的なワークフロー自動化",
  },
};

const additionalTermTranslations: Partial<Record<LocaleCode, Record<string, string>>> = {
  de: {
    "Service pages": "Leistungsseiten",
    "Booking flow": "Buchungsablauf",
    "Lead capture": "Lead-Erfassung",
    "Newsletter signup": "Newsletter-Anmeldung",
    "Offer pages": "Angebotsseiten",
    "Lead-capture form": "Formular zur Lead-Erfassung",
    "Newsletter setup": "Newsletter-Einrichtung",
    "Quote forms": "Anfrageformulare",
    "Service areas": "Leistungsgebiete",
    "Trust sections": "Vertrauensbereiche",
    "Local SEO": "Lokale SEO",
    "Service area pages": "Seiten für Leistungsgebiete",
    "Quote request form": "Anfrageformular",
    "Google Business Profile support": "Unterstützung für Google Business Profile",
    "Conversion tracking": "Conversion-Tracking",
    "FAQ assistant": "FAQ-Assistent",
    "Lead qualification": "Lead-Qualifizierung",
    "Knowledge base": "Wissensbasis",
    "Conversation tracking": "Konversations-Tracking",
    "Traffic overview": "Traffic-Übersicht",
    "Page insights": "Seiten-Einblicke",
    "Inquiry sources": "Anfragequellen",
    Reports: "Berichte",
    "Marketing decisions": "Marketingentscheidungen",
    "Analytics dashboard": "Analytics-Dashboard",
    "Conversion events": "Conversion-Ereignisse",
    "Source tracking": "Quellen-Tracking",
    "Page performance view": "Ansicht der Seitenleistung",
    "Monthly reporting structure": "Monatliche Reporting-Struktur",
    "Decision-focused metrics": "Entscheidungsorientierte Kennzahlen",
  },
  hu: {
    "Service pages": "Szolgáltatási oldalak",
    "Booking flow": "Foglalási folyamat",
    "Lead capture": "Érdeklődőgyűjtés",
    "Newsletter signup": "Hírlevél-feliratkozás",
    "Offer pages": "Ajánlati oldalak",
    "Lead-capture form": "Érdeklődőgyűjtő űrlap",
    "Newsletter setup": "Hírlevél beállítás",
    "Quote forms": "Ajánlatkérő űrlapok",
    "Service areas": "Szolgáltatási területek",
    "Trust sections": "Bizalmi szekciók",
    "Local SEO": "Helyi SEO",
    "Service area pages": "Szolgáltatási terület oldalak",
    "Quote request form": "Ajánlatkérő űrlap",
    "Google Business Profile support": "Google Business Profile támogatás",
    "Conversion tracking": "Konverziómérés",
    "FAQ assistant": "FAQ asszisztens",
    "Lead qualification": "Érdeklődőminősítés",
    "Knowledge base": "Tudásbázis",
    "Conversation tracking": "Beszélgetéskövetés",
    "Traffic overview": "Forgalmi áttekintés",
    "Page insights": "Oldalstatisztikák",
    "Inquiry sources": "Megkeresési források",
    Reports: "Riportok",
    "Marketing decisions": "Marketingdöntések",
    "Analytics dashboard": "Analitikai irányítópult",
    "Conversion events": "Konverziós események",
    "Source tracking": "Forráskövetés",
    "Page performance view": "Oldalteljesítmény nézet",
    "Monthly reporting structure": "Havi riportstruktúra",
    "Decision-focused metrics": "Döntéstámogató mérőszámok",
  },
  pl: {
    "Service pages": "Strony usług",
    "Booking flow": "Proces rezerwacji",
    "Lead capture": "Pozyskiwanie leadów",
    "Newsletter signup": "Zapis do newslettera",
    "Offer pages": "Strony oferty",
    "Lead-capture form": "Formularz pozyskiwania leadów",
    "Newsletter setup": "Konfiguracja newslettera",
    "Quote forms": "Formularze wyceny",
    "Service areas": "Obszary usług",
    "Trust sections": "Sekcje zaufania",
    "Local SEO": "Lokalne SEO",
    "Service area pages": "Strony obszarów usług",
    "Quote request form": "Formularz zapytania ofertowego",
    "Google Business Profile support": "Wsparcie Google Business Profile",
    "Conversion tracking": "Śledzenie konwersji",
    "FAQ assistant": "Asystent FAQ",
    "Lead qualification": "Kwalifikacja leadów",
    "Knowledge base": "Baza wiedzy",
    "Conversation tracking": "Śledzenie rozmów",
    "Traffic overview": "Przegląd ruchu",
    "Page insights": "Wgląd w strony",
    "Inquiry sources": "Źródła zapytań",
    Reports: "Raporty",
    "Marketing decisions": "Decyzje marketingowe",
    "Analytics dashboard": "Panel analityczny",
    "Conversion events": "Zdarzenia konwersji",
    "Source tracking": "Śledzenie źródeł",
    "Page performance view": "Widok wyników stron",
    "Monthly reporting structure": "Struktura raportowania miesięcznego",
    "Decision-focused metrics": "Metryki wspierające decyzje",
  },
  es: {
    "Service pages": "Páginas de servicios",
    "Booking flow": "Flujo de reservas",
    "Lead capture": "Captación de leads",
    "Newsletter signup": "Suscripción al boletín",
    "Offer pages": "Páginas de oferta",
    "Lead-capture form": "Formulario de captación de leads",
    "Newsletter setup": "Configuración del boletín",
    "Quote forms": "Formularios de presupuesto",
    "Service areas": "Zonas de servicio",
    "Trust sections": "Secciones de confianza",
    "Local SEO": "SEO local",
    "Service area pages": "Páginas de zonas de servicio",
    "Quote request form": "Formulario de solicitud de presupuesto",
    "Google Business Profile support": "Soporte para Google Business Profile",
    "Conversion tracking": "Seguimiento de conversiones",
    "FAQ assistant": "Asistente FAQ",
    "Lead qualification": "Cualificación de leads",
    "Knowledge base": "Base de conocimiento",
    "Conversation tracking": "Seguimiento de conversaciones",
    "Traffic overview": "Resumen de tráfico",
    "Page insights": "Información de páginas",
    "Inquiry sources": "Fuentes de consultas",
    Reports: "Informes",
    "Marketing decisions": "Decisiones de marketing",
    "Analytics dashboard": "Panel de analítica",
    "Conversion events": "Eventos de conversión",
    "Source tracking": "Seguimiento de fuentes",
    "Page performance view": "Vista de rendimiento de páginas",
    "Monthly reporting structure": "Estructura de informes mensuales",
    "Decision-focused metrics": "Métricas orientadas a decisiones",
  },
  fr: {
    "Service pages": "Pages de services",
    "Booking flow": "Parcours de réservation",
    "Lead capture": "Capture de leads",
    "Newsletter signup": "Inscription newsletter",
    "Offer pages": "Pages d'offre",
    "Lead-capture form": "Formulaire de capture de leads",
    "Newsletter setup": "Configuration newsletter",
    "Quote forms": "Formulaires de devis",
    "Service areas": "Zones de service",
    "Trust sections": "Sections de confiance",
    "Local SEO": "SEO local",
    "Service area pages": "Pages des zones de service",
    "Quote request form": "Formulaire de demande de devis",
    "Google Business Profile support": "Support Google Business Profile",
    "Conversion tracking": "Suivi des conversions",
    "FAQ assistant": "Assistant FAQ",
    "Lead qualification": "Qualification des leads",
    "Knowledge base": "Base de connaissances",
    "Conversation tracking": "Suivi des conversations",
    "Traffic overview": "Vue d'ensemble du trafic",
    "Page insights": "Insights des pages",
    "Inquiry sources": "Sources de demandes",
    Reports: "Rapports",
    "Marketing decisions": "Décisions marketing",
    "Analytics dashboard": "Tableau de bord analytics",
    "Conversion events": "Événements de conversion",
    "Source tracking": "Suivi des sources",
    "Page performance view": "Vue de performance des pages",
    "Monthly reporting structure": "Structure de reporting mensuel",
    "Decision-focused metrics": "Indicateurs orientés décision",
  },
  it: {
    "Customers cannot book online": "I clienti non possono prenotare online",
    "Menu is hard to find": "Il menù è difficile da trovare",
    "Poor mobile experience": "Esperienza mobile debole",
    "Weak search visibility": "Scarsa visibilità nei motori di ricerca",
    "LinkedIn traffic does not convert": "Il traffico da LinkedIn non converte",
    "No owned contact funnel": "Manca un funnel di contatto proprietario",
    "Booking requires manual messages": "Le prenotazioni richiedono messaggi manuali",
    "Expertise is hard to evaluate quickly": "La competenza è difficile da valutare rapidamente",
    "Customers cannot quickly request a quote": "I clienti non possono richiedere rapidamente un preventivo",
    "Service areas are unclear": "Le aree servite non sono chiare",
    "Trust signals are scattered": "I segnali di fiducia sono sparsi",
    "Local SEO is weak": "La SEO locale è debole",
    "Website activity is hard to interpret": "L'attività del sito è difficile da interpretare",
    "No conversion tracking": "Manca il tracciamento delle conversioni",
    "Best-performing pages are unknown": "Le pagine con migliori risultati non sono note",
    "Marketing decisions rely on guesswork": "Le decisioni marketing si basano su ipotesi",
    "Service pages": "Pagine servizi",
    "Booking flow": "Flusso prenotazioni",
    "Lead capture": "Acquisizione lead",
    "Newsletter signup": "Iscrizione newsletter",
    "Offer pages": "Pagine offerta",
    "Lead-capture form": "Modulo acquisizione lead",
    "Newsletter setup": "Configurazione newsletter",
    "Quote forms": "Moduli preventivo",
    "Service areas": "Aree servite",
    "Trust sections": "Sezioni fiducia",
    "Local SEO": "SEO locale",
    "Service area pages": "Pagine aree servite",
    "Quote request form": "Modulo richiesta preventivo",
    "Google Business Profile support": "Supporto Google Business Profile",
    "Conversion tracking": "Tracciamento conversioni",
    "FAQ assistant": "Assistente FAQ",
    "Lead qualification": "Qualificazione lead",
    "Knowledge base": "Base di conoscenza",
    "Conversation tracking": "Tracciamento conversazioni",
    "Traffic overview": "Panoramica traffico",
    "Page insights": "Insight pagine",
    "Inquiry sources": "Fonti richieste",
    Reports: "Report",
    "Marketing decisions": "Decisioni marketing",
    "Analytics dashboard": "Dashboard analytics",
    "Conversion events": "Eventi di conversione",
    "Source tracking": "Tracciamento fonti",
    "Page performance view": "Vista performance pagine",
    "Monthly reporting structure": "Struttura report mensile",
    "Decision-focused metrics": "Metriche orientate alle decisioni",
  },
  cz: {
    "Customers cannot book online": "Zákazníci nemohou rezervovat online",
    "Menu is hard to find": "Menu je těžké najít",
    "Poor mobile experience": "Slabý mobilní zážitek",
    "Weak search visibility": "Slabá viditelnost ve vyhledávání",
    "LinkedIn traffic does not convert": "Návštěvnost z LinkedIn nekonvertuje",
    "No owned contact funnel": "Chybí vlastní kontaktní funnel",
    "Booking requires manual messages": "Rezervace vyžaduje ruční zprávy",
    "Expertise is hard to evaluate quickly": "Odbornost se těžko rychle posuzuje",
    "Customers cannot quickly request a quote": "Zákazníci nemohou rychle požádat o nabídku",
    "Service areas are unclear": "Oblasti služeb nejsou jasné",
    "Trust signals are scattered": "Prvky důvěry jsou roztříštěné",
    "Local SEO is weak": "Lokální SEO je slabé",
    "Website activity is hard to interpret": "Aktivita webu se těžko interpretuje",
    "No conversion tracking": "Chybí měření konverzí",
    "Best-performing pages are unknown": "Nejvýkonnější stránky nejsou známé",
    "Marketing decisions rely on guesswork": "Marketingová rozhodnutí stojí na odhadech",
    "Service pages": "Stránky služeb",
    "Booking flow": "Rezervační proces",
    "Lead capture": "Sběr leadů",
    "Newsletter signup": "Přihlášení k newsletteru",
    "Offer pages": "Stránky nabídky",
    "Lead-capture form": "Formulář pro sběr leadů",
    "Newsletter setup": "Nastavení newsletteru",
    "Quote forms": "Poptávkové formuláře",
    "Service areas": "Oblasti služeb",
    "Trust sections": "Sekce důvěry",
    "Local SEO": "Lokální SEO",
    "Service area pages": "Stránky oblastí služeb",
    "Quote request form": "Formulář žádosti o nabídku",
    "Google Business Profile support": "Podpora Google Business Profile",
    "Conversion tracking": "Měření konverzí",
    "FAQ assistant": "FAQ asistent",
    "Lead qualification": "Kvalifikace leadů",
    "Knowledge base": "Znalostní báze",
    "Conversation tracking": "Sledování konverzací",
    "Traffic overview": "Přehled návštěvnosti",
    "Page insights": "Přehledy stránek",
    "Inquiry sources": "Zdroje poptávek",
    Reports: "Reporty",
    "Marketing decisions": "Marketingová rozhodnutí",
    "Analytics dashboard": "Analytický dashboard",
    "Conversion events": "Konverzní události",
    "Source tracking": "Sledování zdrojů",
    "Page performance view": "Pohled na výkon stránek",
    "Monthly reporting structure": "Struktura měsíčních reportů",
    "Decision-focused metrics": "Metriky zaměřené na rozhodování",
  },
  pt: {
    "Customers cannot book online": "Os clientes não conseguem reservar online",
    "Menu is hard to find": "O menu é difícil de encontrar",
    "Poor mobile experience": "Experiência móvel fraca",
    "Weak search visibility": "Baixa visibilidade na pesquisa",
    "LinkedIn traffic does not convert": "O tráfego do LinkedIn não converte",
    "No owned contact funnel": "Não há funil de contacto próprio",
    "Booking requires manual messages": "As marcações exigem mensagens manuais",
    "Expertise is hard to evaluate quickly": "A experiência é difícil de avaliar rapidamente",
    "Customers cannot quickly request a quote": "Os clientes não conseguem pedir orçamento rapidamente",
    "Service areas are unclear": "As áreas de serviço não são claras",
    "Trust signals are scattered": "Os sinais de confiança estão dispersos",
    "Local SEO is weak": "O SEO local é fraco",
    "Website activity is hard to interpret": "A atividade do site é difícil de interpretar",
    "No conversion tracking": "Não há tracking de conversões",
    "Best-performing pages are unknown": "As páginas com melhor desempenho são desconhecidas",
    "Marketing decisions rely on guesswork": "As decisões de marketing baseiam-se em suposições",
    "Service pages": "Páginas de serviços",
    "Booking flow": "Fluxo de marcações",
    "Lead capture": "Captação de leads",
    "Newsletter signup": "Subscrição da newsletter",
    "Offer pages": "Páginas da oferta",
    "Lead-capture form": "Formulário de captação de leads",
    "Newsletter setup": "Configuração da newsletter",
    "Quote forms": "Formulários de orçamento",
    "Service areas": "Áreas de serviço",
    "Trust sections": "Secções de confiança",
    "Local SEO": "SEO local",
    "Service area pages": "Páginas de áreas de serviço",
    "Quote request form": "Formulário de pedido de orçamento",
    "Google Business Profile support": "Apoio Google Business Profile",
    "Conversion tracking": "Tracking de conversões",
    "FAQ assistant": "Assistente FAQ",
    "Lead qualification": "Qualificação de leads",
    "Knowledge base": "Base de conhecimento",
    "Conversation tracking": "Tracking de conversas",
    "Traffic overview": "Resumo de tráfego",
    "Page insights": "Insights de páginas",
    "Inquiry sources": "Fontes de pedidos",
    Reports: "Relatórios",
    "Marketing decisions": "Decisões de marketing",
    "Analytics dashboard": "Dashboard analytics",
    "Conversion events": "Eventos de conversão",
    "Source tracking": "Tracking de fontes",
    "Page performance view": "Vista de desempenho das páginas",
    "Monthly reporting structure": "Estrutura de relatórios mensais",
    "Decision-focused metrics": "Métricas orientadas a decisões",
  },
  da: {
    "Customers cannot book online": "Kunder kan ikke reservere online",
    "Menu is hard to find": "Menuen er svær at finde",
    "Poor mobile experience": "Svag mobiloplevelse",
    "Weak search visibility": "Svag synlighed i søgning",
    "LinkedIn traffic does not convert": "LinkedIn-trafik konverterer ikke",
    "No owned contact funnel": "Der mangler en egen kontaktfunnel",
    "Booking requires manual messages": "Booking kræver manuelle beskeder",
    "Expertise is hard to evaluate quickly": "Ekspertise er svær at vurdere hurtigt",
    "Customers cannot quickly request a quote": "Kunder kan ikke hurtigt anmode om et tilbud",
    "Service areas are unclear": "Serviceområder er uklare",
    "Trust signals are scattered": "Tillidssignaler er spredte",
    "Local SEO is weak": "Lokal SEO er svag",
    "Website activity is hard to interpret": "Websiteaktivitet er svær at fortolke",
    "No conversion tracking": "Ingen konverteringssporing",
    "Best-performing pages are unknown": "De bedst præsterende sider er ukendte",
    "Marketing decisions rely on guesswork": "Marketingbeslutninger bygger på gæt",
    "Service pages": "Servicesider",
    "Booking flow": "Bookingflow",
    "Lead capture": "Leadopsamling",
    "Newsletter signup": "Nyhedsbrevstilmelding",
    "Offer pages": "Tilbudssider",
    "Lead-capture form": "Formular til leadopsamling",
    "Newsletter setup": "Opsætning af nyhedsbrev",
    "Quote forms": "Tilbudsformularer",
    "Service areas": "Serviceområder",
    "Trust sections": "Tillidssektioner",
    "Local SEO": "Lokal SEO",
    "Service area pages": "Sider for serviceområder",
    "Quote request form": "Formular til tilbudsforespørgsel",
    "Google Business Profile support": "Support til Google Business Profile",
    "Conversion tracking": "Konverteringssporing",
    "FAQ assistant": "FAQ-assistent",
    "Lead qualification": "Leadkvalificering",
    "Knowledge base": "Vidensbase",
    "Conversation tracking": "Samtalesporing",
    "Traffic overview": "Trafikoverblik",
    "Page insights": "Sideindsigter",
    "Inquiry sources": "Henvendelseskilder",
    Reports: "Rapporter",
    "Marketing decisions": "Marketingbeslutninger",
    "Analytics dashboard": "Analytics-dashboard",
    "Conversion events": "Konverteringshændelser",
    "Source tracking": "Kildesporing",
    "Page performance view": "Visning af sideperformance",
    "Monthly reporting structure": "Månedlig rapporteringsstruktur",
    "Decision-focused metrics": "Beslutningsfokuserede målepunkter",
  },
  nl: {
    "Customers cannot book online": "Klanten kunnen niet online reserveren",
    "Menu is hard to find": "Het menu is moeilijk te vinden",
    "Poor mobile experience": "Zwakke mobiele ervaring",
    "Weak search visibility": "Zwakke zichtbaarheid in zoekmachines",
    "LinkedIn traffic does not convert": "LinkedIn-verkeer converteert niet",
    "No owned contact funnel": "Geen eigen contactfunnel",
    "Booking requires manual messages": "Boekingen vereisen handmatige berichten",
    "Expertise is hard to evaluate quickly": "Expertise is moeilijk snel te beoordelen",
    "Customers cannot quickly request a quote": "Klanten kunnen niet snel een offerte aanvragen",
    "Service areas are unclear": "Servicegebieden zijn onduidelijk",
    "Trust signals are scattered": "Vertrouwenssignalen zijn verspreid",
    "Local SEO is weak": "Lokale SEO is zwak",
    "Website activity is hard to interpret": "Websiteactiviteit is moeilijk te interpreteren",
    "No conversion tracking": "Geen conversietracking",
    "Best-performing pages are unknown": "Best presterende pagina's zijn onbekend",
    "Marketing decisions rely on guesswork": "Marketingbeslissingen steunen op giswerk",
    "Service pages": "Servicepagina's",
    "Booking flow": "Boekingsflow",
    "Lead capture": "Leadcapture",
    "Newsletter signup": "Nieuwsbriefinschrijving",
    "Offer pages": "Aanbodpagina's",
    "Lead-capture form": "Leadcaptureformulier",
    "Newsletter setup": "Nieuwsbriefinstelling",
    "Quote forms": "Offerteformulieren",
    "Service areas": "Servicegebieden",
    "Trust sections": "Vertrouwenssecties",
    "Local SEO": "Lokale SEO",
    "Service area pages": "Pagina's voor servicegebieden",
    "Quote request form": "Offerteaanvraagformulier",
    "Google Business Profile support": "Ondersteuning voor Google Business Profile",
    "Conversion tracking": "Conversietracking",
    "FAQ assistant": "FAQ-assistent",
    "Lead qualification": "Leadkwalificatie",
    "Knowledge base": "Kennisbank",
    "Conversation tracking": "Gesprekstracking",
    "Traffic overview": "Verkeersoverzicht",
    "Page insights": "Pagina-inzichten",
    "Inquiry sources": "Aanvraagbronnen",
    Reports: "Rapporten",
    "Marketing decisions": "Marketingbeslissingen",
    "Analytics dashboard": "Analytics-dashboard",
    "Conversion events": "Conversiegebeurtenissen",
    "Source tracking": "Brontracking",
    "Page performance view": "Weergave van paginaprestaties",
    "Monthly reporting structure": "Maandelijkse rapportagestructuur",
    "Decision-focused metrics": "Beslissingsgerichte statistieken",
  },
  ja: {
    "Customers cannot book online": "顧客がオンライン予約できない",
    "Menu is hard to find": "メニューが見つけにくい",
    "Poor mobile experience": "モバイル体験が弱い",
    "Weak search visibility": "検索での可視性が低い",
    "LinkedIn traffic does not convert": "LinkedInからの訪問が成果につながらない",
    "No owned contact funnel": "自社の問い合わせ導線がない",
    "Booking requires manual messages": "予約に手動メッセージが必要",
    "Expertise is hard to evaluate quickly": "専門性を短時間で判断しにくい",
    "Customers cannot quickly request a quote": "顧客がすぐに見積を依頼できない",
    "Service areas are unclear": "対応エリアが分かりにくい",
    "Trust signals are scattered": "信頼要素が分散している",
    "Local SEO is weak": "地域SEOが弱い",
    "Website activity is hard to interpret": "Webサイトの動きを解釈しにくい",
    "No conversion tracking": "コンバージョン計測がない",
    "Best-performing pages are unknown": "成果の高いページが分からない",
    "Marketing decisions rely on guesswork": "マーケティング判断が推測に頼っている",
    "Service pages": "サービスページ",
    "Booking flow": "予約導線",
    "Lead capture": "リード獲得",
    "Newsletter signup": "ニュースレター登録",
    "Offer pages": "提供内容ページ",
    "Lead-capture form": "リード獲得フォーム",
    "Newsletter setup": "ニュースレター設定",
    "Quote forms": "見積フォーム",
    "Service areas": "対応エリア",
    "Trust sections": "信頼性セクション",
    "Local SEO": "地域SEO",
    "Service area pages": "対応エリアページ",
    "Quote request form": "見積依頼フォーム",
    "Google Business Profile support": "Google Business Profile支援",
    "Conversion tracking": "コンバージョン計測",
    "FAQ assistant": "FAQアシスタント",
    "Lead qualification": "リード判定",
    "Knowledge base": "ナレッジベース",
    "Conversation tracking": "会話追跡",
    "Traffic overview": "トラフィック概要",
    "Page insights": "ページ分析",
    "Inquiry sources": "問い合わせ元",
    Reports: "レポート",
    "Marketing decisions": "マーケティング判断",
    "Analytics dashboard": "分析ダッシュボード",
    "Conversion events": "コンバージョンイベント",
    "Source tracking": "流入元追跡",
    "Page performance view": "ページ成果ビュー",
    "Monthly reporting structure": "月次レポート構成",
    "Decision-focused metrics": "意思決定向け指標",
  },
};

function translateTerms(locale: LocaleCode, values: string[]) {
  const translations = {
    ...(termTranslations[locale] ?? {}),
    ...(additionalTermTranslations[locale] ?? {}),
  };
  return values.map((value) => translations[value] ?? value);
}

export function getDemoPageContent(locale: LocaleCode): DemoPageContent {
  const copy = localized[locale] ?? {};
  return {
    ...en,
    ...copy,
    seo: { ...en.seo, ...copy.seo },
    labels: { ...en.labels, ...copy.labels },
    packageNames: { ...en.packageNames, ...copy.packageNames },
    items: Object.fromEntries(
      Object.entries(en.items).map(([slug, item]) => {
        const mergedItem = {
          ...item,
          ...(copy.items?.[slug as DemoSlug] ?? {}),
        };

        return [
          slug,
          {
            ...mergedItem,
            features: translateTerms(locale, mergedItem.features),
            included: translateTerms(locale, mergedItem.included),
            challenges: translateTerms(locale, mergedItem.challenges),
          },
        ];
      }),
    ) as Record<DemoSlug, DemoContent>,
  };
}

export function getDemo(locale: LocaleCode, slug: DemoSlug) {
  return getDemoPageContent(locale).items[slug];
}
