import type { LocaleCode } from "../../locales";
import type { BlogPostSource, BlogPostTranslation } from "../types";

type LocalizedCopy = {
  title: string;
  description: string;
  category: string;
  readingTime: string;
  audience: string;
  excerpt: string;
  headings: [string, string, string, string, string, string];
  paragraphs: [string, string, string, string, string, string];
};

function makeTranslation(language: LocaleCode, copy: LocalizedCopy): BlogPostTranslation {
  const body = copy.headings
    .map((heading, index) => `## ${heading}\n\n${copy.paragraphs[index]}`)
    .join("\n\n");

  return {
    title: copy.title,
    description: copy.description,
    category: copy.category,
    tags: ["internal AI assistant", "document readiness", "company knowledge base", "AI implementation for SMEs"],
    language,
    readingTime: copy.readingTime,
    audience: copy.audience,
    excerpt: copy.excerpt,
    summary: [copy.excerpt, copy.paragraphs[1], copy.paragraphs[4], copy.paragraphs[5]],
    keyTakeaways: [copy.paragraphs[0], copy.paragraphs[2], copy.paragraphs[4], copy.paragraphs[5]],
    chatGptPrompts: [
      `${copy.headings[0]}: create a practical checklist for my business.`,
      `${copy.headings[4]}: help me map document owners and access rights.`,
      `${copy.headings[5]}: create a retrieval test plan for our first source collection.`,
    ],
    faqs: [
      { question: copy.headings[0], answer: copy.paragraphs[0] },
      { question: copy.headings[1], answer: copy.paragraphs[1] },
      { question: copy.headings[4], answer: copy.paragraphs[4] },
      { question: copy.headings[5], answer: copy.paragraphs[5] },
    ],
    body: `${body}\n\n[Internal AI assistants](/en/services/ai-assistants/) · [AI integrations](/en/services/ai-integrations/) · [Business automation](/en/services/business-automation/) · [Services and pricing](/en/services-pricing/) · [Contact](/en/contact/)`,
  };
}

const translations = {
  en: makeTranslation("en", {
    title: "How to Prepare Company Documents for an Internal AI Assistant",
    description: "A practical document-readiness guide for Swiss and European SMEs planning an internal AI assistant with reliable, permission-aware answers.",
    category: "AI Implementation",
    readingTime: "10 min read",
    audience: "Swiss and European SMEs preparing company knowledge for an internal AI assistant",
    excerpt: "Clean ownership, current versions, access rules and clear document structure matter more than simply uploading everything.",
    headings: ["Start with one business question", "Choose authoritative sources", "Remove duplicates and obsolete versions", "Improve structure and context", "Map ownership and permissions", "Test retrieval before expanding"],
    paragraphs: ["Begin with one task such as finding an approved procedure, preparing a meeting brief or answering an internal policy question. Define what a correct answer looks like, which team will use it and when the assistant must hand the question to a person.", "Select the smallest set of documents that can answer that task. Prefer approved policies, maintained guides, product information and controlled knowledge bases. Informal notes, personal folders and uncertain drafts should not become trusted sources merely because they are easy to access.", "Multiple versions create contradictory answers. Mark the current version, archive or exclude outdated copies and document effective dates. Where two sources disagree, assign an owner to decide which one is authoritative before indexing either document.", "Useful files have descriptive titles, clear headings, readable tables, defined abbreviations and enough context to understand a passage outside the full document. Scanned files may need text extraction and quality checks. A short glossary can improve consistency across teams and languages.", "Record who owns each source, who may read it and how access changes when roles change. The assistant should preserve permissions from the original system. Separate permission to retrieve information from permission to send messages, edit records or publish content.", "Test with real questions, incomplete wording, restricted documents and known edge cases. Check whether the answer cites the correct source, uses the current version and says when evidence is missing. Expand to another source collection only after the first scope is reliable."],
  }),
  de: makeTranslation("de", {
    title: "Unternehmensdokumente für einen internen KI-Assistenten vorbereiten",
    description: "Praxisleitfaden für Schweizer und europäische KMU: Dokumente, Versionen, Zuständigkeiten und Berechtigungen für einen internen KI-Assistenten vorbereiten.",
    category: "KI-Implementierung",
    readingTime: "11 Min. Lesezeit",
    audience: "Schweizer und europäische KMU, die Unternehmenswissen für einen internen KI-Assistenten vorbereiten",
    excerpt: "Klare Zuständigkeiten, aktuelle Versionen, Zugriffsregeln und eine saubere Dokumentstruktur sind wichtiger als möglichst viele Dateien.",
    headings: ["Mit einer konkreten Geschäftsfrage beginnen", "Verbindliche Quellen auswählen", "Duplikate und veraltete Versionen entfernen", "Struktur und Kontext verbessern", "Zuständigkeiten und Berechtigungen abbilden", "Die Suche testen, bevor der Umfang wächst"],
    paragraphs: ["Beginnen Sie mit einer klaren Aufgabe, etwa dem Finden einer gültigen Prozessbeschreibung, der Vorbereitung eines Sitzungsbriefings oder der Beantwortung einer internen Richtlinienfrage. Definieren Sie, wie eine korrekte Antwort aussieht, wer den Assistenten nutzt und wann an eine Person eskaliert werden muss.", "Wählen Sie nur die kleinste Dokumentensammlung, die diese Aufgabe abdeckt. Bevorzugen Sie freigegebene Richtlinien, gepflegte Anleitungen, Produktinformationen und kontrollierte Wissensbestände. Persönliche Ablagen, informelle Notizen und unsichere Entwürfe sollten nicht automatisch zu vertrauenswürdigen Quellen werden.", "Mehrere Versionen führen zu widersprüchlichen Antworten. Kennzeichnen Sie die gültige Fassung, archivieren oder entfernen Sie veraltete Kopien und dokumentieren Sie Gültigkeitsdaten. Wenn Quellen einander widersprechen, muss eine verantwortliche Person festlegen, welche Version verbindlich ist.", "Gute Dokumente haben aussagekräftige Titel, klare Überschriften, lesbare Tabellen, erklärte Abkürzungen und genügend Kontext, damit einzelne Abschnitte verständlich bleiben. Bei Scans sind Texterkennung und Qualitätskontrollen nötig. Ein Glossar hilft besonders bei mehrsprachigen Teams.", "Halten Sie fest, wem jede Quelle gehört, wer sie lesen darf und wie Zugriffe bei Rollenwechseln angepasst werden. Der Assistent muss die Rechte des Ursprungssystems respektieren. Recherche-, Versand-, Bearbeitungs- und Veröffentlichungsrechte sollten getrennt bleiben.", "Testen Sie reale Fragen, unvollständige Formulierungen, gesperrte Dokumente und bekannte Sonderfälle. Prüfen Sie, ob die Antwort die richtige Quelle nennt, die aktuelle Version verwendet und fehlende Belege offenlegt. Erweitern Sie den Umfang erst, wenn der erste Bereich zuverlässig funktioniert."],
  }),
  hu: makeTranslation("hu", { title: "Vállalati dokumentumok előkészítése belső AI-asszisztenshez", description: "Gyakorlati útmutató kkv-knak a dokumentumok, verziók, felelősségek és jogosultságok rendezéséhez belső AI-asszisztens előtt.", category: "AI-bevezetés", readingTime: "9 perc olvasás", audience: "Belső AI-asszisztenst előkészítő svájci és európai kkv-k", excerpt: "A megbízható válaszok alapja a rendezett forrás, az aktuális verzió és az egyértelmű hozzáférés.", headings: ["Egy konkrét üzleti kérdéssel kezdjen", "Válasszon hiteles forrásokat", "Távolítsa el a régi és ismétlődő verziókat", "Javítsa a szerkezetet és a kontextust", "Rögzítse a felelősöket és jogosultságokat", "Tesztelje a keresést bővítés előtt"], paragraphs: ["Határozzon meg egy feladatot, a helyes válasz feltételeit, a felhasználókat és az emberi átadás pontját.", "Csak a szükséges, jóváhagyott szabályzatokat, útmutatókat és tudásbázisokat használja.", "Jelölje az aktuális verziót, archiválja a régit, és oldja fel az ellentmondásokat.", "Használjon világos címeket, címsorokat, olvasható táblázatokat és magyarázott rövidítéseket.", "Dokumentálja a tulajdonost és a hozzáférést; az asszisztens tartsa meg az eredeti jogosultságokat.", "Teszteljen valós kérdésekkel, tiltott dokumentumokkal és hiányos megfogalmazással, majd csak stabil eredmény után bővítsen."] }),
  pl: makeTranslation("pl", { title: "Jak przygotować dokumenty firmowe do wewnętrznego asystenta AI", description: "Praktyczny przewodnik dla MŚP: porządkowanie dokumentów, wersji, właścicieli i uprawnień przed wdrożeniem asystenta AI.", category: "Wdrożenie AI", readingTime: "9 min czytania", audience: "Szwajcarskie i europejskie MŚP przygotowujące wiedzę firmową", excerpt: "Aktualne wersje, jasna własność i poprawne uprawnienia są ważniejsze niż liczba plików.", headings: ["Zacznij od jednego pytania biznesowego", "Wybierz źródła wiarygodne", "Usuń duplikaty i stare wersje", "Popraw strukturę i kontekst", "Przypisz właścicieli i uprawnienia", "Przetestuj wyszukiwanie przed rozszerzeniem"], paragraphs: ["Zdefiniuj jedno zadanie, poprawną odpowiedź, użytkowników i moment przekazania sprawy człowiekowi.", "Użyj najmniejszego zestawu zatwierdzonych polityk, instrukcji i baz wiedzy.", "Oznacz wersję obowiązującą, archiwizuj stare kopie i rozstrzygaj sprzeczności.", "Stosuj jasne tytuły, nagłówki, czytelne tabele i wyjaśnione skróty.", "Udokumentuj właściciela i dostęp; asystent musi zachować prawa systemu źródłowego.", "Testuj prawdziwe pytania, dokumenty ograniczone i brakujące informacje, a zakres rozszerzaj dopiero po stabilizacji."] }),
  es: makeTranslation("es", { title: "Cómo preparar documentos de empresa para un asistente interno de IA", description: "Guía práctica para pymes sobre documentos, versiones, responsables y permisos antes de implantar un asistente interno de IA.", category: "Implementación de IA", readingTime: "9 min de lectura", audience: "Pymes suizas y europeas que preparan conocimiento interno", excerpt: "Las fuentes actuales, bien estructuradas y con permisos claros importan más que cargar todos los archivos.", headings: ["Empieza con una pregunta de negocio", "Elige fuentes autorizadas", "Elimina duplicados y versiones antiguas", "Mejora estructura y contexto", "Asigna responsables y permisos", "Prueba la recuperación antes de ampliar"], paragraphs: ["Define una tarea, una respuesta correcta, los usuarios y cuándo debe intervenir una persona.", "Usa el conjunto mínimo de políticas, guías y bases de conocimiento aprobadas.", "Marca la versión vigente, archiva copias antiguas y resuelve contradicciones.", "Utiliza títulos claros, encabezados, tablas legibles y abreviaturas explicadas.", "Documenta propietario y acceso; el asistente debe respetar los permisos originales.", "Prueba preguntas reales, documentos restringidos y casos incompletos antes de añadir más fuentes."] }),
  fr: makeTranslation("fr", { title: "Préparer les documents d’entreprise pour un assistant IA interne", description: "Guide pratique pour PME sur les documents, versions, responsables et droits d’accès avant un assistant IA interne.", category: "Mise en œuvre de l’IA", readingTime: "9 min de lecture", audience: "PME suisses et européennes préparant leurs connaissances internes", excerpt: "Des sources à jour, structurées et correctement autorisées comptent davantage que le volume de fichiers.", headings: ["Commencer par une question métier", "Choisir des sources faisant autorité", "Supprimer doublons et anciennes versions", "Améliorer structure et contexte", "Définir propriétaires et droits", "Tester la recherche avant d’élargir"], paragraphs: ["Définissez une tâche, une réponse correcte, les utilisateurs et le moment où une personne doit reprendre.", "Utilisez le plus petit ensemble de politiques, guides et bases approuvés.", "Identifiez la version valide, archivez les copies anciennes et résolvez les contradictions.", "Employez des titres clairs, des sections lisibles, des tableaux propres et des abréviations expliquées.", "Documentez le propriétaire et les accès; l’assistant doit respecter les droits du système source.", "Testez des questions réelles, des documents restreints et des informations manquantes avant d’ajouter des sources."] }),
  it: makeTranslation("it", { title: "Come preparare i documenti aziendali per un assistente AI interno", description: "Guida pratica per PMI su documenti, versioni, responsabili e permessi prima di introdurre un assistente AI interno.", category: "Implementazione AI", readingTime: "9 min di lettura", audience: "PMI svizzere ed europee che preparano la conoscenza interna", excerpt: "Fonti aggiornate, strutturate e con permessi chiari contano più del numero di file caricati.", headings: ["Partire da una domanda aziendale", "Scegliere fonti autorevoli", "Rimuovere duplicati e vecchie versioni", "Migliorare struttura e contesto", "Definire proprietari e permessi", "Testare il recupero prima di ampliare"], paragraphs: ["Definisci un compito, la risposta corretta, gli utenti e quando coinvolgere una persona.", "Usa il minimo insieme di policy, guide e basi di conoscenza approvate.", "Segna la versione valida, archivia le copie obsolete e risolvi le contraddizioni.", "Usa titoli chiari, sezioni leggibili, tabelle pulite e abbreviazioni spiegate.", "Documenta proprietario e accesso; l’assistente deve rispettare i permessi originali.", "Prova domande reali, documenti limitati e informazioni mancanti prima di aggiungere altre fonti."] }),
  cz: makeTranslation("cz", { title: "Jak připravit firemní dokumenty pro interního AI asistenta", description: "Praktický průvodce pro malé firmy: dokumenty, verze, vlastníci a oprávnění před zavedením interního AI asistenta.", category: "Implementace AI", readingTime: "9 min čtení", audience: "Švýcarské a evropské malé firmy připravující interní znalosti", excerpt: "Aktuální, strukturované a správně oprávněné zdroje jsou důležitější než množství souborů.", headings: ["Začněte jednou obchodní otázkou", "Vyberte autoritativní zdroje", "Odstraňte duplicity a staré verze", "Zlepšete strukturu a kontext", "Určete vlastníky a oprávnění", "Otestujte vyhledávání před rozšířením"], paragraphs: ["Definujte úkol, správnou odpověď, uživatele a okamžik předání člověku.", "Použijte nejmenší sadu schválených směrnic, návodů a znalostních bází.", "Označte platnou verzi, archivujte staré kopie a vyřešte rozpory.", "Používejte jasné názvy, nadpisy, čitelné tabulky a vysvětlené zkratky.", "Zdokumentujte vlastníka a přístup; asistent musí zachovat původní oprávnění.", "Testujte skutečné dotazy, omezené dokumenty a chybějící informace před přidáním dalších zdrojů."] }),
  sk: makeTranslation("sk", { title: "Ako pripraviť firemné dokumenty pre interného AI asistenta", description: "Praktický sprievodca pre malé firmy: dokumenty, verzie, vlastníci a oprávnenia pred nasadením interného AI asistenta.", category: "Implementácia AI", readingTime: "9 min čítania", audience: "Švajčiarske a európske malé firmy pripravujúce interné znalosti", excerpt: "Aktuálne, štruktúrované a správne oprávnené zdroje sú dôležitejšie než množstvo súborov.", headings: ["Začnite jednou obchodnou otázkou", "Vyberte autoritatívne zdroje", "Odstráňte duplicity a staré verzie", "Zlepšite štruktúru a kontext", "Určte vlastníkov a oprávnenia", "Otestujte vyhľadávanie pred rozšírením"], paragraphs: ["Definujte úlohu, správnu odpoveď, používateľov a moment odovzdania človeku.", "Použite najmenšiu sadu schválených smerníc, návodov a znalostných báz.", "Označte platnú verziu, archivujte staré kópie a vyriešte rozpory.", "Používajte jasné názvy, nadpisy, čitateľné tabuľky a vysvetlené skratky.", "Zdokumentujte vlastníka a prístup; asistent musí zachovať pôvodné oprávnenia.", "Testujte skutočné otázky, obmedzené dokumenty a chýbajúce informácie pred pridaním ďalších zdrojov."] }),
  pt: makeTranslation("pt", { title: "Como preparar documentos da empresa para um assistente interno de IA", description: "Guia prático para PME sobre documentos, versões, responsáveis e permissões antes de implementar um assistente interno de IA.", category: "Implementação de IA", readingTime: "9 min de leitura", audience: "PME suíças e europeias a preparar conhecimento interno", excerpt: "Fontes atuais, estruturadas e com permissões claras importam mais do que carregar todos os ficheiros.", headings: ["Começar com uma pergunta de negócio", "Escolher fontes autorizadas", "Remover duplicados e versões antigas", "Melhorar estrutura e contexto", "Definir responsáveis e permissões", "Testar a pesquisa antes de ampliar"], paragraphs: ["Defina uma tarefa, a resposta correta, os utilizadores e quando uma pessoa deve intervir.", "Use o menor conjunto de políticas, guias e bases de conhecimento aprovadas.", "Marque a versão válida, arquive cópias antigas e resolva contradições.", "Use títulos claros, secções legíveis, tabelas limpas e abreviaturas explicadas.", "Documente o responsável e o acesso; o assistente deve respeitar as permissões originais.", "Teste perguntas reais, documentos restritos e informação em falta antes de adicionar mais fontes."] }),
  da: makeTranslation("da", { title: "Sådan forbereder du virksomhedsdokumenter til en intern AI-assistent", description: "Praktisk guide til SMV’er om dokumenter, versioner, ejerskab og adgang før en intern AI-assistent.", category: "AI-implementering", readingTime: "9 min læsning", audience: "Schweiziske og europæiske SMV’er, der forbereder intern viden", excerpt: "Aktuelle, strukturerede og korrekt beskyttede kilder er vigtigere end antallet af filer.", headings: ["Start med ét forretningsspørgsmål", "Vælg autoritative kilder", "Fjern dubletter og gamle versioner", "Forbedr struktur og kontekst", "Fastlæg ejerskab og adgang", "Test søgningen før udvidelse"], paragraphs: ["Definér en opgave, det korrekte svar, brugerne og hvornår et menneske skal overtage.", "Brug det mindste sæt godkendte politikker, vejledninger og vidensbaser.", "Markér den gældende version, arkivér gamle kopier og løs modstridende indhold.", "Brug klare titler, overskrifter, læsbare tabeller og forklarede forkortelser.", "Dokumentér ejer og adgang; assistenten skal bevare kildesystemets rettigheder.", "Test rigtige spørgsmål, begrænsede dokumenter og manglende information før flere kilder tilføjes."] }),
  nl: makeTranslation("nl", { title: "Bedrijfsdocumenten voorbereiden voor een interne AI-assistent", description: "Praktische gids voor mkb-bedrijven over documenten, versies, eigenaarschap en toegangsrechten vóór een interne AI-assistent.", category: "AI-implementatie", readingTime: "9 min leestijd", audience: "Zwitserse en Europese mkb-bedrijven die interne kennis voorbereiden", excerpt: "Actuele, gestructureerde en correct afgeschermde bronnen zijn belangrijker dan het aantal bestanden.", headings: ["Begin met één bedrijfsvraag", "Kies gezaghebbende bronnen", "Verwijder duplicaten en oude versies", "Verbeter structuur en context", "Leg eigenaarschap en rechten vast", "Test de zoekfunctie vóór uitbreiding"], paragraphs: ["Definieer één taak, het juiste antwoord, de gebruikers en wanneer een mens moet overnemen.", "Gebruik de kleinste set goedgekeurde beleidsstukken, handleidingen en kennisbanken.", "Markeer de geldige versie, archiveer oude kopieën en los tegenstrijdigheden op.", "Gebruik duidelijke titels, koppen, leesbare tabellen en verklaarde afkortingen.", "Documenteer eigenaar en toegang; de assistent moet de oorspronkelijke rechten respecteren.", "Test echte vragen, afgeschermde documenten en ontbrekende informatie voordat meer bronnen worden toegevoegd."] }),
  ja: makeTranslation("ja", { title: "社内AIアシスタント向けに企業文書を準備する方法", description: "社内AIアシスタント導入前に、文書、版管理、責任者、アクセス権を整えるための中小企業向け実践ガイド。", category: "AI導入", readingTime: "9分で読めます", audience: "社内ナレッジを整備するスイスおよび欧州の中小企業", excerpt: "大量のファイルよりも、最新版、明確な構造、責任者、適切な権限が重要です。", headings: ["一つの業務質問から始める", "信頼できる情報源を選ぶ", "重複と古い版を除く", "構造と文脈を改善する", "責任者と権限を定義する", "拡張前に検索をテストする"], paragraphs: ["一つの業務、正しい回答の条件、利用者、人への引き継ぎ条件を定義します。", "承認済みの規程、手順書、ナレッジベースから必要最小限を選びます。", "有効版を明示し、古いコピーを除外し、矛盾を解消します。", "明確な題名、見出し、読みやすい表、説明済みの略語を使います。", "各情報源の責任者とアクセス権を記録し、元システムの権限を維持します。", "実際の質問、制限文書、情報不足を試し、安定してから情報源を増やします。"] }),
} satisfies Record<LocaleCode, BlogPostTranslation>;

export default {
  slug: "prepare-company-documents-internal-ai-assistant",
  published: true,
  status: "published",
  publishDate: "2026-08-04",
  image: "/assets/blog/prepare-company-documents-internal-ai-assistant.png",
  imageAlt: "Websiteli blog cover reading Prepare Documents for AI with organized company policies, document control, ownership, access permissions and an internal AI readiness dashboard.",
  author: "Websiteli",
  date: "2026-08-04",
  updated: "2026-08-04",
  related: ["internal-ai-assistant-small-business", "private-ai-assistant-privacy-checklist", "ai-chatbot-vs-internal-ai-assistant"],
  translations,
} satisfies BlogPostSource;
