import type { LocaleCode } from "../../locales";
import type { BlogPostSource, BlogPostTranslation } from "../types";

type Copy = {
  title: string;
  description: string;
  category: string;
  tags: string[];
  readingTime: string;
  audience: string;
  excerpt: string;
  summary: string[];
  takeaways: string[];
  prompts: string[];
  headings: [string, string, string, string, string, string, string];
  paragraphs: [string, string, string, string, string, string, string];
  faqs: { question: string; answer: string }[];
};

function makeTranslation(language: LocaleCode, copy: Copy): BlogPostTranslation {
  const body = copy.headings
    .map((heading, index) => `## ${heading}\n\n${copy.paragraphs[index]}`)
    .join("\n\n");

  return {
    title: copy.title,
    description: copy.description,
    category: copy.category,
    tags: copy.tags,
    language,
    readingTime: copy.readingTime,
    audience: copy.audience,
    excerpt: copy.excerpt,
    summary: copy.summary,
    keyTakeaways: copy.takeaways,
    chatGptPrompts: copy.prompts,
    faqs: copy.faqs,
    body: `${body}\n\n[Internal AI assistants](/en/services/ai-assistants/) · [AI integrations](/en/services/ai-integrations/) · [Business automation](/en/services/business-automation/) · [Services and pricing](/en/services-pricing/) · [Contact](/en/contact/)`,
  };
}

const translations = {
  en: makeTranslation("en", {
    title: "Private AI Assistant Privacy Checklist for Swiss and European SMEs",
    description: "A practical privacy, permissions and governance checklist for small businesses planning an internal AI assistant that works with company documents.",
    category: "AI Governance",
    tags: ["private AI assistant", "AI privacy checklist", "internal AI assistant security", "AI permissions for SMEs"],
    readingTime: "10 min read",
    audience: "Swiss and European SME owners and operations teams planning a private internal AI assistant",
    excerpt: "Before connecting company documents to an AI assistant, define data boundaries, access rights, retention, logging, human escalation and ownership.",
    summary: [
      "A private AI assistant should only access approved sources needed for a defined business task.",
      "The assistant must preserve the access rights of the original systems instead of creating a new route around them.",
      "Privacy controls include data minimisation, retention rules, logging, deletion procedures and supplier review.",
      "Human escalation and named ownership are necessary when answers are uncertain or sensitive.",
    ],
    takeaways: [
      "Start with one low-risk source collection and one measurable workflow.",
      "Separate retrieval, drafting and action-taking permissions.",
      "Test the system with different roles and deliberately restricted documents.",
      "Document who maintains sources, reviews incidents and approves changes.",
    ],
    prompts: [
      "Create a data inventory for an internal AI assistant used by my small business.",
      "Turn this article into a role-based access and privacy test plan.",
      "Help me define retention, deletion and human-escalation rules for a private AI assistant.",
    ],
    headings: [
      "Define the purpose before connecting data",
      "Minimise the information the assistant can access",
      "Preserve permissions from the source systems",
      "Decide what is stored, logged and deleted",
      "Review suppliers, hosting and integrations",
      "Test sensitive cases and human escalation",
      "Use a practical launch checklist",
    ],
    paragraphs: [
      "Write down the exact task, users, approved sources and expected output before selecting technology. A narrow assistant that finds an approved procedure is easier to govern than a general assistant connected to every drive, mailbox and business system. Do not collect data merely because it may become useful later.",
      "Use the smallest source set that can solve the task. Exclude personal, contractual, financial or confidential material unless it is genuinely required and protected by an appropriate process. Prefer approved folders, curated knowledge bases and explicit source owners over unrestricted access to shared storage.",
      "A user should never receive information through the assistant that they could not open in the original system. Identity checks, role-based access, document-level filtering and permission-aware retrieval should happen before content reaches the model. Drafting permission should also remain separate from permission to send messages, change records or publish content.",
      "Decide whether prompts, retrieved passages, answers and feedback are stored. Define retention periods, incident logs, deletion procedures and who can inspect usage records. Avoid keeping full sensitive conversations by default. When an employee leaves or a document becomes obsolete, access and indexed copies need a clear removal path.",
      "Document where data is processed, which subprocessors or external services are involved, what integrations can read or write, and how credentials are protected. Review contractual and technical controls with qualified privacy or legal advisers where necessary; this article is an operational checklist, not legal advice.",
      "Test with real questions, misleading wording, missing context and documents that different users should not see. The assistant should say when evidence is insufficient, show sources for important answers and transfer sensitive or uncertain cases to a person. Record failures and update either the source material, retrieval rules or workflow.",
      "Before launch, confirm: one defined use case; approved source owners; role-based access; no unrestricted action permissions; retention and deletion rules; logs for failures and access events; a named incident owner; human escalation; documented supplier responsibilities; and a recurring review date. Expand only after the first scope is reliable.",
    ],
    faqs: [
      { question: "Can a private AI assistant read every company document?", answer: "It should not. Limit access to the smallest approved source set needed for the defined task and preserve existing permissions." },
      { question: "Should prompts and answers be stored?", answer: "Only when there is a clear operational reason, a defined retention period and appropriate access controls. Sensitive conversations should not be retained by default." },
      { question: "Does a private AI assistant need human review?", answer: "Yes for uncertain, sensitive or consequential cases. The workflow should define when the assistant must stop and hand the task to a person." },
      { question: "Is this checklist legal advice?", answer: "No. It is an operational planning checklist. Businesses should obtain qualified advice for their specific legal, contractual and regulatory obligations." },
    ],
  }),
  de: makeTranslation("de", {
    title: "Datenschutz-Checkliste für private KI-Assistenten in Schweizer und europäischen KMU",
    description: "Praxisnahe Checkliste zu Datenschutz, Berechtigungen und Governance für KMU, die einen internen KI-Assistenten mit Unternehmensdokumenten planen.",
    category: "KI-Governance",
    tags: ["privater KI-Assistent", "KI Datenschutz Checkliste", "interner KI-Assistent Sicherheit", "KI Berechtigungen KMU"],
    readingTime: "11 Min. Lesezeit",
    audience: "Schweizer und europäische KMU, die einen privaten internen KI-Assistenten planen",
    excerpt: "Vor der Anbindung von Unternehmensdokumenten müssen Datenumfang, Zugriffsrechte, Aufbewahrung, Protokollierung, Eskalation und Verantwortung geklärt sein.",
    summary: [
      "Ein privater KI-Assistent darf nur freigegebene Quellen verwenden, die für eine klar definierte Aufgabe nötig sind.",
      "Die Berechtigungen der Ursprungssysteme müssen erhalten bleiben und dürfen nicht umgangen werden.",
      "Datenschutz umfasst Datenminimierung, Aufbewahrung, Protokollierung, Löschung und die Prüfung externer Anbieter.",
      "Unsichere oder sensible Fälle brauchen einen menschlichen Eskalationsweg und eine klar benannte Verantwortung.",
    ],
    takeaways: [
      "Mit einer risikoarmen Quellensammlung und einem messbaren Workflow beginnen.",
      "Recherche-, Entwurfs- und Aktionsrechte voneinander trennen.",
      "Mit verschiedenen Rollen und bewusst gesperrten Dokumenten testen.",
      "Verantwortung für Quellen, Vorfälle und Änderungen dokumentieren.",
    ],
    prompts: [
      "Erstelle ein Dateninventar für einen internen KI-Assistenten in meinem KMU.",
      "Erstelle aus diesem Artikel einen rollenbasierten Datenschutz- und Zugriffstest.",
      "Hilf mir, Aufbewahrungs-, Lösch- und Eskalationsregeln für einen privaten KI-Assistenten festzulegen.",
    ],
    headings: [
      "Zweck definieren, bevor Daten angebunden werden",
      "Den Datenzugriff konsequent minimieren",
      "Berechtigungen der Ursprungssysteme erhalten",
      "Speicherung, Protokollierung und Löschung regeln",
      "Anbieter, Hosting und Integrationen prüfen",
      "Sensible Fälle und Eskalationen testen",
      "Mit einer praktischen Freigabe-Checkliste starten",
    ],
    paragraphs: [
      "Definieren Sie Aufgabe, Nutzerkreis, freigegebene Quellen und erwartetes Ergebnis, bevor Sie Technologie auswählen. Ein Assistent, der eine gültige Prozessbeschreibung findet, ist leichter kontrollierbar als ein allgemeines System mit Zugriff auf Laufwerke, E-Mails und mehrere Geschäftsanwendungen.",
      "Verwenden Sie nur die kleinste Quellensammlung, die den Anwendungsfall abdeckt. Personenbezogene, vertragliche, finanzielle oder vertrauliche Daten gehören nur dann in den Prozess, wenn sie wirklich benötigt und angemessen geschützt werden. Freigegebene Ordner und klar verantwortete Wissensbestände sind besser als unbeschränkter Zugriff.",
      "Mitarbeitende dürfen über den Assistenten keine Informationen erhalten, die sie im Ursprungssystem nicht öffnen könnten. Identitätsprüfung, rollenbasierter Zugriff, Dokumentfilter und berechtigungsabhängige Suche müssen vor der Übergabe an das Sprachmodell greifen. Recherche, Entwurf, Versand und Änderungen sollten getrennte Rechte besitzen.",
      "Legen Sie fest, ob Eingaben, gefundene Textstellen, Antworten und Feedback gespeichert werden. Definieren Sie Aufbewahrungsfristen, Ereignisprotokolle, Löschwege und Zugriffsrechte auf Logs. Sensible Gespräche sollten nicht standardmässig vollständig gespeichert werden. Auch für austretende Mitarbeitende und veraltete Dokumente braucht es einen Entfernungsprozess.",
      "Dokumentieren Sie Verarbeitungsort, externe Dienste, Unterauftragnehmer, Integrationsrechte und den Schutz von Zugangsdaten. Wo nötig, sollten qualifizierte Datenschutz- oder Rechtsfachpersonen die vertraglichen und technischen Kontrollen prüfen. Dieser Artikel ist eine betriebliche Checkliste und keine Rechtsberatung.",
      "Testen Sie reale Fragen, irreführende Formulierungen, fehlenden Kontext und Dokumente, die einzelne Rollen nicht sehen dürfen. Bei unzureichenden Quellen soll der Assistent dies sagen, wichtige Antworten belegen und sensible Fälle an Menschen übergeben. Fehler müssen dokumentiert und durch bessere Quellen, Regeln oder Abläufe behoben werden.",
      "Vor dem Start sollten ein klarer Anwendungsfall, verantwortete Quellen, rollenbasierte Rechte, getrennte Aktionsrechte, Aufbewahrungs- und Löschregeln, Fehler- und Zugriffslogs, eine verantwortliche Person für Vorfälle, menschliche Eskalation, dokumentierte Anbieterpflichten und ein regelmässiger Prüftermin vorhanden sein.",
    ],
    faqs: [
      { question: "Darf ein privater KI-Assistent alle Unternehmensdokumente lesen?", answer: "Nein. Der Zugriff sollte auf die kleinste freigegebene Quellensammlung begrenzt sein und bestehende Rechte respektieren." },
      { question: "Sollten Eingaben und Antworten gespeichert werden?", answer: "Nur mit einem klaren Zweck, einer definierten Frist und angemessenen Zugriffskontrollen. Sensible Gespräche sollten nicht standardmässig gespeichert werden." },
      { question: "Braucht ein interner KI-Assistent menschliche Prüfung?", answer: "Ja, insbesondere bei sensiblen, unsicheren oder folgenreichen Fällen. Der Eskalationsweg muss im Workflow festgelegt sein." },
      { question: "Ist diese Checkliste Rechtsberatung?", answer: "Nein. Sie dient der betrieblichen Planung. Konkrete rechtliche und regulatorische Pflichten sollten qualifiziert geprüft werden." },
    ],
  }),
  hu: makeTranslation("hu", { title: "Adatvédelmi ellenőrzőlista privát AI-asszisztensekhez kisvállalkozásoknak", description: "Gyakorlati adatvédelmi, jogosultsági és irányítási ellenőrzőlista belső AI-asszisztenst tervező vállalkozásoknak.", category: "AI-irányítás", tags: ["privát AI-asszisztens", "AI adatvédelem", "belső AI biztonság", "jogosultságkezelés"], readingTime: "9 perc olvasás", audience: "Svájci és európai kisvállalkozások", excerpt: "Az AI-asszisztens előtt határozza meg a forrásokat, jogosultságokat, naplózást, megőrzést, törlést és emberi eszkalációt.", summary: ["Csak jóváhagyott és szükséges forrásokat kapcsoljon az asszisztenshez.", "Őrizze meg az eredeti rendszerek jogosultságait.", "Szabályozza a megőrzést, naplózást és törlést.", "Bizonytalan esetben legyen emberi átadás."], takeaways: ["Kezdjen egy szűk feladattal.", "Válassza szét a keresési és műveleti jogokat.", "Teszteljen tiltott dokumentumokkal is.", "Nevezzen ki felelőst."], prompts: ["Készíts adatleltárt a belső AI-asszisztensemhez.", "Készíts jogosultsági teszttervet.", "Határozz meg megőrzési és törlési szabályokat."], headings: ["A cél meghatározása", "Adatminimalizálás", "Jogosultságok megőrzése", "Naplózás és törlés", "Szállítók és hosting", "Tesztelés és eszkaláció", "Indítási ellenőrzőlista"], paragraphs: ["Pontosan írja le a feladatot, a felhasználókat, a forrásokat és az elvárt eredményt.", "Csak a szükséges jóváhagyott dokumentumokat használja, és kerülje a fölösleges személyes vagy bizalmas adatot.", "A felhasználó ne lásson olyan információt, amelyet az eredeti rendszerben sem érhet el.", "Döntse el, mi kerül tárolásra, meddig marad meg, ki láthatja a naplókat, és hogyan törölhető.", "Dokumentálja, hol történik a feldolgozás, milyen külső szolgáltatók és integrációk férnek hozzá az adatokhoz.", "Teszteljen valós, félrevezető és jogosultságot sértő kérdésekkel; bizonytalanság esetén legyen emberi átadás.", "Indítás előtt ellenőrizze a célt, forrásgazdákat, szerepköröket, törlési szabályokat, naplókat, incidensfelelőst és felülvizsgálati dátumot."], faqs: [{ question: "Olvashat minden dokumentumot az asszisztens?", answer: "Nem. Csak a feladathoz szükséges jóváhagyott forrásokat érje el." }, { question: "Tároljuk a beszélgetéseket?", answer: "Csak világos cél, megőrzési idő és megfelelő hozzáférés mellett." }, { question: "Kell emberi ellenőrzés?", answer: "Igen, érzékeny vagy bizonytalan eseteknél." }] }),
  pl: makeTranslation("pl", { title: "Lista prywatności dla prywatnego asystenta AI w małej firmie", description: "Praktyczna lista kontroli prywatności, uprawnień i zarządzania dla firm planujących wewnętrznego asystenta AI.", category: "Zarządzanie AI", tags: ["prywatny asystent AI", "prywatność AI", "bezpieczeństwo asystenta AI", "uprawnienia AI"], readingTime: "9 min czytania", audience: "Małe firmy w Szwajcarii i Europie", excerpt: "Przed połączeniem dokumentów określ źródła, prawa dostępu, retencję, logi, usuwanie i eskalację do człowieka.", summary: ["Podłączaj tylko zatwierdzone źródła.", "Zachowaj uprawnienia systemów źródłowych.", "Ustal retencję, logowanie i usuwanie.", "Zapewnij eskalację do człowieka."], takeaways: ["Zacznij od jednego zadania.", "Oddziel wyszukiwanie od działania.", "Testuj z zablokowanymi dokumentami.", "Wyznacz właściciela procesu."], prompts: ["Utwórz inwentaryzację danych dla asystenta AI.", "Przygotuj test uprawnień według ról.", "Zdefiniuj retencję i usuwanie."], headings: ["Najpierw określ cel", "Minimalizuj dane", "Zachowaj uprawnienia", "Ustal logi i usuwanie", "Sprawdź dostawców", "Testuj i eskaluj", "Lista przed uruchomieniem"], paragraphs: ["Opisz dokładne zadanie, użytkowników, zatwierdzone źródła i oczekiwany wynik.", "Używaj najmniejszego niezbędnego zestawu danych i unikaj zbędnych danych osobowych lub poufnych.", "Użytkownik nie może otrzymać informacji, których nie widzi w systemie źródłowym.", "Określ, co jest zapisywane, jak długo, kto widzi logi i jak dane są usuwane.", "Dokumentuj miejsce przetwarzania, usługi zewnętrzne, integracje i ochronę poświadczeń.", "Testuj prawdziwe pytania, brak kontekstu i dokumenty niedostępne dla części ról; niepewne sprawy przekazuj człowiekowi.", "Przed startem sprawdź zakres, właścicieli źródeł, role, retencję, logi, odpowiedzialność za incydenty i termin przeglądu."], faqs: [{ question: "Czy asystent może czytać wszystkie dokumenty?", answer: "Nie. Tylko zatwierdzone źródła potrzebne do zadania." }, { question: "Czy przechowywać rozmowy?", answer: "Tylko z jasnym celem, okresem retencji i kontrolą dostępu." }, { question: "Czy potrzebna jest kontrola człowieka?", answer: "Tak w sprawach wrażliwych i niepewnych." }] }),
  es: makeTranslation("es", { title: "Checklist de privacidad para un asistente de IA privado en una pyme", description: "Lista práctica de privacidad, permisos y gobernanza para empresas que planean un asistente interno de IA.", category: "Gobernanza de IA", tags: ["asistente de IA privado", "privacidad de IA", "seguridad de asistente interno", "permisos de IA"], readingTime: "9 min de lectura", audience: "Pymes suizas y europeas", excerpt: "Antes de conectar documentos, define fuentes, accesos, retención, registros, eliminación y escalado humano.", summary: ["Conecta solo fuentes aprobadas.", "Mantén los permisos originales.", "Define retención, registros y eliminación.", "Escala los casos inciertos a una persona."], takeaways: ["Empieza con una tarea limitada.", "Separa consulta y acciones.", "Prueba documentos restringidos.", "Asigna un responsable."], prompts: ["Crea un inventario de datos para mi asistente.", "Prepara un test de permisos por roles.", "Define reglas de retención y borrado."], headings: ["Define el propósito", "Minimiza los datos", "Conserva los permisos", "Registros y eliminación", "Proveedores y alojamiento", "Pruebas y escalado", "Checklist de lanzamiento"], paragraphs: ["Describe la tarea, usuarios, fuentes aprobadas y resultado esperado antes de elegir tecnología.", "Usa el conjunto mínimo de información y evita datos personales o confidenciales innecesarios.", "Nadie debe recibir mediante el asistente información que no pueda abrir en el sistema original.", "Decide qué se guarda, durante cuánto tiempo, quién ve los registros y cómo se elimina.", "Documenta dónde se procesan los datos, qué proveedores e integraciones intervienen y cómo se protegen las credenciales.", "Prueba preguntas reales, contexto incompleto y documentos restringidos; los casos inciertos deben pasar a una persona.", "Antes del lanzamiento confirma el alcance, propietarios de fuentes, roles, retención, registros, responsable de incidentes y fecha de revisión."], faqs: [{ question: "¿Puede leer todos los documentos?", answer: "No. Solo fuentes aprobadas necesarias para la tarea." }, { question: "¿Deben guardarse las conversaciones?", answer: "Solo con un motivo claro, plazo definido y acceso controlado." }, { question: "¿Hace falta revisión humana?", answer: "Sí para casos sensibles o inciertos." }] }),
  fr: makeTranslation("fr", { title: "Checklist de confidentialité pour un assistant IA privé en PME", description: "Checklist pratique de confidentialité, droits d'accès et gouvernance pour les PME qui préparent un assistant IA interne.", category: "Gouvernance IA", tags: ["assistant IA privé", "confidentialité IA", "sécurité assistant interne", "droits d'accès IA"], readingTime: "9 min de lecture", audience: "PME suisses et européennes", excerpt: "Avant de connecter les documents, définissez sources, droits, conservation, journaux, suppression et escalade humaine.", summary: ["Connectez uniquement des sources validées.", "Préservez les droits des systèmes d'origine.", "Définissez conservation, journaux et suppression.", "Transférez les cas incertains à une personne."], takeaways: ["Commencez par une tâche limitée.", "Séparez recherche et actions.", "Testez avec des documents interdits.", "Nommez un responsable."], prompts: ["Crée un inventaire de données pour mon assistant.", "Prépare un test des droits par rôle.", "Définis les règles de conservation et suppression."], headings: ["Définir le but", "Minimiser les données", "Préserver les droits", "Journaux et suppression", "Fournisseurs et hébergement", "Tests et escalade", "Checklist avant lancement"], paragraphs: ["Décrivez la tâche, les utilisateurs, les sources validées et le résultat attendu avant de choisir la technologie.", "Utilisez le plus petit ensemble d'informations nécessaire et évitez les données personnelles ou confidentielles inutiles.", "Un utilisateur ne doit jamais recevoir une information inaccessible dans le système d'origine.", "Décidez ce qui est conservé, pendant combien de temps, qui consulte les journaux et comment les données sont supprimées.", "Documentez le lieu de traitement, les fournisseurs, les intégrations et la protection des identifiants.", "Testez des questions réelles, un contexte incomplet et des documents restreints; transmettez les cas incertains à une personne.", "Avant le lancement, vérifiez le périmètre, les propriétaires des sources, les rôles, la conservation, les journaux, le responsable d'incident et la date de révision."], faqs: [{ question: "L'assistant peut-il lire tous les documents ?", answer: "Non. Seulement les sources validées nécessaires à la tâche." }, { question: "Faut-il conserver les conversations ?", answer: "Uniquement avec un objectif clair, une durée définie et des accès contrôlés." }, { question: "Une révision humaine est-elle nécessaire ?", answer: "Oui pour les cas sensibles ou incertains." }] }),
  it: makeTranslation("it", { title: "Checklist privacy per un assistente AI privato in una PMI", description: "Checklist pratica su privacy, permessi e governance per aziende che progettano un assistente AI interno.", category: "Governance AI", tags: ["assistente AI privato", "privacy AI", "sicurezza assistente interno", "permessi AI"], readingTime: "9 min di lettura", audience: "PMI svizzere ed europee", excerpt: "Prima di collegare i documenti definisci fonti, accessi, conservazione, log, cancellazione ed escalation umana.", summary: ["Collega solo fonti approvate.", "Mantieni i permessi originali.", "Definisci conservazione, log e cancellazione.", "Passa i casi incerti a una persona."], takeaways: ["Inizia con un compito limitato.", "Separa ricerca e azioni.", "Testa documenti riservati.", "Assegna un responsabile."], prompts: ["Crea un inventario dati per il mio assistente.", "Prepara un test dei permessi per ruolo.", "Definisci conservazione e cancellazione."], headings: ["Definire lo scopo", "Minimizzare i dati", "Preservare i permessi", "Log e cancellazione", "Fornitori e hosting", "Test ed escalation", "Checklist di lancio"], paragraphs: ["Descrivi attività, utenti, fonti approvate e risultato atteso prima di scegliere la tecnologia.", "Usa il minimo insieme di informazioni necessario ed evita dati personali o riservati non indispensabili.", "Nessun utente deve ricevere informazioni che non potrebbe aprire nel sistema originale.", "Decidi cosa viene salvato, per quanto tempo, chi vede i log e come avviene la cancellazione.", "Documenta luogo di trattamento, fornitori, integrazioni e protezione delle credenziali.", "Testa domande reali, contesto mancante e documenti riservati; i casi incerti devono passare a una persona.", "Prima del lancio verifica ambito, proprietari delle fonti, ruoli, conservazione, log, responsabile incidenti e data di revisione."], faqs: [{ question: "Può leggere tutti i documenti?", answer: "No. Solo le fonti approvate necessarie all'attività." }, { question: "Le conversazioni vanno salvate?", answer: "Solo con uno scopo chiaro, una durata definita e accessi controllati." }, { question: "Serve una revisione umana?", answer: "Sì per casi sensibili o incerti." }] }),
  cz: makeTranslation("cz", { title: "Kontrolní seznam soukromí pro interního AI asistenta v malé firmě", description: "Praktický seznam pro soukromí, oprávnění a správu interního AI asistenta.", category: "AI governance", tags: ["soukromý AI asistent", "AI soukromí", "bezpečnost interního asistenta", "AI oprávnění"], readingTime: "9 min čtení", audience: "Švýcarské a evropské malé firmy", excerpt: "Před připojením dokumentů určete zdroje, přístupy, uchování, logy, mazání a lidskou eskalaci.", summary: ["Připojujte jen schválené zdroje.", "Zachovejte původní oprávnění.", "Určete uchování, logy a mazání.", "Nejisté případy předejte člověku."], takeaways: ["Začněte jedním úkolem.", "Oddělte vyhledávání a akce.", "Testujte zakázané dokumenty.", "Určete vlastníka."], prompts: ["Vytvoř inventář dat pro asistenta.", "Připrav test oprávnění podle rolí.", "Definuj pravidla uchování a mazání."], headings: ["Určete účel", "Minimalizujte data", "Zachovejte oprávnění", "Logy a mazání", "Dodavatelé a hosting", "Testy a eskalace", "Seznam před spuštěním"], paragraphs: ["Popište úkol, uživatele, schválené zdroje a očekávaný výsledek.", "Použijte nejmenší potřebný soubor informací a vyhněte se zbytečným osobním či důvěrným údajům.", "Uživatel nesmí získat informace, které v původním systému nevidí.", "Rozhodněte, co se ukládá, na jak dlouho, kdo vidí logy a jak probíhá mazání.", "Dokumentujte místo zpracování, dodavatele, integrace a ochranu přístupových údajů.", "Testujte reálné otázky, chybějící kontext a omezené dokumenty; nejisté případy předejte člověku.", "Před spuštěním ověřte rozsah, vlastníky zdrojů, role, uchování, logy, odpovědnost za incidenty a datum kontroly."], faqs: [{ question: "Může asistent číst všechny dokumenty?", answer: "Ne. Jen schválené zdroje potřebné pro úkol." }, { question: "Mají se ukládat konverzace?", answer: "Pouze s jasným účelem, lhůtou a kontrolou přístupu." }, { question: "Je nutná lidská kontrola?", answer: "Ano u citlivých nebo nejistých případů." }] }),
  sk: makeTranslation("sk", { title: "Kontrolný zoznam súkromia pre interného AI asistenta v malej firme", description: "Praktický zoznam pre súkromie, oprávnenia a správu interného AI asistenta.", category: "AI governance", tags: ["súkromný AI asistent", "AI súkromie", "bezpečnosť interného asistenta", "AI oprávnenia"], readingTime: "9 min čítania", audience: "Švajčiarske a európske malé firmy", excerpt: "Pred pripojením dokumentov určite zdroje, prístupy, uchovanie, logy, mazanie a ľudskú eskaláciu.", summary: ["Pripájajte iba schválené zdroje.", "Zachovajte pôvodné oprávnenia.", "Určite uchovanie, logy a mazanie.", "Neisté prípady odovzdajte človeku."], takeaways: ["Začnite jednou úlohou.", "Oddeľte vyhľadávanie a akcie.", "Testujte zakázané dokumenty.", "Určite vlastníka."], prompts: ["Vytvor inventár dát pre asistenta.", "Priprav test oprávnení podľa rolí.", "Definuj pravidlá uchovania a mazania."], headings: ["Určite účel", "Minimalizujte dáta", "Zachovajte oprávnenia", "Logy a mazanie", "Dodávatelia a hosting", "Testy a eskalácia", "Zoznam pred spustením"], paragraphs: ["Popíšte úlohu, používateľov, schválené zdroje a očakávaný výsledok.", "Použite najmenší potrebný súbor informácií a vyhnite sa zbytočným osobným či dôverným údajom.", "Používateľ nesmie získať informácie, ktoré v pôvodnom systéme nevidí.", "Rozhodnite, čo sa ukladá, na ako dlho, kto vidí logy a ako prebieha mazanie.", "Dokumentujte miesto spracovania, dodávateľov, integrácie a ochranu prístupových údajov.", "Testujte reálne otázky, chýbajúci kontext a obmedzené dokumenty; neisté prípady odovzdajte človeku.", "Pred spustením overte rozsah, vlastníkov zdrojov, roly, uchovanie, logy, zodpovednosť za incidenty a dátum kontroly."], faqs: [{ question: "Môže asistent čítať všetky dokumenty?", answer: "Nie. Iba schválené zdroje potrebné pre úlohu." }, { question: "Majú sa ukladať konverzácie?", answer: "Iba s jasným účelom, lehotou a kontrolou prístupu." }, { question: "Je nutná ľudská kontrola?", answer: "Áno pri citlivých alebo neistých prípadoch." }] }),
  pt: makeTranslation("pt", { title: "Checklist de privacidade para um assistente interno de IA numa pequena empresa", description: "Checklist prática de privacidade, permissões e governação para empresas que planeiam um assistente interno de IA.", category: "Governação de IA", tags: ["assistente privado de IA", "privacidade de IA", "segurança de assistente interno", "permissões de IA"], readingTime: "9 min de leitura", audience: "Pequenas empresas suíças e europeias", excerpt: "Antes de ligar documentos, define fontes, acessos, retenção, registos, eliminação e encaminhamento humano.", summary: ["Liga apenas fontes aprovadas.", "Mantém as permissões originais.", "Define retenção, registos e eliminação.", "Encaminha casos incertos para uma pessoa."], takeaways: ["Começa com uma tarefa limitada.", "Separa pesquisa e ações.", "Testa documentos restritos.", "Nomeia um responsável."], prompts: ["Cria um inventário de dados para o assistente.", "Prepara um teste de permissões por função.", "Define retenção e eliminação."], headings: ["Definir o objetivo", "Minimizar os dados", "Preservar permissões", "Registos e eliminação", "Fornecedores e alojamento", "Testes e encaminhamento", "Checklist de lançamento"], paragraphs: ["Descreve a tarefa, utilizadores, fontes aprovadas e resultado esperado antes de escolher tecnologia.", "Usa o menor conjunto necessário e evita dados pessoais ou confidenciais desnecessários.", "Ninguém deve receber informação que não consiga abrir no sistema original.", "Decide o que é guardado, por quanto tempo, quem vê os registos e como se elimina.", "Documenta onde os dados são processados, fornecedores, integrações e proteção das credenciais.", "Testa perguntas reais, contexto em falta e documentos restritos; casos incertos devem passar para uma pessoa.", "Antes do lançamento confirma âmbito, responsáveis pelas fontes, funções, retenção, registos, responsável por incidentes e data de revisão."], faqs: [{ question: "Pode ler todos os documentos?", answer: "Não. Apenas fontes aprovadas necessárias para a tarefa." }, { question: "As conversas devem ser guardadas?", answer: "Só com objetivo claro, prazo definido e acessos controlados." }, { question: "É necessária revisão humana?", answer: "Sim para casos sensíveis ou incertos." }] }),
  da: makeTranslation("da", { title: "Tjekliste for privatliv ved en intern AI-assistent i en mindre virksomhed", description: "Praktisk tjekliste for privatliv, adgang og styring ved planlægning af en intern AI-assistent.", category: "AI-governance", tags: ["privat AI-assistent", "AI-privatliv", "intern AI-sikkerhed", "AI-adgang"], readingTime: "9 min. læsning", audience: "Schweiziske og europæiske små virksomheder", excerpt: "Før dokumenter tilsluttes, skal kilder, adgang, opbevaring, logs, sletning og menneskelig eskalering defineres.", summary: ["Tilslut kun godkendte kilder.", "Bevar oprindelige adgangsrettigheder.", "Definér opbevaring, logs og sletning.", "Send usikre sager til et menneske."], takeaways: ["Start med én opgave.", "Adskil søgning og handling.", "Test begrænsede dokumenter.", "Udpeg en ansvarlig."], prompts: ["Lav et datakatalog til assistenten.", "Lav en rollebasseret adgangstest.", "Definér opbevaring og sletning."], headings: ["Definér formålet", "Minimér data", "Bevar adgang", "Logs og sletning", "Leverandører og hosting", "Test og eskalering", "Tjekliste før lancering"], paragraphs: ["Beskriv opgaven, brugerne, de godkendte kilder og det forventede resultat.", "Brug den mindst mulige mængde information og undgå unødvendige personlige eller fortrolige data.", "En bruger må ikke få information, som vedkommende ikke kan åbne i det oprindelige system.", "Beslut hvad der gemmes, hvor længe, hvem der ser logs, og hvordan data slettes.", "Dokumentér behandlingssted, leverandører, integrationer og beskyttelse af legitimationsoplysninger.", "Test virkelige spørgsmål, manglende kontekst og begrænsede dokumenter; usikre sager skal til et menneske.", "Før lancering kontrolleres omfang, kildeejere, roller, opbevaring, logs, incidentansvar og revisionsdato."], faqs: [{ question: "Kan assistenten læse alle dokumenter?", answer: "Nej. Kun godkendte kilder, der er nødvendige for opgaven." }, { question: "Skal samtaler gemmes?", answer: "Kun med tydeligt formål, fast frist og kontrolleret adgang." }, { question: "Er menneskelig kontrol nødvendig?", answer: "Ja ved følsomme eller usikre sager." }] }),
  nl: makeTranslation("nl", { title: "Privacychecklist voor een interne AI-assistent bij een klein bedrijf", description: "Praktische checklist voor privacy, rechten en governance bij het plannen van een interne AI-assistent.", category: "AI-governance", tags: ["private AI-assistent", "AI-privacy", "interne AI-beveiliging", "AI-rechten"], readingTime: "9 min. leestijd", audience: "Zwitserse en Europese kleine bedrijven", excerpt: "Definieer vóór aansluiting van documenten de bronnen, rechten, bewaartermijnen, logs, verwijdering en menselijke escalatie.", summary: ["Sluit alleen goedgekeurde bronnen aan.", "Behoud oorspronkelijke rechten.", "Definieer bewaring, logs en verwijdering.", "Stuur onzekere gevallen naar een mens."], takeaways: ["Begin met één taak.", "Scheid zoeken en handelen.", "Test beperkte documenten.", "Wijs een eigenaar aan."], prompts: ["Maak een data-inventaris voor de assistent.", "Maak een rolgebaseerde toegangstest.", "Definieer bewaring en verwijdering."], headings: ["Bepaal het doel", "Minimaliseer gegevens", "Behoud rechten", "Logs en verwijdering", "Leveranciers en hosting", "Testen en escalatie", "Checklist voor lancering"], paragraphs: ["Beschrijf de taak, gebruikers, goedgekeurde bronnen en het verwachte resultaat.", "Gebruik de kleinste noodzakelijke dataset en vermijd onnodige persoonlijke of vertrouwelijke gegevens.", "Een gebruiker mag geen informatie krijgen die niet toegankelijk is in het bronsysteem.", "Bepaal wat wordt bewaard, hoe lang, wie logs ziet en hoe gegevens worden verwijderd.", "Documenteer verwerkingslocatie, leveranciers, integraties en bescherming van inloggegevens.", "Test echte vragen, ontbrekende context en beperkte documenten; onzekere gevallen gaan naar een mens.", "Controleer vóór lancering het bereik, broneigenaren, rollen, bewaring, logs, incidentverantwoordelijke en evaluatiedatum."], faqs: [{ question: "Kan de assistent alle documenten lezen?", answer: "Nee. Alleen goedgekeurde bronnen die nodig zijn voor de taak." }, { question: "Moeten gesprekken worden bewaard?", answer: "Alleen met duidelijk doel, vaste termijn en gecontroleerde toegang." }, { question: "Is menselijke controle nodig?", answer: "Ja bij gevoelige of onzekere gevallen." }] }),
  ja: makeTranslation("ja", { title: "中小企業向け社内AIアシスタントのプライバシーチェックリスト", description: "社内AIアシスタントを計画する企業向けに、データ、権限、保存、ログ、削除、運用責任を確認します。", category: "AIガバナンス", tags: ["社内AIアシスタント", "AIプライバシー", "AIセキュリティ", "アクセス権限"], readingTime: "9分で読めます", audience: "スイスおよび欧州の中小企業", excerpt: "文書を接続する前に、利用目的、情報源、権限、保存期間、ログ、削除、人への引き継ぎを決めます。", summary: ["承認済みの必要な情報源だけを接続します。", "元のシステムの権限を維持します。", "保存、ログ、削除のルールを決めます。", "不確実な案件は人に引き継ぎます。"], takeaways: ["一つの業務から始めます。", "検索と操作権限を分けます。", "閲覧禁止文書でもテストします。", "責任者を決めます。"], prompts: ["社内AI用のデータ一覧を作成してください。", "役割別の権限テストを作成してください。", "保存と削除のルールを作成してください。"], headings: ["目的を定義する", "データを最小化する", "元の権限を維持する", "ログと削除を決める", "提供者とホスティングを確認する", "テストと人への引き継ぎ", "公開前チェックリスト"], paragraphs: ["技術を選ぶ前に、対象業務、利用者、承認済み情報源、期待する結果を明確にします。", "必要最小限の情報だけを使い、不要な個人情報や機密情報を含めません。", "利用者が元のシステムで見られない情報を、AI経由で受け取ってはいけません。", "何を保存するか、期間、ログ閲覧者、削除手順を決めます。", "処理場所、外部サービス、連携権限、認証情報の保護を文書化します。", "実際の質問、不足した文脈、閲覧制限文書でテストし、不確実な案件は人に渡します。", "開始前に、範囲、情報源の責任者、役割、保存、ログ、インシデント責任者、見直し日を確認します。"], faqs: [{ question: "すべての文書を読ませてもよいですか？", answer: "いいえ。業務に必要な承認済み情報源だけに限定します。" }, { question: "会話を保存すべきですか？", answer: "明確な目的、期間、アクセス管理がある場合だけです。" }, { question: "人の確認は必要ですか？", answer: "機密性が高い案件や不確実な案件では必要です。" }] }),
} satisfies Record<LocaleCode, BlogPostTranslation>;

export default {
  slug: "private-ai-assistant-privacy-checklist",
  title: translations.en.title,
  language: "en",
  description: translations.en.description,
  tags: translations.en.tags,
  published: true,
  status: "published",
  publishDate: "2026-08-03",
  image: "/assets/swiss-ai-websites-hero.png",
  imageAlt: "Illustration of a private internal AI assistant protected by document permissions, access controls and privacy safeguards.",
  author: "Websiteli",
  date: "2026-08-03",
  updated: "2026-08-03",
  translationFallback: false,
  social: {
    linkedin: "Before connecting company documents to a private AI assistant, define data boundaries, permissions, retention, logging, deletion and human escalation.",
    facebook: "New checklist: privacy and permission controls for a private internal AI assistant in a small business.",
    instagram: "Private AI assistant: minimum data, preserved permissions, clear deletion and human escalation.",
  },
  related: [
    "/en/services/ai-assistants/",
    "/en/services/ai-integrations/",
    "/en/services/business-automation/",
    "/en/services-pricing/",
    "/en/contact/",
  ],
  translations,
} satisfies BlogPostSource;
