import type { LocaleCode } from "../../locales";
import type { BlogPostSource, BlogPostTranslation } from "../types";

type LocalizedCopy = {
  title: string;
  description: string;
  category: string;
  readingTime: string;
  audience: string;
  excerpt: string;
  headings: [string, string, string, string, string, string, string];
  paragraphs: [string, string, string, string, string, string, string];
};

function makeTranslation(language: LocaleCode, copy: LocalizedCopy): BlogPostTranslation {
  const body = copy.headings
    .map((heading, index) => `## ${heading}\n\n${copy.paragraphs[index]}`)
    .join("\n\n");

  return {
    title: copy.title,
    description: copy.description,
    category: copy.category,
    tags: ["internal AI assistant pilot", "AI use case selection", "AI implementation for SMEs", "business AI governance"],
    language,
    readingTime: copy.readingTime,
    audience: copy.audience,
    excerpt: copy.excerpt,
    summary: [copy.excerpt, copy.paragraphs[1], copy.paragraphs[2], copy.paragraphs[6]],
    keyTakeaways: [copy.paragraphs[0], copy.paragraphs[3], copy.paragraphs[4], copy.paragraphs[6]],
    chatGptPrompts: [
      `${copy.headings[0]}: help me compare three possible pilot use cases.`,
      `${copy.headings[2]}: create measurable acceptance criteria for my chosen workflow.`,
      `${copy.headings[6]}: create a decision checklist for improving, expanding or stopping the pilot.`,
    ],
    faqs: [
      { question: copy.headings[0], answer: copy.paragraphs[0] },
      { question: copy.headings[2], answer: copy.paragraphs[2] },
      { question: copy.headings[4], answer: copy.paragraphs[4] },
      { question: copy.headings[6], answer: copy.paragraphs[6] },
    ],
    body: `${body}\n\n[Internal AI assistants](/en/services/ai-assistants/) · [AI integrations](/en/services/ai-integrations/) · [Business automation](/en/services/business-automation/) · [Services and pricing](/en/services-pricing/) · [Contact](/en/contact/)`,
  };
}

const translations = {
  en: makeTranslation("en", {
    title: "How to Scope an Internal AI Assistant Pilot for a Small Business",
    description: "A practical guide for Swiss and European SMEs to choose one internal AI assistant use case, define boundaries, assign owners and run a controlled pilot.",
    category: "AI Implementation",
    readingTime: "12 min read",
    audience: "Swiss and European SMEs planning their first internal AI assistant pilot",
    excerpt: "A successful pilot starts with one repeatable task, trusted sources, clear permissions and a measurable decision about whether to expand.",
    headings: ["Choose a narrow task with visible business value", "Define users, sources and boundaries", "Set success criteria before building", "Design the smallest workable pilot", "Assign ownership and decision rights", "Run the pilot with real questions", "Decide whether to improve, expand or stop"],
    paragraphs: ["Start with a task that happens often, consumes time and can be checked against an authoritative source. Good pilot candidates include finding an approved procedure, preparing a standard briefing or answering recurring internal product questions. Avoid broad goals such as ‘answer anything about the company,’ because they hide missing documents, unclear ownership and conflicting expectations.", "Name the first user group, the source systems and the information that must remain out of scope. Decide whether the assistant may only retrieve information or may also draft, send, edit or publish. For Swiss and European businesses, permissions, personal data and confidential material should be addressed before documents are indexed, not after the first demonstration.", "Write down what a useful result means. Criteria can include finding the current source, citing it, refusing unsupported questions, respecting role-based access and handing sensitive cases to a person. Also define unacceptable failures. A pilot is easier to judge when the team agrees on evidence before seeing polished outputs.", "Use the smallest document collection and integration set that can complete the chosen task. Clean versions, clear titles and named owners usually matter more than adding more files. Keep the interface simple, limit the number of actions and preserve a manual fallback so users can finish their work when the assistant is uncertain.", "Assign a business owner for the workflow, a content owner for each source and a technical owner for the system. Decide who approves access, resolves contradictory documents, reviews failures and authorizes scope changes. Without these roles, a pilot can produce useful demos but no reliable operating process.", "Test with real users and realistic wording, including incomplete questions, multilingual terms, outdated expressions and cases with no answer. Record the question, retrieved source, response, user decision and any extra verification work. The goal is not to collect only successful examples but to understand where the workflow breaks.", "Expand only when the original use case is reliable and the next use case has its own owner, sources and acceptance criteria. Improve the pilot when failures are fixable through cleaner documents, better retrieval or clearer instructions. Stop when the task is too rare, the source quality is poor, the risk is disproportionate or a simpler search or workflow tool solves the problem better."],
  }),
  de: makeTranslation("de", {
    title: "Pilot für einen internen KI-Assistenten richtig abgrenzen: Leitfaden für KMU",
    description: "Praxisleitfaden für Schweizer und europäische KMU: ersten Anwendungsfall wählen, Grenzen definieren, Verantwortliche festlegen und einen kontrollierten KI-Pilot durchführen.",
    category: "KI-Implementierung",
    readingTime: "13 Min. Lesezeit",
    audience: "Schweizer und europäische KMU, die einen ersten internen KI-Assistenten pilotieren",
    excerpt: "Ein erfolgreicher Pilot beginnt mit einer klaren Aufgabe, verlässlichen Quellen, sauberen Berechtigungen und messbaren Entscheidungskriterien.",
    headings: ["Eine klar begrenzte Aufgabe mit erkennbarem Nutzen wählen", "Nutzergruppen, Quellen und Grenzen festlegen", "Erfolgskriterien vor der Umsetzung definieren", "Den kleinsten funktionsfähigen Pilot entwerfen", "Verantwortung und Entscheidungsrechte zuweisen", "Mit realen Fragen und echten Nutzenden testen", "Verbessern, erweitern oder bewusst stoppen"],
    paragraphs: ["Beginnen Sie mit einer wiederkehrenden Aufgabe, die Zeit kostet und anhand einer verbindlichen Quelle überprüft werden kann. Geeignet sind etwa das Finden einer freigegebenen Prozessbeschreibung, das Erstellen eines standardisierten Briefings oder die Beantwortung wiederkehrender interner Produktfragen. Ein Ziel wie „alles über das Unternehmen beantworten“ ist für einen Pilot zu breit und verdeckt fehlende Dokumente sowie unklare Zuständigkeiten.", "Legen Sie fest, wer den Assistenten zuerst nutzt, welche Systeme als Quellen dienen und welche Informationen ausgeschlossen bleiben. Entscheiden Sie, ob das System nur recherchieren oder auch Inhalte entwerfen, versenden, ändern oder veröffentlichen darf. Berechtigungen, Personendaten und vertrauliche Inhalte müssen bei Schweizer und europäischen Unternehmen vor der Indexierung geklärt sein.", "Beschreiben Sie konkret, wann das Ergebnis brauchbar ist. Dazu können die richtige aktuelle Quelle, eine nachvollziehbare Quellenangabe, die Ablehnung unbelegter Fragen, rollenbasierter Zugriff und eine klare Übergabe an Menschen gehören. Definieren Sie auch kritische Fehler. So wird der Pilot nach vereinbarten Kriterien statt nach einer überzeugenden Demo bewertet.", "Verwenden Sie nur die kleinste Dokumentensammlung und die wenigen Integrationen, die für den gewählten Ablauf nötig sind. Gepflegte Versionen, klare Titel und benannte Verantwortliche sind meist wichtiger als möglichst viele Dateien. Halten Sie die Oberfläche einfach, begrenzen Sie Aktionen und erhalten Sie einen manuellen Ausweichprozess.", "Bestimmen Sie eine fachliche Verantwortung für den Ablauf, Verantwortliche für jede Quelle und eine technische Verantwortung für das System. Klären Sie, wer Zugriffe genehmigt, widersprüchliche Dokumente auflöst, Fehler prüft und Umfangsänderungen freigibt. Ohne diese Rollen bleibt ein Pilot eine Demonstration statt eines belastbaren Betriebsmodells.", "Testen Sie mit echten Nutzenden und realistischen Formulierungen. Dazu gehören unvollständige Fragen, mehrsprachige Begriffe, veraltete Bezeichnungen und Fälle ohne vorhandene Antwort. Dokumentieren Sie Frage, gefundene Quelle, Antwort, Nutzerentscheidung und zusätzliche Prüfarbeit. Gerade Fehlfälle zeigen, welche Teile des Prozesses verbessert werden müssen.", "Erweitern Sie erst, wenn der erste Anwendungsfall zuverlässig funktioniert und der nächste eigene Quellen, Verantwortliche und Abnahmekriterien besitzt. Verbessern Sie den Pilot bei lösbaren Problemen in Dokumenten, Suche oder Anweisungen. Stoppen Sie bewusst, wenn die Aufgabe zu selten ist, die Quellen unzuverlässig sind, das Risiko unverhältnismässig ist oder eine einfachere Suche beziehungsweise Automatisierung genügt."],
  }),
  hu: makeTranslation("hu", { title: "Belső AI-asszisztens pilot megfelelő lehatárolása kisvállalkozásoknak", description: "Gyakorlati útmutató svájci és európai kkv-knak az első feladat, források, felelősök és mérési feltételek kijelöléséhez.", category: "AI-bevezetés", readingTime: "10 perc olvasás", audience: "Belső AI-asszisztens pilotot tervező svájci és európai kkv-k", excerpt: "A jó pilot egy ellenőrizhető feladatra, megbízható forrásokra és világos döntési feltételekre épül.", headings: ["Válasszon szűk, értékes feladatot", "Határozza meg a felhasználókat és a határokat", "Rögzítse előre a sikerkritériumokat", "Építse meg a legkisebb működő pilotot", "Jelölje ki a felelősöket", "Teszteljen valós kérdésekkel", "Döntsön a folytatásról"], paragraphs: ["Gyakori, időigényes és hiteles forrás alapján ellenőrizhető feladattal kezdjen; ne egy általános, mindentudó asszisztenssel.", "Rögzítse az első felhasználói csoportot, a forrásrendszereket, a kizárt adatokat és azt, hogy az asszisztens csak kereshet-e vagy műveletet is végezhet.", "Írja le, mit jelent a jó válasz: aktuális forrás, hivatkozás, jogosultságok tisztelete, bizonytalanság jelzése és emberi átadás.", "Csak a szükséges dokumentumokat és integrációkat használja, tartson meg kézi kerülőutat, és ne bővítse idő előtt a hatókört.", "Legyen üzleti, tartalmi és technikai felelős, valamint egyértelmű jóváhagyási és hibakezelési folyamat.", "Valós felhasználókkal, hiányos, többnyelvű és megválaszolhatatlan kérdésekkel teszteljen, és rögzítse a plusz ellenőrzési munkát is.", "Csak stabil eredmény után bővítsen; javítson, ha a hiba megoldható, és álljon le, ha egyszerűbb eszköz jobb eredményt ad."] }),
  pl: makeTranslation("pl", { title: "Jak określić zakres pilotażu wewnętrznego asystenta AI w małej firmie", description: "Praktyczny przewodnik dla szwajcarskich i europejskich MŚP: wybór pierwszego przypadku użycia, granic, właścicieli i kryteriów decyzji.", category: "Wdrożenie AI", readingTime: "10 min czytania", audience: "Szwajcarskie i europejskie MŚP planujące pilotaż asystenta AI", excerpt: "Dobry pilotaż opiera się na jednym sprawdzalnym zadaniu, wiarygodnych źródłach i jasnej decyzji o dalszych krokach.", headings: ["Wybierz wąskie zadanie o widocznej wartości", "Określ użytkowników, źródła i granice", "Ustal kryteria sukcesu przed budową", "Zaprojektuj najmniejszy działający pilotaż", "Przypisz właścicieli i decyzje", "Testuj prawdziwe pytania", "Zdecyduj: poprawić, rozszerzyć czy zatrzymać"], paragraphs: ["Zacznij od częstego zadania, które zajmuje czas i można je sprawdzić w zatwierdzonym źródle, zamiast od asystenta do wszystkiego.", "Określ pierwszą grupę użytkowników, systemy źródłowe, dane poza zakresem oraz dozwolone działania.", "Zapisz, co oznacza poprawny wynik: aktualne źródło, cytowanie, odmowa bez dowodów, właściwe prawa i eskalacja.", "Użyj minimalnego zestawu dokumentów i integracji, zachowaj ręczną ścieżkę i prosty interfejs.", "Wyznacz właściciela procesu, źródeł i technologii oraz osoby zatwierdzające dostęp i zmiany zakresu.", "Testuj realne, niepełne, wielojęzyczne i bezodpowiedziowe pytania; zapisuj również dodatkową pracę weryfikacyjną.", "Rozszerzaj po osiągnięciu niezawodności, poprawiaj naprawialne błędy i zatrzymaj projekt, gdy prostsze rozwiązanie jest lepsze."] }),
  es: makeTranslation("es", { title: "Cómo definir el alcance de un piloto de asistente interno de IA", description: "Guía práctica para pymes suizas y europeas: elegir un caso de uso, límites, responsables y criterios para un piloto controlado.", category: "Implementación de IA", readingTime: "10 min de lectura", audience: "Pymes suizas y europeas que preparan su primer piloto de IA interna", excerpt: "Un buen piloto empieza con una tarea verificable, fuentes fiables, permisos claros y criterios para decidir si ampliar.", headings: ["Elige una tarea limitada con valor visible", "Define usuarios, fuentes y límites", "Fija criterios de éxito antes de construir", "Diseña el piloto mínimo viable", "Asigna responsables y decisiones", "Prueba con preguntas reales", "Decide si mejorar, ampliar o parar"], paragraphs: ["Empieza con una tarea frecuente, costosa en tiempo y verificable mediante una fuente autorizada; evita un asistente que pretenda responder sobre todo.", "Define el primer grupo de usuarios, los sistemas fuente, la información excluida y las acciones permitidas.", "Acordad qué significa un buen resultado: fuente vigente, cita, rechazo sin evidencia, permisos y escalado humano.", "Usa solo los documentos e integraciones necesarios, conserva una alternativa manual y limita las acciones.", "Asigna responsables de negocio, contenido y tecnología, además de la aprobación de accesos y cambios.", "Prueba formulaciones reales, incompletas, multilingües y sin respuesta, registrando también el trabajo extra de verificación.", "Amplía solo tras lograr fiabilidad; mejora errores corregibles y detén el piloto si una herramienta más simple resuelve mejor el problema."] }),
  fr: makeTranslation("fr", { title: "Bien cadrer le pilote d’un assistant IA interne pour une PME", description: "Guide pratique pour PME suisses et européennes afin de choisir un premier usage, fixer les limites, nommer les responsables et évaluer le pilote.", category: "Mise en œuvre de l’IA", readingTime: "10 min de lecture", audience: "PME suisses et européennes préparant un premier pilote d’assistant IA", excerpt: "Un pilote utile commence par une tâche vérifiable, des sources fiables, des droits clairs et des critères de décision.", headings: ["Choisir une tâche étroite à valeur visible", "Définir utilisateurs, sources et limites", "Fixer les critères de réussite avant de construire", "Concevoir le plus petit pilote viable", "Attribuer responsabilités et décisions", "Tester avec de vraies questions", "Décider d’améliorer, étendre ou arrêter"], paragraphs: ["Commencez par une tâche fréquente, chronophage et vérifiable dans une source approuvée, plutôt que par un assistant généraliste.", "Définissez le premier groupe d’utilisateurs, les systèmes sources, les données hors périmètre et les actions autorisées.", "Précisez ce qu’est un bon résultat: source à jour, citation, refus sans preuve, respect des droits et transfert humain.", "Limitez les documents et intégrations au strict nécessaire, gardez une solution manuelle et une interface simple.", "Nommez un responsable métier, des responsables de contenu et un responsable technique, avec des droits de décision clairs.", "Testez des questions réelles, incomplètes, multilingues et sans réponse, en mesurant aussi le travail de vérification ajouté.", "Étendez seulement après fiabilisation; corrigez les défauts réparables et arrêtez si une solution plus simple convient mieux."] }),
  it: makeTranslation("it", { title: "Come definire il perimetro di un pilota per un assistente AI interno", description: "Guida pratica per PMI svizzere ed europee: scegliere il primo caso d’uso, stabilire confini, responsabili e criteri di valutazione.", category: "Implementazione AI", readingTime: "10 min di lettura", audience: "PMI svizzere ed europee che pianificano un primo pilota AI interno", excerpt: "Un buon pilota parte da un compito verificabile, fonti affidabili, permessi chiari e criteri per decidere se ampliare.", headings: ["Scegliere un compito limitato e utile", "Definire utenti, fonti e confini", "Stabilire prima i criteri di successo", "Progettare il minimo pilota funzionante", "Assegnare responsabilità e decisioni", "Testare domande reali", "Decidere se migliorare, ampliare o fermare"], paragraphs: ["Parti da un compito frequente, dispendioso e verificabile in una fonte approvata, non da un assistente universale.", "Definisci il primo gruppo utenti, i sistemi fonte, i dati esclusi e le azioni consentite.", "Concorda cosa significa successo: fonte aggiornata, citazione, rifiuto senza evidenza, permessi ed escalation.", "Usa solo documenti e integrazioni necessari, mantieni un’alternativa manuale e limita le azioni.", "Nomina responsabili di processo, contenuti e tecnologia, chiarendo chi approva accessi e modifiche.", "Testa domande reali, incomplete, multilingue e senza risposta, registrando anche la verifica aggiuntiva.", "Amplia solo dopo risultati affidabili; correggi gli errori risolvibili e fermati se uno strumento semplice è migliore."] }),
  cz: makeTranslation("cz", { title: "Jak vymezit pilot interního AI asistenta pro malou firmu", description: "Praktický průvodce pro švýcarské a evropské firmy: první případ použití, hranice, odpovědnosti a kritéria rozhodnutí.", category: "Zavádění AI", readingTime: "10 min čtení", audience: "Švýcarské a evropské malé firmy plánující pilot AI asistenta", excerpt: "Dobrý pilot stojí na jednom ověřitelném úkolu, důvěryhodných zdrojích, jasných právech a měřitelném rozhodnutí.", headings: ["Vyberte úzký a hodnotný úkol", "Určete uživatele, zdroje a hranice", "Stanovte kritéria úspěchu předem", "Navrhněte nejmenší funkční pilot", "Přiřaďte odpovědnosti", "Testujte skutečné otázky", "Rozhodněte o zlepšení, rozšíření či ukončení"], paragraphs: ["Začněte častým úkolem, který bere čas a lze jej ověřit v autorizovaném zdroji, nikoli univerzálním asistentem.", "Určete první uživatele, zdrojové systémy, vyloučená data a povolené akce.", "Sepište úspěch: aktuální zdroj, citace, odmítnutí bez důkazů, správná oprávnění a předání člověku.", "Použijte minimum dokumentů a integrací, zachovejte ruční postup a jednoduché rozhraní.", "Určete vlastníka procesu, obsahu a technologie a jasně nastavte schvalování přístupů a změn.", "Testujte reálné, neúplné, vícejazyčné a nezodpověditelné otázky a měřte i dodatečné ověřování.", "Rozšiřujte až po dosažení spolehlivosti; opravujte řešitelné chyby a zastavte, když je jednodušší nástroj vhodnější."] }),
  sk: makeTranslation("sk", { title: "Ako vymedziť pilot interného AI asistenta pre malú firmu", description: "Praktický sprievodca pre švajčiarske a európske firmy: prvý prípad použitia, hranice, zodpovednosti a kritériá rozhodnutia.", category: "Zavádzanie AI", readingTime: "10 min čítania", audience: "Švajčiarske a európske malé firmy plánujúce pilot AI asistenta", excerpt: "Dobrý pilot stojí na jednej overiteľnej úlohe, dôveryhodných zdrojoch, jasných právach a merateľnom rozhodnutí.", headings: ["Vyberte úzku a hodnotnú úlohu", "Určte používateľov, zdroje a hranice", "Stanovte kritériá úspechu vopred", "Navrhnite najmenší funkčný pilot", "Priraďte zodpovednosti", "Testujte skutočné otázky", "Rozhodnite o zlepšení, rozšírení či ukončení"], paragraphs: ["Začnite častou úlohou, ktorá berie čas a dá sa overiť v schválenom zdroji, nie univerzálnym asistentom.", "Určte prvých používateľov, zdrojové systémy, vylúčené dáta a povolené akcie.", "Spíšte úspech: aktuálny zdroj, citácia, odmietnutie bez dôkazov, správne oprávnenia a odovzdanie človeku.", "Použite minimum dokumentov a integrácií, zachovajte ručný postup a jednoduché rozhranie.", "Určte vlastníka procesu, obsahu a technológie a jasne nastavte schvaľovanie prístupov a zmien.", "Testujte reálne, neúplné, viacjazyčné a nezodpovedateľné otázky a merajte aj dodatočné overovanie.", "Rozširujte až po spoľahlivom výsledku; opravujte riešiteľné chyby a zastavte, ak je jednoduchší nástroj vhodnejší."] }),
  pt: makeTranslation("pt", { title: "Como definir o âmbito de um piloto de assistente interno de IA", description: "Guia prático para PME suíças e europeias: escolher um caso de uso, limites, responsáveis e critérios para um piloto controlado.", category: "Implementação de IA", readingTime: "10 min de leitura", audience: "PME suíças e europeias a preparar o primeiro piloto de IA interna", excerpt: "Um bom piloto começa com uma tarefa verificável, fontes fiáveis, permissões claras e critérios para decidir se deve crescer.", headings: ["Escolher uma tarefa limitada com valor visível", "Definir utilizadores, fontes e limites", "Fixar critérios de sucesso antes de construir", "Desenhar o menor piloto viável", "Atribuir responsáveis e decisões", "Testar com perguntas reais", "Decidir melhorar, expandir ou parar"], paragraphs: ["Começa com uma tarefa frequente, demorada e verificável numa fonte autorizada, não com um assistente para tudo.", "Define o primeiro grupo de utilizadores, sistemas fonte, dados excluídos e ações permitidas.", "Acorda o que significa sucesso: fonte atual, citação, recusa sem evidência, permissões e escalamento humano.", "Usa apenas documentos e integrações necessários, mantém uma alternativa manual e limita as ações.", "Nomeia responsáveis pelo processo, conteúdos e tecnologia, incluindo aprovação de acessos e mudanças.", "Testa perguntas reais, incompletas, multilingues e sem resposta, registando também o trabalho extra de verificação.", "Expande só após resultados fiáveis; corrige falhas resolúveis e para se uma ferramenta mais simples for melhor."] }),
  da: makeTranslation("da", { title: "Sådan afgrænser en lille virksomhed en pilot med en intern AI-assistent", description: "Praktisk guide til schweiziske og europæiske SMV’er om valg af første use case, grænser, ansvar og beslutningskriterier.", category: "AI-implementering", readingTime: "10 min læsetid", audience: "Schweiziske og europæiske SMV’er, der planlægger en intern AI-pilot", excerpt: "En god pilot starter med én kontrollerbar opgave, pålidelige kilder, klare rettigheder og målbare beslutninger.", headings: ["Vælg en smal opgave med synlig værdi", "Definér brugere, kilder og grænser", "Fastlæg succeskriterier før udvikling", "Design den mindste brugbare pilot", "Fordel ansvar og beslutninger", "Test med virkelige spørgsmål", "Beslut om forbedring, udvidelse eller stop"], paragraphs: ["Start med en hyppig og tidskrævende opgave, der kan kontrolleres i en godkendt kilde, ikke en assistent til alt.", "Definér første brugergruppe, kildesystemer, udelukkede data og tilladte handlinger.", "Beskriv succes: aktuel kilde, citation, afvisning uden bevis, korrekte rettigheder og menneskelig eskalering.", "Brug kun nødvendige dokumenter og integrationer, behold en manuel vej og begræns handlingerne.", "Udpeg ejere af proces, indhold og teknik samt klare beslutninger om adgang og ændringer.", "Test virkelige, ufuldstændige, flersprogede og ubesvarelige spørgsmål og registrér ekstra kontrolarbejde.", "Udvid først efter stabil drift; ret løselige fejl og stop, hvis et enklere værktøj er bedre."] }),
  nl: makeTranslation("nl", { title: "Zo bepaal je de scope van een pilot met een interne AI-assistent", description: "Praktische gids voor Zwitserse en Europese mkb-bedrijven: kies één use case, grenzen, eigenaren en meetbare besliscriteria.", category: "AI-implementatie", readingTime: "10 min leestijd", audience: "Zwitserse en Europese mkb-bedrijven die een interne AI-pilot plannen", excerpt: "Een goede pilot begint met één controleerbare taak, betrouwbare bronnen, duidelijke rechten en meetbare besliscriteria.", headings: ["Kies een smalle taak met zichtbare waarde", "Bepaal gebruikers, bronnen en grenzen", "Leg succescriteria vast vóór de bouw", "Ontwerp de kleinste werkbare pilot", "Wijs eigenaarschap en besluiten toe", "Test met echte vragen", "Beslis over verbeteren, uitbreiden of stoppen"], paragraphs: ["Begin met een frequente taak die tijd kost en via een goedgekeurde bron controleerbaar is, niet met een assistent voor alles.", "Bepaal de eerste gebruikersgroep, bronsystemen, uitgesloten gegevens en toegestane acties.", "Omschrijf succes: actuele bron, citaat, weigering zonder bewijs, juiste rechten en menselijke escalatie.", "Gebruik alleen noodzakelijke documenten en integraties, behoud een handmatige route en beperk acties.", "Wijs proceseigenaars, contenteigenaars en een technisch eigenaar aan en leg besluitrechten vast.", "Test echte, onvolledige, meertalige en onbeantwoordbare vragen en registreer extra controlewerk.", "Breid pas uit na betrouwbare resultaten; herstel oplosbare fouten en stop als een eenvoudiger hulpmiddel beter is."] }),
  ja: makeTranslation("ja", { title: "中小企業向け：社内AIアシスタントのパイロット範囲を決める方法", description: "スイス・欧州の中小企業向けに、最初の用途、対象範囲、責任者、評価基準を定める実践ガイド。", category: "AI導入", readingTime: "10分で読めます", audience: "初めて社内AIアシスタントを試験導入するスイス・欧州の中小企業", excerpt: "良いパイロットは、確認可能な一つの業務、信頼できる情報源、明確な権限、測定可能な判断基準から始まります。", headings: ["価値が見える狭い業務を選ぶ", "利用者・情報源・範囲を定める", "開発前に成功基準を決める", "最小限のパイロットを設計する", "責任者と決定権を割り当てる", "実際の質問でテストする", "改善・拡大・停止を判断する"], paragraphs: ["頻度が高く時間がかかり、承認済みの情報源で確認できる業務から始め、何でも答える助手は避けます。", "最初の利用者、接続元、対象外データ、許可する操作を明確にします。", "最新版の取得、引用、根拠がない場合の拒否、権限維持、人への引き継ぎを成功条件にします。", "必要最小限の文書と連携だけを使い、手動の代替手段と単純な操作範囲を残します。", "業務、情報源、技術の責任者を決め、アクセス承認と範囲変更の決定権を明確にします。", "実際の利用者が、不完全、多言語、回答不能な質問を試し、追加確認の負担も記録します。", "信頼性が得られてから拡大し、修正可能な問題は改善し、単純な手段の方が適切なら停止します。"] }),
} satisfies Record<LocaleCode, BlogPostTranslation>;

export default {
  slug: "scope-internal-ai-assistant-pilot",
  published: true,
  status: "published",
  publishDate: "2026-08-06",
  image: "/assets/blog/prepare-company-documents-internal-ai-assistant.png",
  imageAlt: "Websiteli guide to scoping an internal AI assistant pilot with one use case, trusted sources, clear permissions, owners and measurable decision criteria.",
  author: "Websiteli",
  date: "2026-08-06",
  updated: "2026-08-06",
  related: ["internal-ai-assistant-small-business", "prepare-company-documents-internal-ai-assistant", "test-internal-ai-assistant-before-launch"],
  translations,
} satisfies BlogPostSource;
