import type { LocaleCode } from "../../locales";
import type { BlogPostSource, BlogPostTranslation } from "../types";

type Copy = {
  title: string;
  description: string;
  category: string;
  tags: string[];
  readingTime: string;
  audience: string;
  excerpt: string;
  summary: string[];
  takeaways: string[];
  prompts: string[];
  headings: [string, string, string, string, string, string];
  paragraphs: [string, string, string, string, string, string];
  faqs: { question: string; answer: string }[];
};

function makeTranslation(language: LocaleCode, copy: Copy): BlogPostTranslation {
  return {
    title: copy.title,
    description: copy.description,
    category: copy.category,
    tags: copy.tags,
    language,
    readingTime: copy.readingTime,
    audience: copy.audience,
    excerpt: copy.excerpt,
    summary: copy.summary,
    keyTakeaways: copy.takeaways,
    chatGptPrompts: copy.prompts,
    faqs: copy.faqs,
    body:
      copy.headings.map((heading, index) => `## ${heading}\n\n${copy.paragraphs[index]}`).join("\n\n") +
      `\n\n[Business websites](/en/services/business-websites/) · [Website maintenance](/en/services/website-maintenance/) · [Website redesign](/en/services/website-redesign/) · [Services and pricing](/en/services-pricing/) · [Contact Websiteli](/en/contact/)`,
  };
}

const translations = {
  en: makeTranslation("en", {
    title: "Website Accessibility for Small Businesses: A Practical Checklist",
    description: "A practical website accessibility guide for small businesses: improve readability, keyboard use, images, forms, structure and testing without turning the project into jargon.",
    category: "Website Quality",
    tags: ["website accessibility", "small business website", "accessible website", "website usability", "website quality"],
    readingTime: "9 min read",
    audience: "Small-business owners and teams who want their website to be easier for more people to understand and use",
    excerpt: "Accessibility is practical website quality: clear content, usable navigation, understandable forms and interfaces that do not depend on one way of seeing or operating a page.",
    summary: [
      "Start accessibility work with the customer journey: reading, navigating, completing forms and understanding feedback.",
      "Readable text, sufficient visual distinction and a logical heading structure make pages easier to use for many visitors.",
      "Important actions should be usable with a keyboard and should have a visible focus state.",
      "Images need useful alternative text when they carry meaning; decorative images should not create noise.",
      "Forms need clear labels, understandable errors and confirmation that explains what happens next.",
    ],
    takeaways: [
      "Fix the most important customer paths before polishing secondary pages.",
      "Test with a keyboard, zoomed text and real form submissions.",
      "Use semantic headings, descriptive links and meaningful image alternatives.",
      "Treat accessibility as ongoing quality work, not a one-time badge.",
      "Prioritize issues that block understanding or completion of a business-critical action.",
    ],
    prompts: [
      "Turn this article into an accessibility review checklist for my business website.",
      "Review the content of my homepage for unclear headings, link text and form instructions.",
      "Create a prioritized accessibility QA plan for my website's contact and booking journeys.",
    ],
    headings: [
      "Start with the customer journey, not the checklist",
      "Make text and structure easy to understand",
      "Make navigation and actions usable without a mouse",
      "Give images, buttons and links enough meaning",
      "Make forms understandable from start to finish",
      "Test accessibility as part of normal website maintenance",
    ],
    paragraphs: [
      "Accessibility becomes manageable when you begin with real tasks. Can a visitor understand the offer, move through the navigation, find contact information, complete the main form and recognize whether it succeeded? Review the pages that matter most to enquiries, bookings and customer support first. This keeps the work connected to business value and helps you prioritize barriers that prevent people from completing an important action.",
      "Use clear language, descriptive headings and a logical heading order. Keep body text readable, avoid placing essential information only inside images, and make sure important controls remain distinguishable from their surroundings. Visitors should not need perfect vision, a large screen or prior knowledge of your site to understand where they are. When content is easier to scan and interpret, it also tends to support better general usability.",
      "A visitor should be able to move through menus, links, buttons and form fields with a keyboard. Focus should remain visible so the person can see which element is active. Avoid interaction patterns that trap the visitor inside a menu, popup or widget. Test the page yourself with the Tab key and activate important controls without touching the mouse. If the main enquiry path breaks, treat it as a high-priority website issue.",
      "Alternative text should communicate the purpose of an image when that image contributes information. Decorative visuals usually do not need a verbal description that distracts from the page. Button and link text should explain the action or destination rather than relying on vague phrases such as 'click here'. Icons that perform an action need an understandable name. The goal is to preserve meaning even when someone experiences the interface differently from the original visual design.",
      "Forms are common failure points because they combine labels, instructions, validation and follow-up. Every field should have a clear label, required information should be understandable, and errors should explain what needs to change. Do not rely on colour alone to communicate an error. After submission, confirm that the message was received and explain the next step. Test the form on mobile and desktop and verify that the enquiry reaches the intended recipient or system.",
      "Accessibility is easier to maintain when it becomes part of ordinary QA. Re-test key journeys after design changes, new plugins, content updates or form edits. Include keyboard use, zoomed text, heading structure, images, links and forms in recurring website checks. Automated tools can help find certain issues, but they do not replace human review of whether a page actually makes sense and can be completed. Websiteli can include accessibility-oriented checks within [website maintenance](/en/services/website-maintenance/) or a focused [website redesign](/en/services/website-redesign/).",
    ],
    faqs: [
      { question: "What is website accessibility for a small business?", answer: "It means designing and maintaining the website so more people can understand, navigate and complete important tasks, including visitors who use keyboards, zoom, assistive technology or different ways of perceiving content." },
      { question: "What should I fix first?", answer: "Start with barriers in business-critical journeys such as navigation, contact forms, booking, quote requests and essential service information." },
      { question: "Is an automated accessibility scan enough?", answer: "No. Automated tools can identify some technical issues, but human testing is still needed to judge clarity, keyboard flow, instructions, context and whether a task can actually be completed." },
      { question: "How often should accessibility be checked?", answer: "Check important journeys whenever the site changes and include accessibility in recurring maintenance rather than treating it as a one-time project." },
    ],
  }),

  de: makeTranslation("de", {
    title: "Barrierefreie Websites für KMU: Eine praktische Checkliste",
    description: "Praxisleitfaden für KMU: Lesbarkeit, Tastaturbedienung, Bilder, Formulare, Seitenstruktur und Tests verständlich verbessern.",
    category: "Website-Qualität",
    tags: ["barrierefreie Website", "KMU Website", "Web Accessibility", "Website Usability", "Website Qualität"],
    readingTime: "10 Min. Lesezeit",
    audience: "Schweizer und europäische KMU, die ihre Website für mehr Menschen verständlich und nutzbar machen möchten",
    excerpt: "Barrierefreiheit ist praktische Website-Qualität: klare Inhalte, nutzbare Navigation, verständliche Formulare und Bedienung ohne Abhängigkeit von nur einer Eingabemethode.",
    summary: [
      "Beginnen Sie mit den wichtigsten Kundenwegen: lesen, navigieren, Formulare ausfüllen und Rückmeldungen verstehen.",
      "Klare Typografie, erkennbare Elemente und eine logische Überschriftenstruktur erleichtern die Nutzung.",
      "Wichtige Aktionen sollten mit der Tastatur bedienbar sein und einen sichtbaren Fokus besitzen.",
      "Bilder benötigen sinnvolle Alternativtexte, wenn sie Informationen tragen.",
      "Formulare brauchen klare Beschriftungen, verständliche Fehler und eine eindeutige Bestätigung.",
    ],
    takeaways: ["Zuerst geschäftskritische Wege prüfen.", "Tastatur, Zoom und echte Formularübermittlung testen.", "Semantische Überschriften und aussagekräftige Links verwenden.", "Barrierefreiheit als laufende Qualitätsarbeit behandeln.", "Blockierende Probleme vor kosmetischen Details priorisieren."],
    prompts: ["Erstelle aus diesem Artikel eine Accessibility-Checkliste für meine KMU-Website.", "Prüfe meine Startseiten-Texte auf unklare Überschriften, Links und Formularhinweise.", "Erstelle einen priorisierten Accessibility-QA-Plan für Kontakt- und Buchungswege."],
    headings: ["Mit dem Kundenweg beginnen, nicht mit der Checkliste", "Text und Struktur leicht verständlich machen", "Navigation und Aktionen ohne Maus nutzbar machen", "Bildern, Buttons und Links genügend Bedeutung geben", "Formulare vom ersten Feld bis zur Bestätigung verständlich machen", "Barrierefreiheit in die normale Website-Wartung integrieren"],
    paragraphs: [
      "Barrierefreiheit wird überschaubar, wenn Sie mit echten Aufgaben beginnen. Können Besucher das Angebot verstehen, durch die Navigation gehen, Kontaktdaten finden, das wichtigste Formular ausfüllen und erkennen, ob die Übermittlung erfolgreich war? Prüfen Sie zuerst Seiten, die für Anfragen, Buchungen und Kundenservice entscheidend sind. So bleibt die Arbeit mit dem Geschäftsnutzen verbunden.",
      "Verwenden Sie klare Sprache, beschreibende Überschriften und eine logische Reihenfolge. Fliesstext sollte gut lesbar sein; wichtige Informationen gehören nicht ausschliesslich in Bilder. Bedienelemente müssen sich ausreichend von ihrer Umgebung unterscheiden. Besucher sollten weder perfekte Sicht noch einen grossen Bildschirm oder Vorwissen benötigen, um die Seite zu verstehen.",
      "Menüs, Links, Buttons und Formularfelder sollten per Tastatur erreichbar sein. Der Fokus muss sichtbar bleiben, damit erkennbar ist, welches Element gerade aktiv ist. Vermeiden Sie Menüs, Popups oder Widgets, aus denen man mit der Tastatur nicht mehr herauskommt. Testen Sie wichtige Wege selbst mit der Tab-Taste und ohne Maus.",
      "Alternativtexte sollten den Zweck eines Bildes beschreiben, wenn das Bild Information vermittelt. Rein dekorative Bilder brauchen meist keine zusätzliche Beschreibung, die den Inhalt unnötig verlängert. Link- und Buttontexte sollten Aktion oder Ziel benennen statt nur 'hier klicken'. Auch Symbole mit Funktion benötigen eine verständliche Bezeichnung.",
      "Formulare verbinden Labels, Hinweise, Validierung und Follow-up und sind deshalb häufige Fehlerquellen. Jedes Feld braucht eine klare Beschriftung. Fehlermeldungen müssen erklären, was geändert werden soll, und dürfen sich nicht nur auf Farbe stützen. Nach dem Absenden sollte eine Bestätigung erscheinen und den nächsten Schritt erklären. Prüfen Sie zudem, ob die Anfrage tatsächlich beim richtigen Empfänger ankommt.",
      "Barrierefreiheit lässt sich besser erhalten, wenn sie Teil der normalen Qualitätssicherung ist. Prüfen Sie zentrale Wege nach Designänderungen, neuen Plugins, Content-Updates oder Formularanpassungen erneut. Tastaturbedienung, Zoom, Überschriftenstruktur, Bilder, Links und Formulare gehören in regelmässige Checks. Automatische Werkzeuge helfen bei einzelnen technischen Problemen, ersetzen aber keine menschliche Prüfung. Websiteli kann solche Checks in die [Website-Wartung](/en/services/website-maintenance/) oder einen gezielten [Website-Redesign](/en/services/website-redesign/) integrieren.",
    ],
    faqs: [
      { question: "Was bedeutet Website-Barrierefreiheit für ein KMU?", answer: "Die Website wird so gestaltet und gepflegt, dass mehr Menschen Inhalte verstehen, navigieren und wichtige Aufgaben erledigen können – auch mit Tastatur, Zoom oder assistiven Technologien." },
      { question: "Was sollte ich zuerst verbessern?", answer: "Beginnen Sie mit Hindernissen in geschäftskritischen Wegen wie Navigation, Kontaktformularen, Buchungen, Offertanfragen und zentralen Serviceinformationen." },
      { question: "Reicht ein automatischer Accessibility-Scan?", answer: "Nein. Automatische Tools finden gewisse technische Probleme; Klarheit, Tastaturfluss, Kontext und tatsächliche Aufgabenerfüllung müssen zusätzlich menschlich geprüft werden." },
      { question: "Wie oft sollte Barrierefreiheit geprüft werden?", answer: "Nach relevanten Website-Änderungen und regelmässig im Rahmen der Wartung." },
    ],
  }),

  hu: makeTranslation("hu", {
    title: "Weboldal-akadálymentesség kisvállalkozásoknak: gyakorlati ellenőrzőlista",
    description: "Gyakorlati útmutató kisvállalkozásoknak az olvashatóság, billentyűzetes használat, képek, űrlapok, struktúra és tesztelés javításához.",
    category: "Weboldalminőség",
    tags: ["weboldal akadálymentesség", "kisvállalati weboldal", "hozzáférhető weboldal", "weboldal használhatóság", "weboldal minőség"],
    readingTime: "9 perc olvasás",
    audience: "Kisvállalkozások, amelyek több ember számára szeretnék érthetőbbé és használhatóbbá tenni weboldalukat",
    excerpt: "Az akadálymentesség gyakorlati weboldalminőség: egyértelmű tartalom, használható navigáció, érthető űrlapok és többféle kezelési mód.",
    summary: ["A legfontosabb ügyfélutakkal kezdd.", "Az olvasható szöveg és logikus címsorok segítik a megértést.", "A fontos műveletek legyenek billentyűzettel is használhatók.", "Az információt hordozó képekhez kell hasznos alternatív szöveg.", "Az űrlapokhoz egyértelmű címkék, hibák és visszaigazolás szükséges."],
    takeaways: ["Először a kritikus ügyfélutakat javítsd.", "Tesztelj billentyűzettel, nagyítással és valódi űrlapküldéssel.", "Használj leíró linkeket és logikus címsorokat.", "Az akadálymentességet folyamatos minőségbiztosításként kezeld.", "A blokkoló hibák fontosabbak a kozmetikai részleteknél."],
    prompts: ["Készíts akadálymentességi ellenőrzőlistát a weboldalamhoz.", "Vizsgáld át a főoldalam szövegét nem egyértelmű címsorok és linkek szempontjából.", "Készíts prioritásos QA-tervet a kapcsolatfelvételi és foglalási útvonalakhoz."],
    headings: ["Az ügyfélúttal kezdd, ne a listával", "Legyen könnyen érthető a szöveg és a struktúra", "A navigáció működjön egér nélkül is", "Adj jelentést a képeknek, gomboknak és linkeknek", "Tedd érthetővé az űrlap teljes folyamatát", "Építsd be az akadálymentességet a rendszeres karbantartásba"],
    paragraphs: ["Az akadálymentesség akkor kezelhető jól, ha valódi feladatokból indulsz ki. Megérti a látogató az ajánlatot, megtalálja a kapcsolatot, végig tud menni a navigáción és el tudja küldeni a fő űrlapot? Először az érdeklődésekhez, foglalásokhoz és ügyfélszolgálathoz kapcsolódó oldalakat vizsgáld.", "Használj világos nyelvet, leíró címsorokat és logikus sorrendet. A fontos információ ne csak képen szerepeljen, a vezérlők legyenek jól megkülönböztethetők, és az oldal nagyított szöveggel is maradjon érthető.", "A menük, linkek, gombok és mezők legyenek billentyűzettel elérhetők. A fókusz mindig legyen látható, és egy felugró ablak vagy widget ne zárja csapdába a felhasználót. A Tab billentyűvel teszteld végig a legfontosabb útvonalat.", "Ha egy kép információt közöl, az alternatív szöveg mondja el a lényegét. A pusztán dekoratív képek ne növeljék feleslegesen a zajt. A gomb- és linkszöveg írja le a célt, ne csak azt mondja, hogy 'kattints ide'.", "Minden mezőnek legyen világos címkéje, a hibák pedig magyarázzák el, mit kell javítani. Ne csak szín jelezze a problémát. Küldés után legyen egyértelmű visszaigazolás és következő lépés. Mobilon és asztali gépen is próbáld ki a teljes folyamatot.", "Az akadálymentesség legyen része a rendszeres QA-nak. Új dizájn, plugin, tartalom vagy űrlapmódosítás után teszteld újra a kritikus útvonalakat. Az automatikus eszközök hasznosak, de nem helyettesítik azt, hogy egy ember valóban végigpróbálja az oldalt. Websiteli ezt a [weboldal-karbantartás](/en/services/website-maintenance/) vagy [weboldal-redesign](/en/services/website-redesign/) részeként is kezelheti."],
    faqs: [{ question: "Mit jelent a weboldal-akadálymentesség?", answer: "Azt, hogy több ember képes megérteni, navigálni és használni a weboldalt különböző eszközökkel és kezelési módokkal." }, { question: "Mit javítsak először?", answer: "A navigációt, kapcsolatfelvételt, foglalást és más üzletileg kritikus útvonalakat blokkoló hibákat." }, { question: "Elég egy automatikus teszt?", answer: "Nem. Az automatikus eszközök csak bizonyos technikai hibákat találnak meg; emberi tesztelés is kell." }, { question: "Milyen gyakran teszteljem?", answer: "Fontos változtatások után és a rendszeres karbantartás részeként." }],
  }),

  pl: makeTranslation("pl", {
    title: "Dostępność strony internetowej dla małych firm: praktyczna lista kontrolna",
    description: "Praktyczny poradnik dla małych firm: czytelność, obsługa klawiaturą, obrazy, formularze, struktura i testowanie dostępności strony.",
    category: "Jakość strony",
    tags: ["dostępność strony", "strona małej firmy", "dostępna strona", "użyteczność strony", "jakość strony"], readingTime: "9 min czytania", audience: "Małe firmy, które chcą, aby ich strona była łatwiejsza do zrozumienia i użycia dla większej liczby osób", excerpt: "Dostępność to praktyczna jakość strony: jasna treść, użyteczna nawigacja, zrozumiałe formularze i różne sposoby obsługi.",
    summary: ["Zacznij od kluczowych ścieżek klienta.", "Czytelny tekst i logiczne nagłówki ułatwiają korzystanie.", "Ważne działania powinny działać z klawiatury.", "Obrazy przekazujące informacje potrzebują sensownego tekstu alternatywnego.", "Formularze potrzebują jasnych etykiet, błędów i potwierdzeń."], takeaways: ["Najpierw napraw ścieżki krytyczne dla biznesu.", "Testuj klawiaturą, powiększeniem i prawdziwym wysłaniem formularza.", "Używaj opisowych linków i logicznych nagłówków.", "Traktuj dostępność jako stałą kontrolę jakości.", "Priorytetem są bariery blokujące wykonanie zadania."], prompts: ["Zmień ten artykuł w checklistę dostępności dla mojej strony.", "Przejrzyj tekst strony głównej pod kątem niejasnych nagłówków i linków.", "Ułóż priorytetowy plan QA dla formularza kontaktowego i rezerwacji."],
    headings: ["Zacznij od ścieżki klienta, nie od checklisty", "Ułatw zrozumienie tekstu i struktury", "Umożliw nawigację i działania bez myszy", "Nadaj znaczenie obrazom, przyciskom i linkom", "Uczyń formularze zrozumiałymi od początku do końca", "Włącz dostępność do regularnej konserwacji strony"],
    paragraphs: ["Zacznij od realnych zadań: czy odwiedzający rozumie ofertę, znajduje kontakt, przechodzi przez menu i wysyła główny formularz? Najpierw sprawdź strony związane z zapytaniami, rezerwacjami i obsługą klienta.", "Stosuj prosty język, opisowe nagłówki i logiczną kolejność. Ważne informacje nie powinny istnieć wyłącznie w obrazie, a elementy interfejsu muszą być wyraźne także po powiększeniu tekstu.", "Menu, linki, przyciski i pola formularzy powinny działać z klawiatury. Fokus musi być widoczny, a popupy i widgety nie mogą zatrzymywać użytkownika. Przejdź najważniejszą ścieżkę klawiszem Tab bez użycia myszy.", "Tekst alternatywny powinien przekazywać sens obrazu, jeśli obraz wnosi informację. Obrazy dekoracyjne nie powinny tworzyć zbędnego szumu. Teksty linków i przycisków powinny mówić, dokąd prowadzą lub co robią.", "Każde pole potrzebuje jasnej etykiety, a komunikat błędu powinien wyjaśniać, co poprawić. Nie polegaj wyłącznie na kolorze. Po wysłaniu pokaż potwierdzenie i następny krok. Testuj całość na telefonie i komputerze.", "Sprawdzaj dostępność po zmianach projektu, wtyczek, treści i formularzy. Automatyczne narzędzia pomagają znaleźć część problemów, ale nie zastępują ludzkiego testu. Websiteli może uwzględnić takie kontrole w [utrzymaniu strony](/en/services/website-maintenance/) lub [redesignie](/en/services/website-redesign/)."],
    faqs: [{ question: "Czym jest dostępność strony dla małej firmy?", answer: "To projektowanie i utrzymywanie strony tak, aby więcej osób mogło zrozumieć treść, poruszać się po niej i wykonywać ważne zadania." }, { question: "Co poprawić najpierw?", answer: "Bariery w nawigacji, formularzach kontaktowych, rezerwacjach i innych kluczowych ścieżkach." }, { question: "Czy automatyczny skan wystarczy?", answer: "Nie. Wykrywa tylko część problemów technicznych; potrzebny jest także test człowieka." }, { question: "Jak często sprawdzać dostępność?", answer: "Po ważnych zmianach i regularnie w ramach utrzymania strony." }],
  }),

  es: makeTranslation("es", {
    title: "Accesibilidad web para pequeñas empresas: checklist práctica",
    description: "Guía práctica para pequeñas empresas: mejora legibilidad, teclado, imágenes, formularios, estructura y pruebas de accesibilidad web.",
    category: "Calidad web", tags: ["accesibilidad web", "web pequeña empresa", "sitio accesible", "usabilidad web", "calidad web"], readingTime: "9 min de lectura", audience: "Pequeñas empresas que quieren que su web sea más fácil de entender y usar para más personas", excerpt: "La accesibilidad es calidad web práctica: contenido claro, navegación usable, formularios comprensibles y distintas formas de interactuar.",
    summary: ["Empieza por los recorridos clave del cliente.", "Texto legible y encabezados lógicos facilitan la comprensión.", "Las acciones importantes deben funcionar con teclado.", "Las imágenes informativas necesitan texto alternativo útil.", "Los formularios necesitan etiquetas, errores y confirmaciones claras."], takeaways: ["Prioriza los recorridos críticos.", "Prueba teclado, zoom y envíos reales.", "Usa enlaces descriptivos y encabezados semánticos.", "Trata la accesibilidad como trabajo continuo.", "Corrige primero los bloqueos de tareas importantes."], prompts: ["Convierte este artículo en una checklist de accesibilidad para mi web.", "Revisa el texto de mi página de inicio para detectar encabezados y enlaces poco claros.", "Crea un plan de QA priorizado para contacto y reservas."],
    headings: ["Empieza por el recorrido del cliente, no por la checklist", "Haz que texto y estructura sean fáciles de entender", "Permite navegar y actuar sin ratón", "Da suficiente significado a imágenes, botones y enlaces", "Haz comprensibles los formularios de principio a fin", "Incluye la accesibilidad en el mantenimiento habitual"],
    paragraphs: ["Empieza por tareas reales: ¿la persona entiende la oferta, encuentra el contacto, recorre la navegación y envía el formulario principal? Revisa primero las páginas vinculadas a consultas, reservas y soporte.", "Usa lenguaje claro, encabezados descriptivos y un orden lógico. No pongas información esencial solo dentro de imágenes y asegúrate de que los controles sigan siendo distinguibles con texto ampliado.", "Menús, enlaces, botones y campos deben poder usarse con teclado. El foco debe verse y ningún popup o widget debería atrapar a la persona. Recorre la ruta principal con la tecla Tab y sin ratón.", "El texto alternativo debe comunicar el propósito de una imagen cuando aporta información. Las imágenes decorativas no necesitan añadir ruido. Los textos de botones y enlaces deben explicar la acción o el destino en lugar de decir solo 'haz clic aquí'.", "Cada campo necesita una etiqueta clara y cada error debe explicar qué cambiar. No uses únicamente el color para indicar problemas. Después del envío, confirma la recepción y explica el siguiente paso. Prueba todo en móvil y escritorio.", "Repite las pruebas después de cambios de diseño, plugins, contenido o formularios. Las herramientas automáticas ayudan, pero no sustituyen una revisión humana. Websiteli puede incluir estas comprobaciones en [mantenimiento web](/en/services/website-maintenance/) o en un [rediseño](/en/services/website-redesign/)."],
    faqs: [{ question: "¿Qué es la accesibilidad web para una pequeña empresa?", answer: "Es diseñar y mantener la web para que más personas puedan entenderla, navegar y completar tareas importantes con diferentes formas de interacción." }, { question: "¿Qué debería corregir primero?", answer: "Las barreras en navegación, contacto, reservas, solicitudes y otros recorridos críticos." }, { question: "¿Basta un escaneo automático?", answer: "No. Detecta algunos problemas técnicos, pero también hace falta una prueba humana." }, { question: "¿Cada cuánto debo revisarla?", answer: "Después de cambios importantes y de forma recurrente durante el mantenimiento." }],
  }),

  fr: makeTranslation("fr", {
    title: "Accessibilité web pour petites entreprises : checklist pratique",
    description: "Guide pratique pour petites entreprises : lisibilité, clavier, images, formulaires, structure et tests d'accessibilité web.",
    category: "Qualité du site", tags: ["accessibilité web", "site petite entreprise", "site accessible", "ergonomie web", "qualité site"], readingTime: "9 min de lecture", audience: "Petites entreprises qui veulent rendre leur site plus facile à comprendre et à utiliser", excerpt: "L'accessibilité est une qualité web concrète : contenu clair, navigation utilisable, formulaires compréhensibles et plusieurs modes d'interaction.",
    summary: ["Commencez par les parcours clients essentiels.", "Un texte lisible et des titres logiques facilitent l'utilisation.", "Les actions importantes doivent fonctionner au clavier.", "Les images informatives ont besoin d'un texte alternatif utile.", "Les formulaires exigent des libellés, erreurs et confirmations clairs."], takeaways: ["Priorisez les parcours critiques.", "Testez clavier, zoom et vrais envois de formulaire.", "Utilisez des liens descriptifs et une structure logique.", "Traitez l'accessibilité comme une qualité continue.", "Corrigez d'abord les obstacles qui bloquent une action importante."], prompts: ["Transforme cet article en checklist d'accessibilité pour mon site.", "Analyse ma page d'accueil pour repérer les titres et liens ambigus.", "Crée un plan QA priorisé pour les parcours de contact et réservation."],
    headings: ["Commencer par le parcours client, pas par la checklist", "Rendre le texte et la structure faciles à comprendre", "Permettre la navigation et les actions sans souris", "Donner assez de sens aux images, boutons et liens", "Rendre les formulaires compréhensibles de bout en bout", "Intégrer l'accessibilité à la maintenance régulière"],
    paragraphs: ["Partez de tâches réelles : la personne comprend-elle l'offre, trouve-t-elle le contact, parcourt-elle la navigation et peut-elle envoyer le formulaire principal ? Vérifiez d'abord les pages liées aux demandes, réservations et au support.", "Utilisez un langage clair, des titres descriptifs et une hiérarchie logique. Les informations essentielles ne doivent pas exister uniquement dans une image et les contrôles doivent rester distinguables lorsque le texte est agrandi.", "Menus, liens, boutons et champs doivent être utilisables au clavier. Le focus doit rester visible et aucun popup ne devrait bloquer la navigation. Testez le parcours principal avec la touche Tab sans utiliser la souris.", "Le texte alternatif doit transmettre le rôle d'une image lorsqu'elle apporte une information. Les images décoratives ne doivent pas ajouter de bruit. Les liens et boutons doivent annoncer clairement leur destination ou leur action.", "Chaque champ a besoin d'un libellé clair et les erreurs doivent expliquer quoi corriger. Ne comptez pas uniquement sur la couleur. Après l'envoi, confirmez la réception et expliquez la suite. Testez sur mobile et ordinateur.", "Refaites ces contrôles après des changements de design, plugins, contenu ou formulaires. Les outils automatiques sont utiles mais ne remplacent pas un test humain. Websiteli peut intégrer ces vérifications à la [maintenance](/en/services/website-maintenance/) ou à une [refonte](/en/services/website-redesign/)."],
    faqs: [{ question: "Qu'est-ce que l'accessibilité web pour une petite entreprise ?", answer: "C'est concevoir et maintenir le site afin que davantage de personnes puissent comprendre, naviguer et réaliser les actions essentielles." }, { question: "Que faut-il corriger d'abord ?", answer: "Les obstacles dans la navigation, les formulaires, réservations et autres parcours critiques." }, { question: "Un scan automatique suffit-il ?", answer: "Non. Il détecte certains problèmes techniques, mais un test humain reste indispensable." }, { question: "À quelle fréquence vérifier ?", answer: "Après les changements importants et régulièrement dans la maintenance." }],
  }),

  it: makeTranslation("it", {
    title: "Accessibilità web per piccole imprese: checklist pratica",
    description: "Guida pratica per piccole imprese: leggibilità, tastiera, immagini, moduli, struttura e test di accessibilità del sito.",
    category: "Qualità del sito", tags: ["accessibilità web", "sito piccola impresa", "sito accessibile", "usabilità web", "qualità sito"], readingTime: "9 min di lettura", audience: "Piccole imprese che vogliono rendere il sito più facile da capire e usare", excerpt: "L'accessibilità è qualità web concreta: contenuti chiari, navigazione usabile, moduli comprensibili e più modi di interagire.",
    summary: ["Parti dai percorsi cliente principali.", "Testo leggibile e titoli logici facilitano l'uso.", "Le azioni importanti devono funzionare da tastiera.", "Le immagini informative richiedono un testo alternativo utile.", "I moduli hanno bisogno di etichette, errori e conferme chiari."], takeaways: ["Dai priorità ai percorsi critici.", "Prova tastiera, zoom e invii reali.", "Usa link descrittivi e titoli logici.", "Tratta l'accessibilità come qualità continua.", "Correggi prima i problemi che bloccano un'azione importante."], prompts: ["Trasforma questo articolo in una checklist di accessibilità per il mio sito.", "Rivedi la homepage per titoli e link poco chiari.", "Crea un piano QA prioritario per contatti e prenotazioni."],
    headings: ["Parti dal percorso del cliente, non dalla checklist", "Rendi testo e struttura facili da capire", "Permetti navigazione e azioni senza mouse", "Dai significato a immagini, pulsanti e link", "Rendi i moduli comprensibili dall'inizio alla fine", "Integra l'accessibilità nella manutenzione ordinaria"],
    paragraphs: ["Inizia da compiti reali: il visitatore capisce l'offerta, trova il contatto, usa la navigazione e invia il modulo principale? Controlla prima le pagine legate a richieste, prenotazioni e assistenza.", "Usa linguaggio chiaro, titoli descrittivi e un ordine logico. Le informazioni essenziali non devono essere solo dentro immagini e i controlli devono restare riconoscibili anche con testo ingrandito.", "Menu, link, pulsanti e campi devono essere utilizzabili da tastiera. Il focus deve essere visibile e popup o widget non devono intrappolare l'utente. Prova il percorso principale con Tab senza mouse.", "Il testo alternativo deve comunicare il significato di un'immagine quando porta informazione. Le immagini decorative non devono creare rumore. Link e pulsanti devono descrivere azione o destinazione.", "Ogni campo richiede un'etichetta chiara e gli errori devono spiegare cosa cambiare. Non usare solo il colore. Dopo l'invio, conferma la ricezione e indica il passo successivo. Prova su mobile e desktop.", "Ripeti i controlli dopo modifiche a design, plugin, contenuti o moduli. Gli strumenti automatici aiutano ma non sostituiscono una verifica umana. Websiteli può includere questi controlli nella [manutenzione](/en/services/website-maintenance/) o in un [redesign](/en/services/website-redesign/)."],
    faqs: [{ question: "Cos'è l'accessibilità web per una piccola impresa?", answer: "È progettare e mantenere il sito in modo che più persone possano capirlo, navigarlo e completare attività importanti." }, { question: "Cosa correggere prima?", answer: "Gli ostacoli nella navigazione, nei moduli, nelle prenotazioni e nei percorsi critici." }, { question: "Basta uno scan automatico?", answer: "No. Trova alcuni problemi tecnici, ma serve anche una verifica umana." }, { question: "Quanto spesso controllare?", answer: "Dopo cambiamenti importanti e regolarmente durante la manutenzione." }],
  }),

  cz: makeTranslation("cz", {
    title: "Přístupnost webu pro malé firmy: praktický checklist",
    description: "Praktický průvodce pro malé firmy: čitelnost, ovládání klávesnicí, obrázky, formuláře, struktura a testování přístupnosti webu.",
    category: "Kvalita webu", tags: ["přístupnost webu", "web malé firmy", "přístupný web", "použitelnost webu", "kvalita webu"], readingTime: "9 min čtení", audience: "Malé firmy, které chtějí zpřístupnit svůj web většímu počtu lidí", excerpt: "Přístupnost je praktická kvalita webu: jasný obsah, použitelná navigace, srozumitelné formuláře a více způsobů ovládání.",
    summary: ["Začněte klíčovými cestami zákazníka.", "Čitelný text a logické nadpisy usnadňují používání.", "Důležité akce musí fungovat z klávesnice.", "Informační obrázky potřebují smysluplný alternativní text.", "Formuláře potřebují jasné popisky, chyby a potvrzení."], takeaways: ["Nejdříve opravte kritické cesty.", "Testujte klávesnicí, zoomem a skutečným odesláním formuláře.", "Používejte popisné odkazy a logické nadpisy.", "Přístupnost řešte průběžně.", "Prioritou jsou bariéry, které blokují důležitou akci."], prompts: ["Převeď tento článek na checklist přístupnosti pro můj web.", "Zkontroluj text homepage kvůli nejasným nadpisům a odkazům.", "Vytvoř prioritizovaný QA plán pro kontakt a rezervace."],
    headings: ["Začněte cestou zákazníka, ne checklistem", "Usnadněte pochopení textu a struktury", "Umožněte navigaci a akce bez myši", "Dejte obrázkům, tlačítkům a odkazům dostatek významu", "Zpřehledněte formuláře od začátku do konce", "Zařaďte přístupnost do běžné údržby webu"],
    paragraphs: ["Začněte reálnými úkoly: rozumí návštěvník nabídce, najde kontakt, projde navigací a odešle hlavní formulář? Nejprve kontrolujte stránky spojené s poptávkami, rezervacemi a podporou.", "Používejte jasný jazyk, popisné nadpisy a logické pořadí. Důležité informace nemají být pouze v obrázcích a ovládací prvky musí zůstat rozpoznatelné i při zvětšení textu.", "Menu, odkazy, tlačítka a pole musí být použitelné klávesnicí. Fokus má být viditelný a popup nesmí uživatele uvěznit. Projděte hlavní cestu klávesou Tab bez myši.", "Alternativní text má popsat smysl obrázku, pokud obrázek nese informaci. Dekorativní obrázky nemají přidávat zbytečný šum. Odkazy a tlačítka mají popsat akci nebo cíl.", "Každé pole potřebuje jasný popisek a chyba musí vysvětlit, co opravit. Nespoléhejte pouze na barvu. Po odeslání potvrďte přijetí a vysvětlete další krok. Testujte na mobilu i počítači.", "Kontroly opakujte po změnách designu, pluginů, obsahu či formulářů. Automatické nástroje pomáhají, ale nenahrazují lidské testování. Websiteli může kontroly zahrnout do [údržby webu](/en/services/website-maintenance/) nebo [redesignu](/en/services/website-redesign/)."],
    faqs: [{ question: "Co je přístupnost webu pro malou firmu?", answer: "Jde o návrh a údržbu webu tak, aby více lidí mohlo obsah pochopit, navigovat a dokončit důležité úkoly." }, { question: "Co opravit jako první?", answer: "Překážky v navigaci, kontaktech, rezervacích a dalších kritických cestách." }, { question: "Stačí automatický sken?", answer: "Ne. Najde jen část technických problémů; nutný je i lidský test." }, { question: "Jak často kontrolovat?", answer: "Po důležitých změnách a pravidelně v rámci údržby." }],
  }),

  sk: makeTranslation("sk", {
    title: "Prístupnosť webu pre malé firmy: praktický checklist",
    description: "Praktický návod pre malé firmy: čitateľnosť, klávesnica, obrázky, formuláre, štruktúra a testovanie prístupnosti webu.",
    category: "Kvalita webu", tags: ["prístupnosť webu", "web malej firmy", "prístupný web", "použiteľnosť webu", "kvalita webu"], readingTime: "9 min čítania", audience: "Malé firmy, ktoré chcú sprístupniť svoj web väčšiemu počtu ľudí", excerpt: "Prístupnosť je praktická kvalita webu: jasný obsah, použiteľná navigácia, zrozumiteľné formuláre a viac spôsobov ovládania.",
    summary: ["Začnite kľúčovými cestami zákazníka.", "Čitateľný text a logické nadpisy uľahčujú používanie.", "Dôležité akcie musia fungovať klávesnicou.", "Informačné obrázky potrebujú zmysluplný alternatívny text.", "Formuláre potrebujú jasné popisy, chyby a potvrdenia."], takeaways: ["Najprv opravte kritické cesty.", "Testujte klávesnicou, zoomom a skutočným odoslaním formulára.", "Používajte popisné odkazy a logické nadpisy.", "Prístupnosť riešte priebežne.", "Prioritou sú bariéry blokujúce dôležitú akciu."], prompts: ["Premeň tento článok na checklist prístupnosti pre môj web.", "Skontroluj text homepage kvôli nejasným nadpisom a odkazom.", "Vytvor prioritizovaný QA plán pre kontakt a rezervácie."],
    headings: ["Začnite cestou zákazníka, nie checklistom", "Uľahčite pochopenie textu a štruktúry", "Umožnite navigáciu a akcie bez myši", "Dajte obrázkom, tlačidlám a odkazom dosť významu", "Spravte formuláre zrozumiteľné od začiatku do konca", "Zaraďte prístupnosť do bežnej údržby webu"],
    paragraphs: ["Začnite reálnymi úlohami: rozumie návštevník ponuke, nájde kontakt, prejde navigáciou a odošle hlavný formulár? Najskôr kontrolujte stránky spojené s dopytmi, rezerváciami a podporou.", "Používajte jasný jazyk, popisné nadpisy a logické poradie. Dôležité informácie nemajú byť iba v obrázkoch a ovládacie prvky musia zostať rozpoznateľné aj pri zväčšení textu.", "Menu, odkazy, tlačidlá a polia musia byť použiteľné klávesnicou. Fokus má byť viditeľný a popup nesmie používateľa uväzniť. Prejdite hlavnú cestu klávesom Tab bez myši.", "Alternatívny text má popísať význam obrázka, ak obrázok nesie informáciu. Dekoratívne obrázky nemajú pridávať zbytočný šum. Odkazy a tlačidlá majú pomenovať akciu alebo cieľ.", "Každé pole potrebuje jasný popis a chyba musí vysvetliť, čo opraviť. Nespoliehajte sa iba na farbu. Po odoslaní potvrďte prijatie a vysvetlite ďalší krok. Testujte na mobile aj počítači.", "Kontroly opakujte po zmenách dizajnu, pluginov, obsahu či formulárov. Automatické nástroje pomáhajú, ale nenahrádzajú ľudský test. Websiteli môže kontroly zaradiť do [údržby webu](/en/services/website-maintenance/) alebo [redizajnu](/en/services/website-redesign/)."],
    faqs: [{ question: "Čo je prístupnosť webu pre malú firmu?", answer: "Je to návrh a údržba webu tak, aby viac ľudí mohlo obsah pochopiť, navigovať a dokončiť dôležité úlohy." }, { question: "Čo opraviť ako prvé?", answer: "Prekážky v navigácii, kontaktoch, rezerváciách a ďalších kritických cestách." }, { question: "Stačí automatický sken?", answer: "Nie. Nájde iba časť technických problémov; potrebný je aj ľudský test." }, { question: "Ako často kontrolovať?", answer: "Po dôležitých zmenách a pravidelne v rámci údržby." }],
  }),

  pt: makeTranslation("pt", {
    title: "Acessibilidade web para pequenas empresas: checklist prática",
    description: "Guia prático para pequenas empresas: legibilidade, teclado, imagens, formulários, estrutura e testes de acessibilidade do website.",
    category: "Qualidade do website", tags: ["acessibilidade web", "website pequena empresa", "site acessível", "usabilidade web", "qualidade website"], readingTime: "9 min de leitura", audience: "Pequenas empresas que querem tornar o website mais fácil de compreender e usar", excerpt: "A acessibilidade é qualidade web prática: conteúdo claro, navegação utilizável, formulários compreensíveis e diferentes formas de interação.",
    summary: ["Começa pelos percursos principais do cliente.", "Texto legível e títulos lógicos facilitam a utilização.", "As ações importantes devem funcionar com teclado.", "Imagens informativas precisam de texto alternativo útil.", "Formulários precisam de etiquetas, erros e confirmações claras."], takeaways: ["Prioriza os percursos críticos.", "Testa teclado, zoom e envios reais.", "Usa links descritivos e títulos lógicos.", "Trata a acessibilidade como qualidade contínua.", "Corrige primeiro os bloqueios de ações importantes."], prompts: ["Transforma este artigo numa checklist de acessibilidade para o meu website.", "Revê a homepage para identificar títulos e links pouco claros.", "Cria um plano QA priorizado para contacto e reservas."],
    headings: ["Começa pelo percurso do cliente, não pela checklist", "Facilita a compreensão do texto e da estrutura", "Permite navegar e agir sem rato", "Dá significado suficiente a imagens, botões e links", "Torna os formulários compreensíveis do início ao fim", "Inclui acessibilidade na manutenção regular"],
    paragraphs: ["Começa por tarefas reais: a pessoa entende a oferta, encontra o contacto, percorre a navegação e envia o formulário principal? Revê primeiro as páginas ligadas a pedidos, reservas e suporte.", "Usa linguagem clara, títulos descritivos e uma ordem lógica. A informação essencial não deve existir apenas em imagens e os controlos devem continuar distinguíveis com texto ampliado.", "Menus, links, botões e campos devem funcionar com teclado. O foco deve estar visível e nenhum popup deve prender o utilizador. Percorre o caminho principal com Tab e sem rato.", "O texto alternativo deve comunicar o objetivo de uma imagem quando ela transmite informação. Imagens decorativas não devem criar ruído. Links e botões devem descrever a ação ou o destino.", "Cada campo precisa de uma etiqueta clara e os erros devem explicar o que corrigir. Não uses apenas cor. Depois do envio, confirma a receção e explica o passo seguinte. Testa em móvel e desktop.", "Repete os testes após alterações de design, plugins, conteúdo ou formulários. Ferramentas automáticas ajudam, mas não substituem testes humanos. A Websiteli pode incluir estas verificações na [manutenção](/en/services/website-maintenance/) ou num [redesign](/en/services/website-redesign/)."],
    faqs: [{ question: "O que é acessibilidade web para uma pequena empresa?", answer: "É desenhar e manter o website para que mais pessoas consigam compreender, navegar e concluir tarefas importantes." }, { question: "O que devo corrigir primeiro?", answer: "Barreiras na navegação, contacto, reservas e outros percursos críticos." }, { question: "Um scan automático chega?", answer: "Não. Deteta alguns problemas técnicos, mas também é necessário teste humano." }, { question: "Com que frequência devo testar?", answer: "Após alterações importantes e regularmente durante a manutenção." }],
  }),

  da: makeTranslation("da", {
    title: "Webtilgængelighed for små virksomheder: en praktisk tjekliste",
    description: "Praktisk guide til små virksomheder: læsbarhed, tastatur, billeder, formularer, struktur og test af webtilgængelighed.",
    category: "Websitekvalitet", tags: ["webtilgængelighed", "website til små virksomheder", "tilgængeligt website", "webbrugervenlighed", "websitekvalitet"], readingTime: "9 min. læsning", audience: "Små virksomheder, der vil gøre deres website lettere at forstå og bruge for flere mennesker", excerpt: "Tilgængelighed er praktisk websitekvalitet: klart indhold, brugbar navigation, forståelige formularer og flere måder at betjene siden på.",
    summary: ["Start med kundens vigtigste rejser.", "Læsbar tekst og logiske overskrifter gør siden lettere at bruge.", "Vigtige handlinger skal kunne udføres med tastatur.", "Informationsbærende billeder har brug for nyttig alternativ tekst.", "Formularer kræver tydelige labels, fejl og bekræftelser."], takeaways: ["Prioritér kritiske kunderejser.", "Test tastatur, zoom og rigtige formularindsendelser.", "Brug beskrivende links og logiske overskrifter.", "Behandl tilgængelighed som løbende kvalitet.", "Ret først problemer, der blokerer en vigtig handling."], prompts: ["Lav denne artikel om til en tilgængelighedstjekliste for mit website.", "Gennemgå min forside for uklare overskrifter og links.", "Lav en prioriteret QA-plan for kontakt og booking."],
    headings: ["Start med kunderejsen, ikke tjeklisten", "Gør tekst og struktur lette at forstå", "Gør navigation og handlinger mulige uden mus", "Giv billeder, knapper og links tydelig betydning", "Gør formularer forståelige fra start til slut", "Indbyg tilgængelighed i den normale vedligeholdelse"],
    paragraphs: ["Start med reelle opgaver: forstår den besøgende tilbuddet, finder kontakt, kan navigere og indsende hovedformularen? Gennemgå først sider, der er vigtige for henvendelser, bookinger og support.", "Brug klart sprog, beskrivende overskrifter og logisk rækkefølge. Vigtig information bør ikke kun ligge i billeder, og kontroller skal forblive tydelige, når teksten forstørres.", "Menuer, links, knapper og felter bør kunne bruges med tastatur. Fokus skal være synligt, og popup-vinduer må ikke fange brugeren. Test hovedforløbet med Tab uden mus.", "Alternativ tekst skal formidle billedets formål, når billedet indeholder information. Dekorative billeder bør ikke skabe unødig støj. Link- og knaptekst bør beskrive handling eller destination.", "Hvert felt behøver en tydelig label, og fejl skal forklare, hvad der skal rettes. Brug ikke kun farve. Efter indsendelse skal du bekræfte modtagelsen og forklare næste skridt. Test på mobil og desktop.", "Gentag kontrollen efter ændringer i design, plugins, indhold eller formularer. Automatiske værktøjer hjælper, men erstatter ikke menneskelig test. Websiteli kan inkludere dette i [websitevedligeholdelse](/en/services/website-maintenance/) eller [redesign](/en/services/website-redesign/)."],
    faqs: [{ question: "Hvad er webtilgængelighed for en lille virksomhed?", answer: "Det er at designe og vedligeholde websitet, så flere mennesker kan forstå, navigere og udføre vigtige opgaver." }, { question: "Hvad skal jeg rette først?", answer: "Barrierer i navigation, kontakt, booking og andre kritiske forløb." }, { question: "Er en automatisk scanning nok?", answer: "Nej. Den finder nogle tekniske problemer, men menneskelig test er også nødvendig." }, { question: "Hvor ofte bør det testes?", answer: "Efter vigtige ændringer og løbende som del af vedligeholdelsen." }],
  }),

  nl: makeTranslation("nl", {
    title: "Webtoegankelijkheid voor kleine bedrijven: praktische checklist",
    description: "Praktische gids voor kleine bedrijven: leesbaarheid, toetsenbord, afbeeldingen, formulieren, structuur en toegankelijkheidstests.",
    category: "Websitekwaliteit", tags: ["webtoegankelijkheid", "website klein bedrijf", "toegankelijke website", "website usability", "websitekwaliteit"], readingTime: "9 min leestijd", audience: "Kleine bedrijven die hun website voor meer mensen begrijpelijk en bruikbaar willen maken", excerpt: "Toegankelijkheid is praktische websitekwaliteit: duidelijke inhoud, bruikbare navigatie, begrijpelijke formulieren en meerdere manieren om een pagina te bedienen.",
    summary: ["Begin bij de belangrijkste klantreizen.", "Leesbare tekst en logische koppen maken pagina's makkelijker te gebruiken.", "Belangrijke acties moeten met het toetsenbord werken.", "Informatieve afbeeldingen hebben nuttige alternatieve tekst nodig.", "Formulieren hebben duidelijke labels, fouten en bevestigingen nodig."], takeaways: ["Prioriteer kritieke klantreizen.", "Test toetsenbord, zoom en echte formulierverzendingen.", "Gebruik beschrijvende links en logische koppen.", "Behandel toegankelijkheid als doorlopende kwaliteit.", "Los eerst blokkades in belangrijke taken op."], prompts: ["Maak van dit artikel een toegankelijkheidschecklist voor mijn website.", "Controleer mijn homepage op onduidelijke koppen en links.", "Maak een geprioriteerd QA-plan voor contact en boekingen."],
    headings: ["Begin bij de klantreis, niet bij de checklist", "Maak tekst en structuur makkelijk te begrijpen", "Maak navigatie en acties mogelijk zonder muis", "Geef afbeeldingen, knoppen en links voldoende betekenis", "Maak formulieren begrijpelijk van begin tot eind", "Neem toegankelijkheid op in normaal websiteonderhoud"],
    paragraphs: ["Begin met echte taken: begrijpt de bezoeker het aanbod, vindt die contact, kan die navigeren en het belangrijkste formulier versturen? Controleer eerst pagina's die belangrijk zijn voor aanvragen, boekingen en ondersteuning.", "Gebruik duidelijke taal, beschrijvende koppen en een logische volgorde. Belangrijke informatie hoort niet alleen in afbeeldingen te staan en bedieningselementen moeten herkenbaar blijven wanneer tekst wordt vergroot.", "Menu's, links, knoppen en velden moeten met een toetsenbord bruikbaar zijn. Focus moet zichtbaar blijven en popups mogen de gebruiker niet vasthouden. Test het hoofdpad met Tab zonder muis.", "Alternatieve tekst moet het doel van een afbeelding overbrengen wanneer die afbeelding informatie bevat. Decoratieve afbeeldingen hoeven geen extra ruis te creëren. Link- en knoptekst moet actie of bestemming beschrijven.", "Elk veld heeft een duidelijk label nodig en fouten moeten uitleggen wat moet veranderen. Gebruik niet alleen kleur. Bevestig na verzending de ontvangst en leg de volgende stap uit. Test op mobiel en desktop.", "Herhaal controles na wijzigingen in design, plugins, inhoud of formulieren. Automatische tools helpen, maar vervangen menselijke tests niet. Websiteli kan dit opnemen in [websiteonderhoud](/en/services/website-maintenance/) of een [website-redesign](/en/services/website-redesign/)."],
    faqs: [{ question: "Wat is webtoegankelijkheid voor een klein bedrijf?", answer: "Het is de website zo ontwerpen en onderhouden dat meer mensen de inhoud kunnen begrijpen, navigeren en belangrijke taken uitvoeren." }, { question: "Wat moet ik eerst oplossen?", answer: "Barrières in navigatie, contact, boekingen en andere kritieke klantreizen." }, { question: "Is een automatische scan genoeg?", answer: "Nee. Die vindt sommige technische problemen, maar menselijke tests blijven nodig." }, { question: "Hoe vaak moet ik testen?", answer: "Na belangrijke wijzigingen en regelmatig als onderdeel van onderhoud." }],
  }),

  ja: makeTranslation("ja", {
    title: "小規模事業者のためのウェブアクセシビリティ実践チェックリスト",
    description: "小規模事業者向けに、読みやすさ、キーボード操作、画像、フォーム、構造、アクセシビリティテストを実践的に整理します。",
    category: "ウェブサイト品質", tags: ["ウェブアクセシビリティ", "小規模事業者サイト", "アクセシブルなサイト", "ウェブユーザビリティ", "ウェブサイト品質"], readingTime: "約9分", audience: "より多くの人にとって分かりやすく使いやすいウェブサイトを目指す小規模事業者", excerpt: "アクセシビリティは実用的なサイト品質です。明確なコンテンツ、使えるナビゲーション、分かりやすいフォーム、複数の操作方法が重要です。",
    summary: ["重要な顧客導線から確認します。", "読みやすい文章と論理的な見出し構造が理解を助けます。", "重要な操作はキーボードでも実行できるようにします。", "意味を持つ画像には適切な代替テキストが必要です。", "フォームには明確なラベル、エラー説明、送信確認が必要です。"], takeaways: ["まず重要な導線を優先します。", "キーボード、拡大表示、実際のフォーム送信でテストします。", "説明的なリンク文言と論理的な見出しを使います。", "アクセシビリティを継続的な品質管理として扱います。", "重要な操作を妨げる問題から修正します。"], prompts: ["この記事を私のサイト向けアクセシビリティチェックリストにしてください。", "トップページの見出しやリンク文言が分かりにくくないか確認してください。", "問い合わせと予約導線の優先順位付きQA計画を作ってください。"],
    headings: ["チェックリストより顧客導線から始める", "文章と構造を分かりやすくする", "マウスなしでもナビゲーションと操作を可能にする", "画像・ボタン・リンクに十分な意味を持たせる", "フォームを最初から最後まで分かりやすくする", "通常のサイト保守にアクセシビリティを組み込む"],
    paragraphs: ["実際のタスクから始めます。訪問者はサービス内容を理解し、連絡先を見つけ、ナビゲーションを進み、主要フォームを送信できるでしょうか。問い合わせ、予約、サポートに直結するページから優先して確認します。", "明確な言葉、内容を表す見出し、論理的な順序を使います。重要な情報を画像だけに入れず、文字を拡大しても主要な操作要素が認識できる状態を保ちます。", "メニュー、リンク、ボタン、フォーム項目はキーボードでも操作できるようにします。フォーカス位置を見えるようにし、ポップアップなどで操作が止まらないようにします。Tabキーだけで主要導線を確認してください。", "画像が情報を伝える場合は、その目的が分かる代替テキストを付けます。装飾だけの画像は不要な説明を増やさないようにします。リンクやボタンの文言は『こちら』だけではなく、行き先や操作内容を示します。", "各項目には明確なラベルを付け、エラーは何を直せばよいか説明します。色だけに依存してエラーを示さないようにします。送信後は受付完了と次のステップを示し、スマートフォンとPCの両方で実際に送信テストを行います。", "デザイン、プラグイン、コンテンツ、フォームを変更したら重要導線を再確認します。自動ツールは役立ちますが、人が実際に操作して意味や流れを確認する代わりにはなりません。Websiteliでは[ウェブサイト保守](/en/services/website-maintenance/)や[リデザイン](/en/services/website-redesign/)の一部としてこうした確認を組み込めます。"],
    faqs: [{ question: "小規模事業者にとってウェブアクセシビリティとは何ですか？", answer: "より多くの人が内容を理解し、ナビゲーションし、重要なタスクを完了できるようにサイトを設計・保守することです。" }, { question: "何から直すべきですか？", answer: "ナビゲーション、問い合わせ、予約など、事業上重要な導線を妨げる問題から始めます。" }, { question: "自動スキャンだけで十分ですか？", answer: "十分ではありません。一部の技術的問題は見つけられますが、人による操作確認も必要です。" }, { question: "どのくらいの頻度で確認すべきですか？", answer: "重要な変更の後と、定期的な保守の一環として確認してください。" }],
  }),
} satisfies Record<LocaleCode, BlogPostTranslation>;

export default {
  slug: "website-accessibility-small-business",
  published: true,
  status: "published",
  publishDate: "2026-09-02",
  image: "/assets/blog/website-accessibility-small-business.webp",
  socialImage: "/assets/blog/website-accessibility-small-business-linkedin.jpg",
  imageAlt: "Website accessibility checklist graphic showing keyboard navigation, contrast, form labels, alt text and accessibility checks.",
  author: "Websiteli",
  date: "2026-09-02",
  updated: "2026-09-02",
  related: [
    "/en/services/business-websites/",
    "/en/services/website-maintenance/",
    "/en/services/website-redesign/",
    "/en/services-pricing/",
    "/en/contact/",
  ],
  translations,
} satisfies BlogPostSource;
