export type IndustryPage = {
  slug: string;
  title: string;
  description: string;
  challenges: string[];
  websiteRecommendations: string[];
  automationOpportunities: string[];
  aiOpportunities: string[];
  seoStrategy: string[];
  relatedServices: string[];
  demoIdea: string;
};

export const industries: IndustryPage[] = [
  {
    slug: "healthcare",
    title: "Healthcare Websites and Automation",
    description: "Websites, appointment flows, document handling and AI-assisted search for healthcare providers and clinics.",
    challenges: ["Patients need clear information before contacting the practice", "Appointments and forms create repetitive admin work", "Documents and FAQs are difficult to search"],
    websiteRecommendations: ["Clear service pages", "Mobile contact and appointment actions", "Trust, privacy and accessibility-first design"],
    automationOpportunities: ["Appointment reminders", "Patient intake forms", "Document routing", "Follow-up email workflows"],
    aiOpportunities: ["Internal knowledge search", "FAQ assistant with safe handoff", "Document classification", "Policy and procedure search"],
    seoStrategy: ["Location and specialty pages", "Structured FAQ content", "Fast mobile pages", "Clear schema for services"],
    relatedServices: ["business-websites", "appointment-automation", "document-automation", "knowledge-base-search"],
    demoIdea: "Clinic website with appointment request, intake form and internal FAQ search.",
  },
  {
    slug: "restaurants",
    title: "Restaurant Websites and Automation",
    description: "Mobile-first restaurant websites with menus, booking paths, local SEO, review proof and simple automation.",
    challenges: ["Menus and opening hours are hard to find", "Reservations depend on calls or manual messages", "Local search visibility is inconsistent"],
    websiteRecommendations: ["Menu and booking above the fold", "Google Maps and opening hours", "Photo-led mobile pages with fast loading"],
    automationOpportunities: ["Reservation requests", "Event inquiries", "Review follow-up", "Newsletter or offer emails"],
    aiOpportunities: ["FAQ assistant for opening hours and menu questions", "Review summary insights", "Content drafting for seasonal menus"],
    seoStrategy: ["Local restaurant keywords", "Menu schema where suitable", "Neighborhood pages", "Google Business Profile alignment"],
    relatedServices: ["business-websites", "appointment-automation", "email-automation", "seo-optimization"],
    demoIdea: "Restaurant website with menu, booking request, local SEO and review follow-up.",
  },
  {
    slug: "hotels",
    title: "Hotel Websites and Guest Automation",
    description: "Hotel and accommodation websites that support direct inquiries, guest information and operational workflows.",
    challenges: ["Guests compare many options quickly", "Information is spread across booking platforms", "Reception teams answer repeated questions"],
    websiteRecommendations: ["Room and amenity pages", "Direct inquiry CTA", "Local area content", "Multilingual structure"],
    automationOpportunities: ["Pre-arrival emails", "Guest request forms", "Review follow-up", "Housekeeping reports"],
    aiOpportunities: ["Guest FAQ assistant", "Internal document search", "Review insight summaries"],
    seoStrategy: ["Location and amenity keywords", "Multilingual metadata", "Local attractions content", "Structured business data"],
    relatedServices: ["multilingual-websites", "business-websites", "customer-support-ai", "email-automation"],
    demoIdea: "Boutique hotel site with multilingual room pages and guest FAQ automation.",
  },
  {
    slug: "construction",
    title: "Construction Websites and Workflow Systems",
    description: "Websites, quote flows, project dashboards and document workflows for construction and building companies.",
    challenges: ["Prospects need proof before requesting a quote", "Project updates move through scattered messages", "Documents and photos are hard to organize"],
    websiteRecommendations: ["Project galleries", "Service-area pages", "Quote request forms", "Trust and safety proof"],
    automationOpportunities: ["Quote intake", "Project status updates", "Document naming", "Photo and report workflows"],
    aiOpportunities: ["Document search", "Proposal drafting support", "Project note summaries"],
    seoStrategy: ["Service plus location pages", "Project case-study structure without fabricated metrics", "Local schema", "Image optimization"],
    relatedServices: ["business-websites", "workflow-systems", "document-automation", "dashboard-development"],
    demoIdea: "Construction website with quote intake and internal project status dashboard.",
  },
  {
    slug: "electricians",
    title: "Electrician Websites and Lead Automation",
    description: "Local websites and quote workflows for electricians that need more qualified service inquiries.",
    challenges: ["Emergency and non-emergency requests need different paths", "Service areas are unclear", "Phone-only lead handling loses context"],
    websiteRecommendations: ["Service pages by need", "Mobile call and quote CTAs", "Trust, licenses and service-area clarity"],
    automationOpportunities: ["Quote form routing", "Appointment reminders", "Lead source tracking", "Follow-up emails"],
    aiOpportunities: ["FAQ assistant for common service questions", "Lead triage summaries", "Internal knowledge search"],
    seoStrategy: ["Local service pages", "Emergency and planned-work keywords", "Google Business Profile support"],
    relatedServices: ["business-websites", "lead-generation", "appointment-automation", "seo-optimization"],
    demoIdea: "Electrician website with emergency CTA, quote form and automated follow-up.",
  },
  {
    slug: "plumbers",
    title: "Plumber Websites and Booking Automation",
    description: "Local plumber websites with fast mobile contact, service-area SEO and practical lead automation.",
    challenges: ["Urgent visitors need immediate contact", "Quote details are incomplete", "Local SEO competition is high"],
    websiteRecommendations: ["Mobile-first call and WhatsApp actions", "Service-area structure", "Clear emergency and planned-work paths"],
    automationOpportunities: ["Lead qualification forms", "Booking reminders", "Photo upload intake", "CRM updates"],
    aiOpportunities: ["Inquiry triage", "FAQ assistant", "Job note summaries"],
    seoStrategy: ["Service plus town pages", "FAQ content for common problems", "Fast pages and local schema"],
    relatedServices: ["business-websites", "lead-generation", "appointment-automation", "crm-automation"],
    demoIdea: "Plumber site with urgent contact, photo intake and CRM lead routing.",
  },
  {
    slug: "law-firms",
    title: "Law Firm Websites and Document Automation",
    description: "Credible legal websites, intake flows, document organization and internal AI search for law firms.",
    challenges: ["Prospects need clarity without legal overclaiming", "Intake context arrives inconsistently", "Documents are difficult to search and classify"],
    websiteRecommendations: ["Practice-area pages", "Careful trust signals", "Accessible contact flow", "Clear disclaimers"],
    automationOpportunities: ["Client intake forms", "Document classification", "Appointment follow-up", "CRM updates"],
    aiOpportunities: ["Internal document search", "Case note summaries", "Knowledge base assistant"],
    seoStrategy: ["Practice area plus location pages", "FAQ content", "Authoritative internal linking", "Schema for services"],
    relatedServices: ["business-websites", "document-intelligence", "client-portals", "knowledge-base-search"],
    demoIdea: "Law firm website with intake form and internal document search prototype.",
  },
  {
    slug: "consultants",
    title: "Consultant Websites and Lead Systems",
    description: "Consultant websites, booking funnels, thought-leadership pages and lead generation automation.",
    challenges: ["Expertise is hard to evaluate quickly", "LinkedIn attention does not become owned leads", "Booking requires manual messages"],
    websiteRecommendations: ["Positioning-led homepage", "Service and proof pages", "Booking CTA", "Newsletter capture"],
    automationOpportunities: ["Lead magnet delivery", "Booking reminders", "CRM updates", "Email nurture"],
    aiOpportunities: ["Content pipeline", "Internal knowledge assistant", "Proposal draft support"],
    seoStrategy: ["Service niche pages", "Comparison and problem-led articles", "Structured author credibility"],
    relatedServices: ["portfolio-websites", "lead-generation", "email-automation", "ai-content-pipelines"],
    demoIdea: "Consultant website with booking funnel, lead magnet and newsletter automation.",
  },
  {
    slug: "marketing-agencies",
    title: "Marketing Agency Websites and Automation",
    description: "Agency websites, client portals, dashboards and automation for reporting and operations.",
    challenges: ["Agency proof must be credible without overclaiming", "Client reporting is repetitive", "Project status lives across too many tools"],
    websiteRecommendations: ["Service pages by outcome", "Clear process", "Portfolio structure", "Lead qualification"],
    automationOpportunities: ["Client onboarding", "Report generation", "CRM automation", "Task routing"],
    aiOpportunities: ["Content pipelines", "Research assistants", "Client knowledge search", "Summary generation"],
    seoStrategy: ["Service-specific landing pages", "Niche case-study templates", "Content cluster strategy"],
    relatedServices: ["business-websites", "client-portals", "dashboard-development", "ai-content-pipelines"],
    demoIdea: "Agency website with lead qualification and client reporting dashboard.",
  },
  {
    slug: "photographers",
    title: "Photographer Websites and Booking Flows",
    description: "Portfolio websites, inquiry flows and automation for photographers and visual studios.",
    challenges: ["Social profiles do not show the full portfolio", "Inquiry details are incomplete", "Bookings and packages need clarity"],
    websiteRecommendations: ["Fast image galleries", "Package and style pages", "Inquiry form", "Mobile-first portfolio"],
    automationOpportunities: ["Inquiry qualification", "Booking reminders", "Gallery delivery emails", "CRM updates"],
    aiOpportunities: ["Content tagging", "FAQ assistant", "Email draft support"],
    seoStrategy: ["Location plus specialty pages", "Optimized image metadata", "Portfolio internal links"],
    relatedServices: ["portfolio-websites", "appointment-automation", "email-automation", "seo-optimization"],
    demoIdea: "Photography portfolio with package pages and inquiry automation.",
  },
  {
    slug: "architects",
    title: "Architect Websites and Project Portfolios",
    description: "Architecture portfolio websites, project pages, inquiry flows and document organization.",
    challenges: ["Project quality is hard to evaluate from scattered images", "Inquiries lack project context", "Documents and project notes are fragmented"],
    websiteRecommendations: ["Project portfolio structure", "Service and process pages", "Inquiry forms with project context"],
    automationOpportunities: ["Project inquiry routing", "Document folders", "Follow-up sequences", "Status dashboards"],
    aiOpportunities: ["Project note summaries", "Document search", "Content drafting for project pages"],
    seoStrategy: ["Architecture service and location pages", "Project schema where appropriate", "Image performance optimization"],
    relatedServices: ["portfolio-websites", "document-automation", "workflow-systems", "business-websites"],
    demoIdea: "Architecture portfolio with project pages and inquiry routing workflow.",
  },
  {
    slug: "fitness-studios",
    title: "Fitness Studio Websites and Member Automation",
    description: "Fitness websites with class information, bookings, local SEO and member communication automation.",
    challenges: ["Visitors need schedules and pricing quickly", "Class booking and reminders create admin work", "Local competition is strong"],
    websiteRecommendations: ["Schedule and membership pages", "Class booking CTA", "Mobile-first design", "Local proof"],
    automationOpportunities: ["Trial booking", "Class reminders", "Member onboarding", "Newsletter campaigns"],
    aiOpportunities: ["FAQ assistant", "Content pipeline for class updates", "Lead follow-up drafts"],
    seoStrategy: ["Local fitness keywords", "Class and service pages", "Google Business Profile support"],
    relatedServices: ["business-websites", "appointment-automation", "email-automation", "lead-generation"],
    demoIdea: "Fitness studio website with trial booking and class reminder automation.",
  },
  {
    slug: "beauty-salons",
    title: "Beauty Salon Websites and Booking Automation",
    description: "Beauty salon websites with services, booking flows, local SEO and customer follow-up.",
    challenges: ["Customers compare services on mobile", "Bookings need reminders", "Promotions and repeat visits require follow-up"],
    websiteRecommendations: ["Service and price pages", "Booking CTA", "Before/after gallery with consent", "Local trust signals"],
    automationOpportunities: ["Appointment reminders", "Review requests", "Customer rebooking emails", "Offer campaigns"],
    aiOpportunities: ["FAQ assistant", "Review insight summaries", "Content drafts for promotions"],
    seoStrategy: ["Treatment plus location pages", "FAQ content", "Google Business Profile alignment"],
    relatedServices: ["business-websites", "appointment-automation", "email-automation", "seo-optimization"],
    demoIdea: "Beauty salon website with booking, services and rebooking automation.",
  },
  {
    slug: "dentists",
    title: "Dentist Websites and Patient Automation",
    description: "Dental websites, appointment flows, patient intake and document automation for clinics.",
    challenges: ["Patients need clear service information", "Appointments and reminders consume admin time", "Forms and documents create repeated work"],
    websiteRecommendations: ["Treatment pages", "Emergency and routine appointment CTAs", "Accessibility and trust-focused layout"],
    automationOpportunities: ["Appointment reminders", "Intake forms", "Review requests", "Document routing"],
    aiOpportunities: ["Internal FAQ search", "Document classification", "Website FAQ assistant with handoff"],
    seoStrategy: ["Treatment plus city pages", "FAQ schema", "Google Business Profile support", "Fast mobile pages"],
    relatedServices: ["business-websites", "appointment-automation", "document-automation", "customer-support-ai"],
    demoIdea: "Dental practice website with appointment request and intake workflow.",
  },
  {
    slug: "veterinarians",
    title: "Veterinarian Websites and Clinic Automation",
    description: "Veterinary websites with appointment requests, service pages, client communication and document workflows.",
    challenges: ["Pet owners need urgent and routine information quickly", "Appointments and reminders are repetitive", "Records and forms create admin pressure"],
    websiteRecommendations: ["Service and emergency pages", "Appointment request flow", "Mobile contact actions", "Trust and care proof"],
    automationOpportunities: ["Appointment reminders", "Client intake", "Vaccination reminders", "Follow-up emails"],
    aiOpportunities: ["FAQ assistant", "Internal protocol search", "Document summaries"],
    seoStrategy: ["Local veterinary keywords", "Service pages", "FAQ content", "Google Business Profile alignment"],
    relatedServices: ["business-websites", "appointment-automation", "email-automation", "knowledge-base-search"],
    demoIdea: "Veterinary clinic website with appointment flow and reminder automation.",
  },
  {
    slug: "e-commerce",
    title: "E-commerce Websites and Automation",
    description: "Storefront improvements, product landing pages, analytics and automation for online shops.",
    challenges: ["Product pages do not explain value clearly", "Email follow-up is inconsistent", "Reporting is fragmented"],
    websiteRecommendations: ["Product landing pages", "Trust and delivery information", "Analytics and conversion tracking"],
    automationOpportunities: ["Email flows", "Inventory alerts", "Order reporting", "Review requests"],
    aiOpportunities: ["Product content support", "Support assistant", "Search and recommendation helpers"],
    seoStrategy: ["Product category pages", "Structured product content where appropriate", "Core Web Vitals", "Internal links"],
    relatedServices: ["ecommerce-websites", "email-automation", "dashboard-development", "customer-support-ai"],
    demoIdea: "E-commerce landing page with email flow and performance dashboard.",
  },
  {
    slug: "shopify-consultants",
    title: "Shopify Consultant Websites and Lead Generation",
    description: "Portfolio and lead generation websites for Shopify consultants, CRO specialists and e-commerce service providers.",
    challenges: ["Cold outreach needs a credible verification page", "Services and proof are scattered", "Leads need a clearer booking path"],
    websiteRecommendations: ["Portfolio proof", "Service pages", "Case-study templates", "Booking and lead capture"],
    automationOpportunities: ["Lead qualification", "Email follow-up", "CRM updates", "Proposal request intake"],
    aiOpportunities: ["Content pipeline", "Proposal draft support", "Internal knowledge assistant"],
    seoStrategy: ["Niche service pages", "Comparison and audit content", "Portfolio internal links"],
    relatedServices: ["portfolio-websites", "lead-generation", "crm-automation", "ai-content-pipelines"],
    demoIdea: "Shopify consultant portfolio with outreach trust page and lead capture.",
  },
  {
    slug: "freelancers",
    title: "Freelancer Websites and Automation",
    description: "Freelancer websites, portfolio systems, booking flows and lightweight automation for independent specialists.",
    challenges: ["Work is scattered across platforms", "Prospects cannot evaluate fit quickly", "Admin work steals billable time"],
    websiteRecommendations: ["Focused portfolio", "Offer pages", "Booking CTA", "Newsletter or lead magnet"],
    automationOpportunities: ["Inquiry forms", "Booking reminders", "Invoice workflows", "Client onboarding"],
    aiOpportunities: ["Content drafting", "Proposal support", "Knowledge assistant"],
    seoStrategy: ["Niche offer pages", "Portfolio content", "Local or international positioning depending on market"],
    relatedServices: ["portfolio-websites", "appointment-automation", "invoice-automation", "lead-generation"],
    demoIdea: "Freelancer portfolio with booking, lead form and invoice automation concept.",
  },
  {
    slug: "local-businesses",
    title: "Local Business Websites and Automation",
    description: "Local business websites, SEO foundations, lead capture and practical automation for day-to-day operations.",
    challenges: ["Customers cannot quickly understand services", "Local visibility depends too much on social profiles", "Manual follow-up is inconsistent"],
    websiteRecommendations: ["Clear homepage", "Service and location pages", "Mobile contact actions", "Trust signals"],
    automationOpportunities: ["Quote requests", "Appointment reminders", "Review follow-up", "CRM updates"],
    aiOpportunities: ["FAQ assistant", "Lead triage", "Document and email summaries"],
    seoStrategy: ["Service plus location pages", "Google Business Profile support", "FAQ content", "Structured data"],
    relatedServices: ["business-websites", "seo-optimization", "lead-generation", "business-automation"],
    demoIdea: "Local service website with quote form, local SEO and follow-up automation.",
  },
];

export const industrySlugs = industries.map((industry) => industry.slug);

export function getIndustryBySlug(slug: string | undefined) {
  return industries.find((industry) => industry.slug === slug);
}

export function getRelatedIndustries(currentSlug: string, limit = 4) {
  return industries.filter((industry) => industry.slug !== currentSlug).slice(0, limit);
}
