export type MarketScanLocale = "en" | "de" | "fr" | "it" | "es";

type DiagnosisCopy = {
  title: string;
  healthy: string;
  opportunity: string;
};

export type MarketScanContent = {
  meta: { title: string; description: string };
  eyebrow: string; title: string; intro: string; placeholder: string; button: string; scanning: string; note: string; error: string;
  summary: string; pages: string; buyer: string; reddit: string; reviews: string; competitors: string; content: string; ads: string; actions: string;
  scoreTitle: string; scoreNote: string; priorities: string; diagnostics: string; signals: string; pains: string; compTitle: string;
  redditTitle: string; reviewsTitle: string; contentTitle: string; adTitle: string; source: string; empty: string;
  reportTitle: string; reportIntro: string; preview: string; newsletterEyebrow: string; locksIn: string; locked: string; lockedText: string;
  email: string; subscribe: string; sending: string; consent: string; privacy: string; subscribed: string; subscribeError: string; subscribeValidation: string;
  ctaTitle: string; ctaText: string; cta: string; again: string; method: string;
  evidenceSnapshot: string; execEyebrow: string; execPositioning: string; execOpportunity: string; execConfidence: string; execSignals: string;
  demandCategory: string; customerVoiceCategory: string; competitionCategory: string; growthCategory: string;
  actionSummary: string; demandSummary: string; evidenceSummary: string; competitionSummary: string; growthSummary: string;
  pass: string; review: string; healthy: string; opportunities: string; diagnosisGood: string; diagnosisImprove: string;
  whyRelevant: string; clientImpact: string; priority: string; area: string; scanTime: string;
  includedLabel: string;
  tags: [string,string,string,string,string];
  map: {
    title: string; live: string; website: string; websiteSub: string; gaps: string; gapsSub: string;
    buyers: string; buyersSub: string; competitors: string; competitorsSub: string; reviews: string; reviewsSub: string;
    content: string; contentSub: string; ads: string; adsSub: string; crawl: string; discover: string; connect: string; prioritise: string;
  };
  actionCategories: { foundation: string; conversion: string; messaging: string; growth: string; other: string };
  diagnosis: Record<string, DiagnosisCopy>;
  seo: {
    heading: string; intro: string; whatTitle: string; whatText: string; signalsTitle: string; signals: string[];
    accuracyTitle: string; accuracyText: string; faqTitle: string;
    faqs: { question: string; answer: string }[];
  };
};

const diagnosisEn: Record<string, DiagnosisCopy> = {
  "Homepage title": { title:"Clear page titles", healthy:"Key pages use clear titles that are understandable to users and search engines.", opportunity:"Page titles could communicate the offer and value proposition more clearly." },
  "Meta description": { title:"Search descriptions in place", healthy:"Important pages include supporting descriptions for search visibility.", opportunity:"Some search descriptions are missing or could communicate more value." },
  "Clear H1 structure": { title:"Strong page structure", healthy:"The heading hierarchy looks clear and easy to scan.", opportunity:"The main message could be strengthened with a clearer heading structure." },
  "Conversion CTA": { title:"Visible conversion path", healthy:"Visitors are given a clear next step to take.", opportunity:"The primary call to action could be more obvious and more consistent." },
  "Lead capture": { title:"Lead capture is present", healthy:"The site offers clear ways for visitors to get in touch or convert.", opportunity:"Lead capture could be made more prominent or easier to use." },
  "Analytics": { title:"Tracking is in place", healthy:"Measurement appears to be set up, which supports data-driven optimisation.", opportunity:"Tracking should be added so important user actions can be measured." },
  "Structured data": { title:"Structured data", healthy:"Structured data appears to be present and can support search visibility.", opportunity:"Structured data appears to be missing and is a clear technical SEO opportunity." },
  "Mobile viewport": { title:"Mobile-ready setup", healthy:"The site appears technically prepared for mobile devices.", opportunity:"Mobile readiness should be improved for a smoother experience on smaller devices." },
  "Content depth": { title:"Enough content depth", healthy:"The sampled pages contain enough substantive content for a meaningful assessment.", opportunity:"The site is very thin; more focused content would give users and search engines more context." },
};

const en: MarketScanContent = {
  meta:{ title:"Free Website & Market Scan: SEO, Competitors and Buyer Signals | Websiteli", description:"Scan any public website for website fundamentals, SEO gaps, competitor candidates, buyer signals, public discussions, content opportunities and growth ideas. Free Market Scan by Websiteli." },
  eyebrow:"Free Market Scan", title:"Give us one URL. We’ll map your website and market.", intro:"A live crawl of your website plus public market, Reddit, competitor and review signals — with traceable sources instead of invented numbers.",
  placeholder:"yourbusiness.com", button:"Run my free scan", scanning:"Researching your market…", note:"Free · no card · sources linked · no login required", error:"The scan could not be completed.",
  summary:"Your Market Scan", pages:"Pages crawled", buyer:"Buyer signals", reddit:"Reddit discussions", reviews:"Review mentions", competitors:"Competitor candidates", content:"Content opportunities", ads:"Ad angles", actions:"Priorities",
  scoreTitle:"Website fundamentals score", scoreNote:"Transparent heuristic score based on 9 observable website signals — not a revenue promise.", priorities:"Priority action plan", diagnostics:"Website diagnosis", signals:"Buyer signals", pains:"Recurring pain points", compTitle:"Competitor candidates",
  redditTitle:"Reddit discussions", reviewsTitle:"Review mentions", contentTitle:"Content opportunities", adTitle:"Ad angles worth testing", source:"Open source", empty:"No sufficiently strong public signals were found for this section in the current scan.",
  reportTitle:"Your complete Market Scan", reportIntro:"Review the full report now. When the preview ends, you can have the complete Market Scan sent to your inbox.", preview:"Free report preview", newsletterEyebrow:"Full report", locksIn:"Report locks in", locked:"Your report preview has ended", lockedText:"Enter your email and we’ll send the complete Market Scan with every diagnosis, source, buyer signal, competitor, content opportunity and ad angle.",
  email:"Email", subscribe:"Send my full report", sending:"Sending your report…", consent:"I want my Market Scan report and Websiteli Growth Notes by email and accept the", privacy:"Privacy Policy", subscribed:"Sent — check your inbox. Your complete Market Scan is on its way.", subscribeError:"That didn’t work. Please try again.", subscribeValidation:"Enter a valid email and confirm consent.",
  ctaTitle:"Want Websiteli to implement the highest-impact fixes?", ctaText:"We can prioritise the opportunities and implement the website, SEO, tracking, ads or automation.", cta:"Book a 30-minute call", again:"Scan another website", method:"Public data providers can rate-limit automated requests. A zero count therefore does not always mean zero market activity.",
  evidenceSnapshot:"Executive summary", execEyebrow:"What actually matters", execPositioning:"Detected positioning", execOpportunity:"Biggest opportunity", execConfidence:"Positioning confidence", execSignals:"Relevant external signals",
  demandCategory:"Customer demand", customerVoiceCategory:"Customer voice", competitionCategory:"Competitive landscape", growthCategory:"Growth opportunities", actionSummary:"The most important next steps, organised by impact and focus area.", demandSummary:"What potential customers are actively looking for, asking about and struggling with.", evidenceSummary:"Public conversations and review mentions that support the market findings.", competitionSummary:"The alternatives and competitors that repeatedly surfaced in the research.", growthSummary:"Concrete content and campaign ideas derived from the market signals we found.",
  pass:"Healthy", review:"Opportunity", healthy:"Healthy", opportunities:"Opportunities", diagnosisGood:"The website fundamentals look strong overall, with the key structural elements in place.", diagnosisImprove:"The site looks solid overall, with a few clear opportunities to improve visibility and conversion.", whyRelevant:"Why this matters", clientImpact:"How this can help win clients", priority:"Priority", area:"Area", scanTime:"Scan time",
  includedLabel:"Included in the scan", tags:["Buyer intent","Competitors","Website gaps","Content ideas","Ad angles"],
  map:{ title:"What the scan connects", live:"Live research", website:"Your website", websiteSub:"One URL in", gaps:"Website gaps", gapsSub:"SEO · UX · conversion", buyers:"Buyer signals", buyersSub:"Questions · intent · demand", competitors:"Competitors", competitorsSub:"Alternatives · positioning", reviews:"Reddit & reviews", reviewsSub:"Pain points · language", content:"Content ideas", contentSub:"Topics · objections", ads:"Ad angles", adsSub:"Messages worth testing", crawl:"Crawl", discover:"Discover", connect:"Connect", prioritise:"Prioritise" },
  actionCategories:{foundation:"Visibility & foundation",conversion:"Conversion & UX",messaging:"Messaging & positioning",growth:"Growth & demand",other:"Other opportunities"},
  diagnosis:diagnosisEn,
  seo:{
    heading:"Free website and market analysis from one URL",
    intro:"Websiteli Market Scan combines a crawl of your public website with public market research. It is designed to help small businesses, founders and website owners understand what is working, what may be limiting conversions, and which external signals are relevant enough to investigate.",
    whatTitle:"What does the Market Scan analyse?", whatText:"The scan checks observable website fundamentals such as titles, descriptions, heading structure, calls to action, lead capture, analytics, structured data, mobile setup and content depth. For commercial sites, it also searches public sources for relevant buyer language, competitor candidates, review mentions and content opportunities.",
    signalsTitle:"What you can get from the report", signals:["A website fundamentals score based on observable checks","A prioritised action plan with reasons and client impact","Relevant public buyer and pain-point signals when evidence is strong enough","Competitor candidates and source links","Content and campaign opportunities grounded in the scan"],
    accuracyTitle:"How does Websiteli avoid made-up market data?", accuracyText:"The scanner prefers an empty section over an unrelated result. External findings must pass site-specific relevance filters, and source URLs are kept so you can verify them. Public search providers can still rate-limit requests, so zero results do not prove that no market activity exists.",
    faqTitle:"Market Scan FAQ",
    faqs:[
      {question:"Is the Websiteli Market Scan free?",answer:"Yes. You can run the scan and review the report preview without a credit card or login."},
      {question:"What website can I scan?",answer:"You can enter a public HTTP or HTTPS website. Private, local and non-public network addresses are blocked for security."},
      {question:"Does the score predict revenue?",answer:"No. The website fundamentals score is a transparent heuristic based on observable website checks; it is not a revenue or conversion-rate prediction."},
      {question:"Does the scan use real sources?",answer:"Yes. External findings include source URLs when available. Weak or irrelevant market findings are intentionally suppressed."},
    ]
  }
};

const de: MarketScanContent = {
  ...en,
  meta:{title:"Kostenloser Website- & Market Scan: SEO, Wettbewerber und Buyer Signals | Websiteli",description:"Analysiere eine öffentliche Website auf SEO-Grundlagen, Conversion-Lücken, Wettbewerber, Buyer Signals, öffentliche Diskussionen und Content-Chancen. Kostenloser Market Scan von Websiteli."},
  eyebrow:"Kostenloser Market Scan",title:"Eine URL. Wir analysieren Website und Markt.",intro:"Ein Live-Scan deiner Website plus öffentliche Markt-, Reddit-, Wettbewerber- und Review-Signale — mit nachvollziehbaren Quellen statt erfundenen Zahlen.",placeholder:"deinefirma.ch",button:"Kostenlosen Scan starten",scanning:"Wir recherchieren deinen Markt…",note:"Kostenlos · keine Karte · Quellen verlinkt · kein Login nötig",error:"Der Scan konnte nicht abgeschlossen werden.",
  summary:"Dein Market Scan",pages:"Seiten gecrawlt",buyer:"Buyer Signals",reddit:"Reddit-Diskussionen",reviews:"Review-Erwähnungen",competitors:"Wettbewerber-Kandidaten",content:"Content-Chancen",ads:"Ad Angles",actions:"Prioritäten",
  scoreTitle:"Website Fundamentals Score",scoreNote:"Transparenter Heuristik-Score aus 9 beobachtbaren Website-Signalen — kein Umsatzversprechen.",priorities:"Priorisierter Aktionsplan",diagnostics:"Website-Diagnose",signals:"Buyer Signals",pains:"Wiederkehrende Pain Points",compTitle:"Wettbewerber-Kandidaten",redditTitle:"Reddit-Diskussionen",reviewsTitle:"Review-Erwähnungen",contentTitle:"Content-Chancen",adTitle:"Ad Angles zum Testen",source:"Quelle öffnen",empty:"Für diesen Bereich wurden beim aktuellen Scan keine belastbaren öffentlichen Signale gefunden.",
  reportTitle:"Dein vollständiger Market Scan",reportIntro:"Prüfe jetzt den vollständigen Report. Wenn die Vorschau endet, kannst du dir den kompletten Market Scan kostenlos per E-Mail schicken lassen.",preview:"Kostenlose Report-Vorschau",newsletterEyebrow:"Vollständiger Report",locksIn:"Report wird gesperrt in",locked:"Deine Report-Vorschau ist abgelaufen",lockedText:"Gib deine E-Mail ein und wir schicken dir den vollständigen Market Scan mit allen Diagnosen, Quellen, Buyer Signals, Wettbewerbern, Content-Chancen und Ad Angles.",email:"E-Mail",subscribe:"Vollständigen Report senden",sending:"Report wird gesendet…",consent:"Ich möchte meinen Market-Scan-Report und Websiteli Growth Notes per E-Mail erhalten und akzeptiere die",privacy:"Datenschutzerklärung",subscribed:"Gesendet — prüfe deinen Posteingang. Dein vollständiger Market Scan ist unterwegs.",subscribeError:"Das hat nicht geklappt. Bitte versuche es erneut.",subscribeValidation:"Bitte gib eine gültige E-Mail ein und bestätige die Einwilligung.",
  ctaTitle:"Soll Websiteli die wichtigsten Punkte direkt umsetzen?",ctaText:"Wir priorisieren die Chancen und können Website, SEO, Tracking, Ads oder Automatisierung umsetzen.",cta:"30-Minuten-Call buchen",again:"Andere Website scannen",method:"Öffentliche Datenquellen können Rate-Limits haben. 0 Treffer bedeutet daher nicht automatisch, dass es keine Marktsignale gibt.",
  evidenceSnapshot:"Executive Summary",execEyebrow:"Was wirklich zählt",execPositioning:"Erkannte Positionierung",execOpportunity:"Größte Chance",execConfidence:"Positionierungs-Sicherheit",execSignals:"Belastbare externe Signale",demandCategory:"Kundennachfrage",customerVoiceCategory:"Kundenstimme",competitionCategory:"Wettbewerb",growthCategory:"Wachstumschancen",actionSummary:"Die wichtigsten nächsten Schritte, nach Wirkung und Themenbereich geordnet.",demandSummary:"Was potenzielle Kunden suchen, fragen und worüber sie sich beschweren.",evidenceSummary:"Öffentliche Gespräche und Reviews, die die Marktanalyse stützen.",competitionSummary:"Welche Alternativen und Wettbewerber in der Recherche wiederholt auftauchen.",growthSummary:"Konkrete Content- und Werbeansätze, die aus den gefundenen Signalen abgeleitet wurden.",pass:"Gesund",review:"Chance",healthy:"Gesund",opportunities:"Chancen",diagnosisGood:"Die Website ist strukturell solide. Die wichtigsten Grundlagen sind vorhanden.",diagnosisImprove:"Die Website ist insgesamt solide, mit einigen klaren Chancen für bessere Sichtbarkeit und Conversion.",whyRelevant:"Warum das relevant ist",clientImpact:"Wie das mehr Kunden bringen kann",priority:"Priorität",area:"Bereich",scanTime:"Scan-Zeit",
  includedLabel:"Im Scan enthalten",tags:["Kaufintention","Wettbewerber","Website-Lücken","Content-Ideen","Werbeansätze"],
  map:{title:"Was der Scan verbindet",live:"Live-Recherche",website:"Deine Website",websiteSub:"Eine URL genügt",gaps:"Website-Lücken",gapsSub:"SEO · UX · Conversion",buyers:"Buyer Signals",buyersSub:"Fragen · Intention · Nachfrage",competitors:"Wettbewerber",competitorsSub:"Alternativen · Positionierung",reviews:"Reddit & Reviews",reviewsSub:"Pain Points · Sprache",content:"Content-Ideen",contentSub:"Themen · Einwände",ads:"Ad Angles",adsSub:"Botschaften zum Testen",crawl:"Crawlen",discover:"Entdecken",connect:"Verbinden",prioritise:"Priorisieren"},
  actionCategories:{foundation:"Sichtbarkeit & Technik",conversion:"Conversion & UX",messaging:"Messaging & Positionierung",growth:"Wachstum & Nachfrage",other:"Weitere Chancen"},
  diagnosis:{
    "Homepage title":{title:"Klare Seitentitel",healthy:"Die wichtigsten Seiten verwenden klare Titel, die für Nutzer und Suchmaschinen verständlich sind.",opportunity:"Die Seitentitel könnten Angebot und Nutzen klarer kommunizieren."},
    "Meta description":{title:"Suchbeschreibungen vorhanden",healthy:"Wichtige Seiten enthalten unterstützende Beschreibungen für Suchergebnisse.",opportunity:"Einige Suchbeschreibungen fehlen oder könnten den Nutzen stärker vermitteln."},
    "Clear H1 structure":{title:"Klare Seitenstruktur",healthy:"Die Überschriften-Hierarchie wirkt klar und gut lesbar.",opportunity:"Die Hauptbotschaft könnte durch eine klarere Überschriften-Struktur stärker werden."},
    "Conversion CTA":{title:"Klarer Conversion-Pfad",healthy:"Besucher erhalten einen klaren nächsten Schritt.",opportunity:"Der primäre Call-to-Action könnte sichtbarer und konsistenter sein."},
    "Lead capture":{title:"Lead Capture vorhanden",healthy:"Die Website bietet klare Möglichkeiten zur Kontaktaufnahme oder Conversion.",opportunity:"Die Kontakt- oder Lead-Capture-Möglichkeiten könnten prominenter sein."},
    "Analytics":{title:"Tracking vorhanden",healthy:"Messung scheint eingerichtet zu sein und unterstützt datenbasierte Optimierung.",opportunity:"Tracking sollte ergänzt werden, damit wichtige Nutzeraktionen messbar werden."},
    "Structured data":{title:"Strukturierte Daten",healthy:"Strukturierte Daten sind vorhanden und können die Suchsichtbarkeit unterstützen.",opportunity:"Strukturierte Daten scheinen zu fehlen und sind eine klare technische SEO-Chance."},
    "Mobile viewport":{title:"Mobil optimiert",healthy:"Die Website ist technisch für mobile Geräte vorbereitet.",opportunity:"Die mobile Basis sollte verbessert werden, um die Nutzung auf kleinen Geräten zu stärken."},
    "Content depth":{title:"Ausreichende Inhaltstiefe",healthy:"Die analysierten Seiten enthalten genügend Substanz für eine aussagekräftige Bewertung.",opportunity:"Die Website ist sehr dünn; mehr fokussierte Inhalte würden Nutzern und Suchmaschinen mehr Kontext geben."},
  },
  seo:{heading:"Kostenlose Website- und Marktanalyse aus nur einer URL",intro:"Der Websiteli Market Scan verbindet einen Crawl deiner öffentlichen Website mit öffentlicher Marktrecherche. Er hilft Unternehmen und Website-Betreibern zu verstehen, was funktioniert, was Conversions bremsen kann und welche externen Signale relevant genug sind, um sie weiterzuverfolgen.",whatTitle:"Was analysiert der Market Scan?",whatText:"Der Scan prüft beobachtbare Website-Grundlagen wie Titel, Beschreibungen, Überschriftenstruktur, Calls-to-Action, Lead Capture, Analytics, strukturierte Daten, mobile Einrichtung und Content-Tiefe. Bei kommerziellen Websites sucht er zusätzlich öffentliche Quellen nach relevanter Buyer-Sprache, Wettbewerbern, Review-Erwähnungen und Content-Chancen.",signalsTitle:"Was du im Report erhältst",signals:["Website Fundamentals Score aus beobachtbaren Checks","Priorisierter Aktionsplan mit Begründung und Kundenwirkung","Öffentliche Buyer- und Pain-Point-Signale, wenn die Evidenz stark genug ist","Wettbewerber-Kandidaten mit Quellen","Content- und Kampagnenchancen aus dem Scan"],accuracyTitle:"Wie vermeidet Websiteli erfundene Marktdaten?",accuracyText:"Der Scanner zeigt lieber einen leeren Bereich als ein irrelevantes Ergebnis. Externe Funde müssen websitespezifische Relevanzfilter bestehen; Quellen-URLs bleiben erhalten. Öffentliche Suchanbieter können Anfragen begrenzen, deshalb beweisen 0 Ergebnisse nicht, dass es keine Marktaktivität gibt.",faqTitle:"Market-Scan-FAQ",faqs:[{question:"Ist der Websiteli Market Scan kostenlos?",answer:"Ja. Du kannst den Scan starten und die Report-Vorschau ohne Kreditkarte oder Login ansehen."},{question:"Welche Website kann ich scannen?",answer:"Du kannst eine öffentliche HTTP- oder HTTPS-Website eingeben. Private, lokale und nicht öffentliche Netzwerkadressen werden aus Sicherheitsgründen blockiert."},{question:"Sagt der Score Umsatz voraus?",answer:"Nein. Der Website Fundamentals Score ist eine transparente Heuristik aus beobachtbaren Website-Checks und keine Umsatz- oder Conversion-Prognose."},{question:"Verwendet der Scan echte Quellen?",answer:"Ja. Externe Ergebnisse enthalten Quellen-URLs, wenn verfügbar. Schwache oder irrelevante Marktergebnisse werden bewusst unterdrückt."}]}
};

const fr: MarketScanContent = {
  ...en,
  meta:{title:"Audit gratuit de site et analyse de marché : SEO, concurrents et signaux d’achat | Websiteli",description:"Analysez un site public : bases SEO, conversion, concurrents, signaux d’achat, discussions publiques et opportunités de contenu. Market Scan gratuit par Websiteli."},
  eyebrow:"Market Scan gratuit",title:"Une URL. Nous analysons votre site et votre marché.",intro:"Un crawl en direct de votre site, complété par des signaux publics de marché, Reddit, concurrents et avis — avec des sources vérifiables, sans chiffres inventés.",placeholder:"votreentreprise.ch",button:"Lancer mon scan gratuit",scanning:"Analyse de votre marché…",note:"Gratuit · sans carte · sources liées · sans compte",error:"Le scan n’a pas pu être terminé.",
  summary:"Votre Market Scan",pages:"Pages analysées",buyer:"Signaux d’achat",reddit:"Discussions Reddit",reviews:"Mentions d’avis",competitors:"Concurrents potentiels",content:"Opportunités de contenu",ads:"Angles publicitaires",actions:"Priorités",scoreTitle:"Score des fondamentaux du site",scoreNote:"Score heuristique transparent basé sur 9 signaux observables — ce n’est pas une promesse de revenus.",priorities:"Plan d’action prioritaire",diagnostics:"Diagnostic du site",signals:"Signaux d’achat",pains:"Freins récurrents",compTitle:"Concurrents potentiels",redditTitle:"Discussions Reddit",reviewsTitle:"Mentions d’avis",contentTitle:"Opportunités de contenu",adTitle:"Angles publicitaires à tester",source:"Ouvrir la source",empty:"Aucun signal public suffisamment solide n’a été trouvé pour cette section lors de ce scan.",
  reportTitle:"Votre Market Scan complet",reportIntro:"Consultez maintenant le rapport complet. À la fin de l’aperçu, vous pouvez recevoir gratuitement le Market Scan complet par e-mail.",preview:"Aperçu gratuit du rapport",newsletterEyebrow:"Rapport complet",locksIn:"Le rapport se verrouille dans",locked:"Votre aperçu est terminé",lockedText:"Saisissez votre e-mail pour recevoir le Market Scan complet avec diagnostics, sources, signaux d’achat, concurrents, opportunités de contenu et angles publicitaires.",email:"E-mail",subscribe:"Envoyer mon rapport complet",sending:"Envoi du rapport…",consent:"Je souhaite recevoir mon rapport Market Scan et les Websiteli Growth Notes par e-mail et j’accepte la",privacy:"Politique de confidentialité",subscribed:"Envoyé — consultez votre boîte de réception.",subscribeError:"Une erreur s’est produite. Réessayez.",subscribeValidation:"Saisissez un e-mail valide et confirmez votre consentement.",
  ctaTitle:"Vous voulez que Websiteli mette en œuvre les améliorations prioritaires ?",ctaText:"Nous pouvons prioriser les opportunités et mettre en œuvre le site, le SEO, le tracking, les campagnes ou l’automatisation.",cta:"Réserver un appel de 30 min",again:"Analyser un autre site",method:"Les sources publiques peuvent limiter les requêtes automatisées. Un résultat à zéro ne signifie donc pas forcément une absence d’activité sur le marché.",
  evidenceSnapshot:"Résumé exécutif",execEyebrow:"Ce qui compte vraiment",execPositioning:"Positionnement détecté",execOpportunity:"Plus grande opportunité",execConfidence:"Confiance du positionnement",execSignals:"Signaux externes pertinents",demandCategory:"Demande client",customerVoiceCategory:"Voix du client",competitionCategory:"Paysage concurrentiel",growthCategory:"Opportunités de croissance",actionSummary:"Les prochaines actions les plus importantes, classées par impact et domaine.",demandSummary:"Ce que les clients potentiels recherchent, demandent et trouvent difficile.",evidenceSummary:"Conversations publiques et mentions d’avis qui soutiennent l’analyse.",competitionSummary:"Alternatives et concurrents apparus de façon répétée dans la recherche.",growthSummary:"Idées concrètes de contenu et de campagnes dérivées des signaux trouvés.",pass:"Sain",review:"Opportunité",healthy:"Sain",opportunities:"Opportunités",diagnosisGood:"Les fondamentaux du site sont globalement solides.",diagnosisImprove:"Le site est globalement solide, avec plusieurs opportunités claires pour la visibilité et la conversion.",whyRelevant:"Pourquoi c’est important",clientImpact:"Comment cela peut aider à gagner des clients",priority:"Priorité",area:"Domaine",scanTime:"Temps du scan",
  includedLabel:"Inclus dans le scan",tags:["Intention d’achat","Concurrents","Lacunes du site","Idées de contenu","Angles publicitaires"],
  map:{title:"Ce que le scan relie",live:"Recherche en direct",website:"Votre site",websiteSub:"Une URL suffit",gaps:"Lacunes du site",gapsSub:"SEO · UX · conversion",buyers:"Signaux d’achat",buyersSub:"Questions · intention · demande",competitors:"Concurrents",competitorsSub:"Alternatives · positionnement",reviews:"Reddit & avis",reviewsSub:"Freins · langage",content:"Idées de contenu",contentSub:"Sujets · objections",ads:"Angles publicitaires",adsSub:"Messages à tester",crawl:"Crawler",discover:"Découvrir",connect:"Relier",prioritise:"Prioriser"},
  actionCategories:{foundation:"Visibilité & fondations",conversion:"Conversion & UX",messaging:"Message & positionnement",growth:"Croissance & demande",other:"Autres opportunités"},
  diagnosis:{
    "Homepage title":{title:"Titres de pages clairs",healthy:"Les pages principales utilisent des titres compréhensibles pour les visiteurs et les moteurs de recherche.",opportunity:"Les titres pourraient mieux communiquer l’offre et sa valeur."},
    "Meta description":{title:"Descriptions de recherche présentes",healthy:"Les pages importantes disposent de descriptions utiles pour la visibilité dans les résultats de recherche.",opportunity:"Certaines descriptions manquent ou pourraient mieux exprimer la valeur."},
    "Clear H1 structure":{title:"Structure de page claire",healthy:"La hiérarchie des titres est claire et facile à parcourir.",opportunity:"Le message principal gagnerait à utiliser une structure de titres plus claire."},
    "Conversion CTA":{title:"Parcours de conversion visible",healthy:"Les visiteurs disposent d’une prochaine étape claire.",opportunity:"L’appel à l’action principal pourrait être plus visible et cohérent."},
    "Lead capture":{title:"Capture de leads en place",healthy:"Le site propose des moyens clairs de prendre contact ou de convertir.",opportunity:"La capture de leads pourrait être plus visible ou plus simple."},
    "Analytics":{title:"Mesure en place",healthy:"La mesure semble configurée et permet une optimisation fondée sur les données.",opportunity:"Il faudrait ajouter du tracking pour mesurer les actions importantes."},
    "Structured data":{title:"Données structurées",healthy:"Des données structurées semblent présentes et peuvent soutenir la visibilité dans les moteurs de recherche.",opportunity:"Les données structurées semblent absentes, ce qui représente une opportunité SEO technique."},
    "Mobile viewport":{title:"Configuration mobile prête",healthy:"Le site semble techniquement préparé pour les appareils mobiles.",opportunity:"La configuration mobile devrait être améliorée pour une expérience plus fluide."},
    "Content depth":{title:"Profondeur de contenu suffisante",healthy:"Les pages analysées contiennent suffisamment de contenu substantiel pour une évaluation utile.",opportunity:"Le site est assez léger; davantage de contenu ciblé donnerait plus de contexte aux utilisateurs et aux moteurs de recherche."}
  },
  seo:{heading:"Analyse gratuite de site et de marché à partir d’une seule URL",intro:"Le Websiteli Market Scan combine le crawl d’un site public avec une recherche de marché publique. Il aide les PME, fondateurs et propriétaires de sites à comprendre les forces du site, les freins possibles à la conversion et les signaux externes qui méritent d’être vérifiés.",whatTitle:"Que vérifie le Market Scan ?",whatText:"Le scan vérifie les fondamentaux observables : titres, descriptions, structure des titres, appels à l’action, capture de leads, analytics, données structurées, mobile et profondeur du contenu. Pour les sites commerciaux, il recherche aussi des signaux d’achat, concurrents, mentions d’avis et opportunités de contenu dans des sources publiques.",signalsTitle:"Ce que contient le rapport",signals:["Score des fondamentaux basé sur des contrôles observables","Plan d’action priorisé avec justification et impact client","Signaux publics d’achat et de friction quand les preuves sont suffisantes","Concurrents potentiels avec liens vers les sources","Opportunités de contenu et de campagne issues du scan"],accuracyTitle:"Comment Websiteli évite-t-il les données de marché inventées ?",accuracyText:"Le scanner préfère une section vide à un résultat hors sujet. Les résultats externes doivent passer des filtres de pertinence propres au site, et les URL sources sont conservées pour vérification. Les fournisseurs publics peuvent limiter les requêtes, donc zéro résultat ne prouve pas l’absence d’activité.",faqTitle:"FAQ du Market Scan",faqs:[{question:"Le Websiteli Market Scan est-il gratuit ?",answer:"Oui. Vous pouvez lancer le scan et consulter l’aperçu sans carte bancaire ni compte."},{question:"Quel site puis-je analyser ?",answer:"Vous pouvez saisir un site public en HTTP ou HTTPS. Les adresses privées, locales ou non publiques sont bloquées pour des raisons de sécurité."},{question:"Le score prédit-il les revenus ?",answer:"Non. Le score est une heuristique transparente fondée sur des contrôles observables, pas une prévision de revenus ou de taux de conversion."},{question:"Le scan utilise-t-il de vraies sources ?",answer:"Oui. Les résultats externes conservent les URL sources lorsqu’elles sont disponibles. Les résultats faibles ou hors sujet sont volontairement écartés."}]}
};

const it: MarketScanContent = {
  ...en,
  meta:{title:"Analisi gratuita del sito e del mercato: SEO, concorrenti e segnali d’acquisto | Websiteli",description:"Analizza un sito pubblico per SEO, conversione, concorrenti, segnali d’acquisto, discussioni pubbliche e opportunità di contenuto. Market Scan gratuito di Websiteli."},
  eyebrow:"Market Scan gratuito",title:"Una URL. Analizziamo il tuo sito e il tuo mercato.",intro:"Un crawl live del sito più segnali pubblici di mercato, Reddit, concorrenti e recensioni — con fonti verificabili invece di numeri inventati.",placeholder:"latuaazienda.ch",button:"Avvia il mio scan gratuito",scanning:"Stiamo analizzando il mercato…",note:"Gratis · nessuna carta · fonti collegate · nessun login",error:"Impossibile completare lo scan.",
  summary:"Il tuo Market Scan",pages:"Pagine analizzate",buyer:"Segnali d’acquisto",reddit:"Discussioni Reddit",reviews:"Menzioni di recensioni",competitors:"Concorrenti potenziali",content:"Opportunità di contenuto",ads:"Angoli pubblicitari",actions:"Priorità",scoreTitle:"Punteggio fondamentali del sito",scoreNote:"Punteggio euristico trasparente basato su 9 segnali osservabili — non è una promessa di ricavi.",priorities:"Piano d’azione prioritario",diagnostics:"Diagnosi del sito",signals:"Segnali d’acquisto",pains:"Problemi ricorrenti",compTitle:"Concorrenti potenziali",redditTitle:"Discussioni Reddit",reviewsTitle:"Menzioni di recensioni",contentTitle:"Opportunità di contenuto",adTitle:"Angoli pubblicitari da testare",source:"Apri fonte",empty:"In questa sezione non sono stati trovati segnali pubblici abbastanza solidi.",
  reportTitle:"Il tuo Market Scan completo",reportIntro:"Consulta ora il report completo. Al termine dell’anteprima puoi ricevere gratuitamente il Market Scan completo via email.",preview:"Anteprima gratuita del report",newsletterEyebrow:"Report completo",locksIn:"Il report si blocca tra",locked:"L’anteprima del report è terminata",lockedText:"Inserisci l’email e ti invieremo il Market Scan completo con diagnosi, fonti, segnali d’acquisto, concorrenti, opportunità di contenuto e angoli pubblicitari.",email:"Email",subscribe:"Invia il report completo",sending:"Invio del report…",consent:"Voglio ricevere il Market Scan e le Websiteli Growth Notes via email e accetto la",privacy:"Privacy Policy",subscribed:"Inviato — controlla la tua casella email.",subscribeError:"Qualcosa non ha funzionato. Riprova.",subscribeValidation:"Inserisci un’email valida e conferma il consenso.",
  ctaTitle:"Vuoi che Websiteli implementi le correzioni a maggior impatto?",ctaText:"Possiamo prioritizzare le opportunità e implementare sito, SEO, tracking, campagne o automazione.",cta:"Prenota una call di 30 minuti",again:"Analizza un altro sito",method:"I fornitori di dati pubblici possono limitare le richieste automatiche. Un conteggio pari a zero non significa sempre assenza di attività di mercato.",
  evidenceSnapshot:"Sintesi esecutiva",execEyebrow:"Ciò che conta davvero",execPositioning:"Posizionamento rilevato",execOpportunity:"Opportunità principale",execConfidence:"Confidenza del posizionamento",execSignals:"Segnali esterni rilevanti",demandCategory:"Domanda dei clienti",customerVoiceCategory:"Voce del cliente",competitionCategory:"Scenario competitivo",growthCategory:"Opportunità di crescita",actionSummary:"Le azioni più importanti, ordinate per impatto e area.",demandSummary:"Cosa cercano, chiedono e trovano difficile i potenziali clienti.",evidenceSummary:"Conversazioni pubbliche e menzioni di recensioni che supportano l’analisi.",competitionSummary:"Alternative e concorrenti emersi ripetutamente nella ricerca.",growthSummary:"Idee concrete di contenuto e campagne derivate dai segnali trovati.",pass:"Solido",review:"Opportunità",healthy:"Solido",opportunities:"Opportunità",diagnosisGood:"I fondamentali del sito risultano complessivamente solidi.",diagnosisImprove:"Il sito è solido nel complesso, con alcune opportunità chiare per migliorare visibilità e conversione.",whyRelevant:"Perché è importante",clientImpact:"Come può aiutare ad acquisire clienti",priority:"Priorità",area:"Area",scanTime:"Tempo scan",
  includedLabel:"Incluso nello scan",tags:["Intento d’acquisto","Concorrenti","Lacune del sito","Idee di contenuto","Angoli pubblicitari"],
  map:{title:"Cosa collega lo scan",live:"Ricerca live",website:"Il tuo sito",websiteSub:"Una URL in ingresso",gaps:"Lacune del sito",gapsSub:"SEO · UX · conversione",buyers:"Segnali d’acquisto",buyersSub:"Domande · intento · domanda",competitors:"Concorrenti",competitorsSub:"Alternative · posizionamento",reviews:"Reddit & recensioni",reviewsSub:"Problemi · linguaggio",content:"Idee di contenuto",contentSub:"Temi · obiezioni",ads:"Angoli pubblicitari",adsSub:"Messaggi da testare",crawl:"Scansione",discover:"Scoperta",connect:"Connessione",prioritise:"Priorità"},
  actionCategories:{foundation:"Visibilità & fondamenta",conversion:"Conversione & UX",messaging:"Messaggio & posizionamento",growth:"Crescita & domanda",other:"Altre opportunità"},
  diagnosis:{
    "Homepage title":{title:"Titoli pagina chiari",healthy:"Le pagine principali usano titoli comprensibili per utenti e motori di ricerca.",opportunity:"I titoli potrebbero comunicare meglio l’offerta e il valore."},
    "Meta description":{title:"Descrizioni di ricerca presenti",healthy:"Le pagine importanti includono descrizioni utili per la visibilità nei risultati di ricerca.",opportunity:"Alcune descrizioni mancano o potrebbero comunicare più valore."},
    "Clear H1 structure":{title:"Struttura pagina chiara",healthy:"La gerarchia dei titoli è chiara e facile da scansionare.",opportunity:"Il messaggio principale potrebbe essere rafforzato con una struttura heading più chiara."},
    "Conversion CTA":{title:"Percorso di conversione visibile",healthy:"Ai visitatori viene proposto un passo successivo chiaro.",opportunity:"La call to action principale potrebbe essere più evidente e coerente."},
    "Lead capture":{title:"Raccolta lead presente",healthy:"Il sito offre modi chiari per contattare o convertire.",opportunity:"La raccolta lead potrebbe essere più visibile o più semplice da usare."},
    "Analytics":{title:"Tracking attivo",healthy:"La misurazione sembra configurata e supporta l’ottimizzazione basata sui dati.",opportunity:"Va aggiunto tracking per misurare le azioni importanti degli utenti."},
    "Structured data":{title:"Dati strutturati",healthy:"I dati strutturati sembrano presenti e possono supportare la visibilità in ricerca.",opportunity:"I dati strutturati sembrano assenti e rappresentano un’opportunità SEO tecnica."},
    "Mobile viewport":{title:"Configurazione mobile pronta",healthy:"Il sito sembra tecnicamente preparato per dispositivi mobili.",opportunity:"La configurazione mobile dovrebbe essere migliorata per un’esperienza più fluida."},
    "Content depth":{title:"Profondità contenuti sufficiente",healthy:"Le pagine analizzate contengono abbastanza contenuto sostanziale per una valutazione utile.",opportunity:"Il sito è piuttosto leggero; più contenuti mirati darebbero maggiore contesto a utenti e motori di ricerca."}
  },
  seo:{heading:"Analisi gratuita del sito e del mercato da una sola URL",intro:"Websiteli Market Scan combina il crawl di un sito pubblico con ricerca di mercato pubblica. Aiuta piccole imprese, founder e proprietari di siti a capire cosa funziona, cosa può limitare le conversioni e quali segnali esterni meritano approfondimento.",whatTitle:"Cosa analizza il Market Scan?",whatText:"Il tool verifica elementi osservabili del sito: titoli, descrizioni, struttura heading, call to action, raccolta lead, analytics, dati strutturati, mobile e profondità dei contenuti. Per siti commerciali cerca anche linguaggio degli acquirenti, concorrenti, recensioni e opportunità di contenuto in fonti pubbliche.",signalsTitle:"Cosa puoi ottenere dal report",signals:["Punteggio dei fondamentali basato su controlli osservabili","Piano d’azione prioritario con motivazioni e impatto sui clienti","Segnali pubblici di acquisto e problemi quando l’evidenza è sufficiente","Concorrenti potenziali con link alle fonti","Opportunità di contenuto e campagne derivate dallo scan"],accuracyTitle:"Come evita Websiteli dati di mercato inventati?",accuracyText:"Lo scanner preferisce una sezione vuota a un risultato non pertinente. I risultati esterni devono superare filtri di rilevanza specifici per il sito e le URL delle fonti vengono mantenute. I provider pubblici possono applicare rate limit, quindi zero risultati non dimostrano assenza di attività.",faqTitle:"FAQ Market Scan",faqs:[{question:"Il Websiteli Market Scan è gratuito?",answer:"Sì. Puoi avviare lo scan e vedere l’anteprima senza carta di credito o login."},{question:"Quale sito posso analizzare?",answer:"Puoi inserire un sito pubblico HTTP o HTTPS. Indirizzi privati, locali o non pubblici vengono bloccati per sicurezza."},{question:"Il punteggio prevede i ricavi?",answer:"No. È un’euristica trasparente basata su controlli osservabili, non una previsione di ricavi o conversioni."},{question:"Lo scan usa fonti reali?",answer:"Sì. I risultati esterni mantengono i link alle fonti quando disponibili; i risultati deboli o irrilevanti vengono esclusi."}]}
};

const es: MarketScanContent = {
  ...en,
  meta:{title:"Análisis gratis de web y mercado: SEO, competidores y señales de compra | Websiteli",description:"Analiza una web pública: SEO, conversión, competidores, señales de compra, conversaciones públicas y oportunidades de contenido. Market Scan gratis de Websiteli."},
  eyebrow:"Market Scan gratis",title:"Una URL. Analizamos tu web y tu mercado.",intro:"Un rastreo en directo de tu web más señales públicas de mercado, Reddit, competidores y reseñas — con fuentes verificables y sin cifras inventadas.",placeholder:"tuempresa.com",button:"Iniciar mi análisis gratis",scanning:"Analizando tu mercado…",note:"Gratis · sin tarjeta · fuentes enlazadas · sin registro",error:"No se pudo completar el análisis.",
  summary:"Tu Market Scan",pages:"Páginas analizadas",buyer:"Señales de compra",reddit:"Conversaciones en Reddit",reviews:"Menciones de reseñas",competitors:"Competidores potenciales",content:"Oportunidades de contenido",ads:"Ángulos publicitarios",actions:"Prioridades",scoreTitle:"Puntuación de fundamentos web",scoreNote:"Puntuación heurística transparente basada en 9 señales observables — no es una promesa de ingresos.",priorities:"Plan de acción prioritario",diagnostics:"Diagnóstico web",signals:"Señales de compra",pains:"Problemas recurrentes",compTitle:"Competidores potenciales",redditTitle:"Conversaciones en Reddit",reviewsTitle:"Menciones de reseñas",contentTitle:"Oportunidades de contenido",adTitle:"Ángulos publicitarios para probar",source:"Abrir fuente",empty:"No se encontraron señales públicas suficientemente sólidas para esta sección.",
  reportTitle:"Tu Market Scan completo",reportIntro:"Revisa ahora el informe completo. Cuando termine la vista previa, puedes recibir gratis el Market Scan completo por email.",preview:"Vista previa gratuita",newsletterEyebrow:"Informe completo",locksIn:"El informe se bloquea en",locked:"La vista previa ha terminado",lockedText:"Introduce tu email y te enviaremos el Market Scan completo con diagnósticos, fuentes, señales de compra, competidores, oportunidades de contenido y ángulos publicitarios.",email:"Email",subscribe:"Enviar mi informe completo",sending:"Enviando el informe…",consent:"Quiero recibir mi informe Market Scan y las Websiteli Growth Notes por email y acepto la",privacy:"Política de privacidad",subscribed:"Enviado — revisa tu bandeja de entrada.",subscribeError:"Algo salió mal. Inténtalo de nuevo.",subscribeValidation:"Introduce un email válido y confirma el consentimiento.",
  ctaTitle:"¿Quieres que Websiteli implemente las mejoras de mayor impacto?",ctaText:"Podemos priorizar las oportunidades e implementar web, SEO, tracking, campañas o automatización.",cta:"Reservar llamada de 30 min",again:"Analizar otra web",method:"Los proveedores de datos públicos pueden limitar solicitudes automatizadas. Un cero no siempre significa ausencia de actividad de mercado.",
  evidenceSnapshot:"Resumen ejecutivo",execEyebrow:"Lo que realmente importa",execPositioning:"Posicionamiento detectado",execOpportunity:"Mayor oportunidad",execConfidence:"Confianza del posicionamiento",execSignals:"Señales externas relevantes",demandCategory:"Demanda de clientes",customerVoiceCategory:"Voz del cliente",competitionCategory:"Panorama competitivo",growthCategory:"Oportunidades de crecimiento",actionSummary:"Los próximos pasos más importantes, organizados por impacto y área.",demandSummary:"Qué buscan, preguntan y qué dificultades tienen los clientes potenciales.",evidenceSummary:"Conversaciones públicas y menciones de reseñas que respaldan los hallazgos.",competitionSummary:"Alternativas y competidores que aparecieron repetidamente en la investigación.",growthSummary:"Ideas concretas de contenido y campañas derivadas de las señales encontradas.",pass:"Correcto",review:"Oportunidad",healthy:"Correcto",opportunities:"Oportunidades",diagnosisGood:"Los fundamentos de la web parecen sólidos en general.",diagnosisImprove:"La web parece sólida, con varias oportunidades claras para mejorar visibilidad y conversión.",whyRelevant:"Por qué importa",clientImpact:"Cómo puede ayudar a conseguir clientes",priority:"Prioridad",area:"Área",scanTime:"Tiempo del análisis",
  includedLabel:"Incluido en el análisis",tags:["Intención de compra","Competidores","Problemas web","Ideas de contenido","Ángulos publicitarios"],
  map:{title:"Qué conecta el análisis",live:"Investigación en directo",website:"Tu web",websiteSub:"Una URL de entrada",gaps:"Problemas web",gapsSub:"SEO · UX · conversión",buyers:"Señales de compra",buyersSub:"Preguntas · intención · demanda",competitors:"Competidores",competitorsSub:"Alternativas · posicionamiento",reviews:"Reddit y reseñas",reviewsSub:"Problemas · lenguaje",content:"Ideas de contenido",contentSub:"Temas · objeciones",ads:"Ángulos publicitarios",adsSub:"Mensajes para probar",crawl:"Rastrear",discover:"Descubrir",connect:"Conectar",prioritise:"Priorizar"},
  actionCategories:{foundation:"Visibilidad y fundamentos",conversion:"Conversión y UX",messaging:"Mensaje y posicionamiento",growth:"Crecimiento y demanda",other:"Otras oportunidades"},
  diagnosis:{
    "Homepage title":{title:"Títulos de página claros",healthy:"Las páginas principales usan títulos comprensibles para usuarios y buscadores.",opportunity:"Los títulos podrían comunicar mejor la oferta y su valor."},
    "Meta description":{title:"Descripciones de búsqueda presentes",healthy:"Las páginas importantes incluyen descripciones útiles para la visibilidad en buscadores.",opportunity:"Faltan algunas descripciones o podrían comunicar mejor el valor."},
    "Clear H1 structure":{title:"Estructura de página clara",healthy:"La jerarquía de encabezados es clara y fácil de recorrer.",opportunity:"El mensaje principal podría reforzarse con una estructura de encabezados más clara."},
    "Conversion CTA":{title:"Ruta de conversión visible",healthy:"Los visitantes tienen un siguiente paso claro.",opportunity:"La llamada a la acción principal podría ser más visible y coherente."},
    "Lead capture":{title:"Captación de leads presente",healthy:"La web ofrece formas claras de contactar o convertir.",opportunity:"La captación de leads podría ser más visible o fácil de usar."},
    "Analytics":{title:"Medición configurada",healthy:"La medición parece estar configurada y permite optimizar con datos.",opportunity:"Conviene añadir tracking para medir acciones importantes."},
    "Structured data":{title:"Datos estructurados",healthy:"Los datos estructurados parecen estar presentes y pueden apoyar la visibilidad en buscadores.",opportunity:"Los datos estructurados parecen faltar y son una oportunidad SEO técnica."},
    "Mobile viewport":{title:"Configuración móvil preparada",healthy:"La web parece técnicamente preparada para dispositivos móviles.",opportunity:"La configuración móvil debería mejorar para una experiencia más fluida."},
    "Content depth":{title:"Profundidad de contenido suficiente",healthy:"Las páginas analizadas tienen suficiente contenido sustancial para una evaluación útil.",opportunity:"La web tiene poco contenido; más contenido enfocado daría mayor contexto a usuarios y buscadores."}
  },
  seo:{heading:"Análisis gratuito de web y mercado a partir de una sola URL",intro:"Websiteli Market Scan combina el rastreo de una web pública con investigación pública de mercado. Ayuda a pequeñas empresas, fundadores y propietarios de webs a entender qué funciona, qué puede limitar conversiones y qué señales externas merece la pena revisar.",whatTitle:"¿Qué analiza el Market Scan?",whatText:"Comprueba fundamentos observables: títulos, descripciones, estructura de encabezados, llamadas a la acción, captación de leads, analítica, datos estructurados, configuración móvil y profundidad de contenido. Para webs comerciales también busca lenguaje de compra, competidores, reseñas y oportunidades de contenido en fuentes públicas.",signalsTitle:"Qué puedes obtener del informe",signals:["Puntuación de fundamentos basada en controles observables","Plan de acción priorizado con motivos e impacto en clientes","Señales públicas de compra y problemas cuando la evidencia es suficiente","Competidores potenciales con enlaces a las fuentes","Oportunidades de contenido y campañas derivadas del análisis"],accuracyTitle:"¿Cómo evita Websiteli inventar datos de mercado?",accuracyText:"El escáner prefiere una sección vacía a un resultado irrelevante. Los hallazgos externos deben superar filtros de relevancia específicos de la web y se conservan los enlaces de origen. Los proveedores públicos pueden limitar solicitudes, por lo que cero resultados no demuestra que no exista actividad.",faqTitle:"Preguntas frecuentes sobre Market Scan",faqs:[{question:"¿El Websiteli Market Scan es gratis?",answer:"Sí. Puedes ejecutar el análisis y revisar la vista previa sin tarjeta de crédito ni registro."},{question:"¿Qué web puedo analizar?",answer:"Puedes introducir una web pública HTTP o HTTPS. Las direcciones privadas, locales o no públicas se bloquean por seguridad."},{question:"¿La puntuación predice ingresos?",answer:"No. Es una heurística transparente basada en comprobaciones observables, no una predicción de ingresos o conversión."},{question:"¿El análisis usa fuentes reales?",answer:"Sí. Los hallazgos externos incluyen enlaces a las fuentes cuando están disponibles; los resultados débiles o irrelevantes se omiten."}]}
};

const copies: Record<MarketScanLocale, MarketScanContent> = { en, de, fr, it, es };

export function getMarketScanContent(locale: string): MarketScanContent {
  return copies[(["en","de","fr","it","es"].includes(locale) ? locale : "en") as MarketScanLocale];
}
