import type { PackageKey } from "../config/pricing";

export const serviceCategoryIds = ["websites", "automation", "ai", "custom-software"] as const;
export type ServiceCategoryId = (typeof serviceCategoryIds)[number];

export type ServicePage = {
  slug: string;
  title: string;
  shortTitle: string;
  category: ServiceCategoryId;
  description: string;
  problem: string;
  solution: string;
  benefits: string[];
  idealClients: string[];
  technologies: string[];
  packageKey: PackageKey;
  investment: string;
  relatedServices: string[];
};

export const serviceCategoryDetails: Record<
  ServiceCategoryId,
  {
    eyebrow: string;
    title: string;
    summary: string;
    process: string[];
  }
> = {
  websites: {
    eyebrow: "Websites",
    title: "Modern websites built to explain, convert and scale.",
    summary:
      "Business websites, landing pages, multilingual sites, SEO foundations and maintenance for companies that need a credible owned presence.",
    process: ["Clarify the offer and page structure", "Design and build a responsive website", "Connect forms, analytics and SEO basics", "Launch, monitor and improve"],
  },
  automation: {
    eyebrow: "Automation",
    title: "Business automation that removes repetitive manual work.",
    summary:
      "Workflow automation, CRM updates, lead follow-up, document processing, spreadsheets, invoices, appointments and connected business systems.",
    process: ["Map the repetitive workflow", "Choose the simplest reliable automation path", "Build and test with real business examples", "Document the handover and monitor edge cases"],
  },
  ai: {
    eyebrow: "AI",
    title: "Useful AI systems connected to real business knowledge.",
    summary:
      "AI chatbots, internal assistants, RAG search, document intelligence, semantic search and AI integrations that help teams answer and act faster.",
    process: ["Identify the business question or knowledge source", "Prepare the data, prompts and retrieval flow", "Build a controlled AI workflow", "Evaluate answers and improve safeguards"],
  },
  "custom-software": {
    eyebrow: "Custom software",
    title: "Internal tools and web applications for the way your business works.",
    summary:
      "Dashboards, portals, booking systems, admin panels, SaaS prototypes, API integrations and workflow systems that replace scattered manual operations.",
    process: ["Define users, permissions and workflows", "Prototype the core screens and data model", "Build the application in focused milestones", "Deploy, train and iterate after launch"],
  },
};

export const automationShowcaseTasks = [
  "Sending invoices",
  "Reading PDFs",
  "Processing forms",
  "Email follow-up",
  "Lead qualification",
  "CRM updates",
  "Appointment reminders",
  "Customer onboarding",
  "Report generation",
  "Inventory synchronization",
  "Spreadsheet processing",
  "Data migration",
  "Document classification",
  "AI document search",
  "Chatbots",
  "Workflow automation",
  "Calendar automation",
  "Google Workspace automation",
  "Microsoft 365 automation",
  "Slack automation",
  "Notion automation",
  "Airtable automation",
  "Zapier replacement",
] as const;

export const technologyGroups = [
  {
    title: "Websites and apps",
    items: ["Astro", "TypeScript", "HTML", "CSS", "JavaScript", "Static hosting", "Headless content"],
  },
  {
    title: "Automation",
    items: ["APIs", "Webhooks", "Google Workspace", "Microsoft 365", "Airtable", "Notion", "CRM integrations"],
  },
  {
    title: "AI and data",
    items: ["OpenAI APIs", "RAG", "Embeddings", "OCR", "Semantic search", "Dashboards", "Data pipelines"],
  },
] as const;

export const services: ServicePage[] = [
  {
    slug: "landing-pages",
    title: "Landing Pages",
    shortTitle: "Landing pages",
    category: "websites",
    description: "Focused campaign pages for launches, offers, ads and lead generation.",
    problem: "Visitors arrive from ads, search or outreach but do not find one clear next step.",
    solution: "We build a focused page with a sharp offer, proof, conversion tracking and a clear contact or booking path.",
    benefits: ["Launch a focused offer quickly", "Improve paid traffic relevance", "Measure CTA and form actions", "Reduce distraction for visitors"],
    idealClients: ["New offers", "Campaigns", "Consultants", "Local service businesses"],
    technologies: ["Astro", "HTML", "CSS", "GA4", "Search Console", "Form tracking"],
    packageKey: "digitalFoundation",
    investment: "Usually a focused Digital Foundation or Growth Setup scope depending on tracking and campaign needs.",
    relatedServices: ["lead-generation", "seo-optimization", "business-websites"],
  },
  {
    slug: "business-websites",
    title: "Business Websites",
    shortTitle: "Business websites",
    category: "websites",
    description: "Complete websites that explain your business, build trust and generate qualified inquiries.",
    problem: "The business is credible offline, but the website does not explain the offer or convert visitors into conversations.",
    solution: "We plan the core pages, write clear conversion paths, build the site and connect analytics, forms and SEO foundations.",
    benefits: ["Clear positioning", "Better trust before sales calls", "Mobile-ready contact paths", "Owned digital asset"],
    idealClients: ["SMEs", "Local businesses", "Professional services", "Growing teams"],
    technologies: ["Astro", "Responsive design", "GA4", "Search Console", "Structured data", "Static hosting"],
    packageKey: "digitalFoundation",
    investment: "Best matched to Digital Foundation, with Growth Setup when bookings, ads or lead capture are important.",
    relatedServices: ["landing-pages", "multilingual-websites", "website-maintenance"],
  },
  {
    slug: "portfolio-websites",
    title: "Portfolio Websites",
    shortTitle: "Portfolio websites",
    category: "websites",
    description: "Personal brand and portfolio websites for specialists, consultants and creators.",
    problem: "Projects, experience and proof are scattered across social profiles, PDFs and old links.",
    solution: "We create one polished owned profile with case-study structure, project highlights, contact paths and SEO basics.",
    benefits: ["Centralize credibility", "Support outreach", "Show work clearly", "Make contact easy"],
    idealClients: ["Freelancers", "Consultants", "Researchers", "Creative professionals"],
    technologies: ["Astro", "Static hosting", "SEO metadata", "Analytics", "Responsive media"],
    packageKey: "digitalFoundation",
    investment: "Usually a Digital Foundation scope, with optional content strategy and ongoing maintenance.",
    relatedServices: ["business-websites", "lead-generation", "website-maintenance"],
  },
  {
    slug: "website-redesign",
    title: "Website Redesign",
    shortTitle: "Website redesign",
    category: "websites",
    description: "Redesign outdated websites into faster, clearer and more measurable business assets.",
    problem: "The existing website looks dated, loads slowly, hides important services or no longer matches the business.",
    solution: "We audit the current site, preserve what works, rebuild the structure and improve content, conversion paths and SEO basics.",
    benefits: ["Modern visual system", "Clearer service pages", "Lower technical debt", "Improved measurement"],
    idealClients: ["Businesses with outdated websites", "Teams repositioning their offer", "Companies preparing for campaigns"],
    technologies: ["Astro", "SEO migration checks", "GA4", "Search Console", "Performance optimization"],
    packageKey: "growthSetup",
    investment: "Usually a Growth Setup scope because redesigns need analytics, redirects, content and conversion planning.",
    relatedServices: ["business-websites", "seo-optimization", "website-maintenance"],
  },
  {
    slug: "ecommerce-websites",
    title: "E-commerce Websites",
    shortTitle: "E-commerce",
    category: "websites",
    description: "Conversion-focused online shop foundations and storefront improvements.",
    problem: "Products are online, but customers struggle to trust the store, find products or complete the purchase journey.",
    solution: "We improve storefront structure, landing pages, analytics, product content and the supporting automation around the shop.",
    benefits: ["Clear product journeys", "Better analytics", "Improved trust signals", "Automation-ready operations"],
    idealClients: ["Small shops", "DTC brands", "Shopify consultants", "Specialty retailers"],
    technologies: ["Shopify", "Static landing pages", "GA4", "Conversion tracking", "Email automation"],
    packageKey: "growthSetup",
    investment: "Usually Growth Setup plus optional automation for operations, reporting or email follow-up.",
    relatedServices: ["lead-generation", "email-automation", "analytics-dashboard"],
  },
  {
    slug: "multilingual-websites",
    title: "Multilingual Websites",
    shortTitle: "Multilingual websites",
    category: "websites",
    description: "Localized website structures for companies serving more than one language market.",
    problem: "International visitors cannot find or understand the right version of the offer.",
    solution: "We build a clean multilingual structure with language navigation, localized metadata, hreflang and market-specific CTAs.",
    benefits: ["Serve more markets", "Improve localized SEO", "Reduce language friction", "Keep content structured"],
    idealClients: ["Swiss businesses", "Cross-border service providers", "Tourism and hospitality", "International consultants"],
    technologies: ["Astro i18n patterns", "Hreflang", "Localized metadata", "Structured data"],
    packageKey: "growthSetup",
    investment: "Usually Growth Setup because multilingual work needs content planning, SEO and QA across languages.",
    relatedServices: ["business-websites", "seo-optimization", "website-maintenance"],
  },
  {
    slug: "seo-optimization",
    title: "SEO Optimization",
    shortTitle: "SEO",
    category: "websites",
    description: "Technical SEO, content structure and local visibility foundations for business websites.",
    problem: "The website exists, but search engines and customers cannot clearly understand the services, locations or proof.",
    solution: "We improve metadata, headings, schema, internal links, Search Console setup and service-page structure.",
    benefits: ["Cleaner indexing signals", "Better service discoverability", "Stronger local relevance", "Improved content priorities"],
    idealClients: ["Local businesses", "Service companies", "Consultants", "Redesign projects"],
    technologies: ["Search Console", "Schema.org", "Sitemaps", "Core Web Vitals", "Content audits"],
    packageKey: "growthSetup",
    investment: "Usually Growth Setup or a focused audit before a content or redesign phase.",
    relatedServices: ["business-websites", "landing-pages", "website-redesign"],
  },
  {
    slug: "website-maintenance",
    title: "Website Maintenance",
    shortTitle: "Maintenance",
    category: "websites",
    description: "Ongoing website care, monitoring, updates, small changes and performance checks.",
    problem: "After launch, websites slowly become outdated, insecure, broken or disconnected from the business.",
    solution: "We keep the site healthy with updates, checks, backups, analytics review and practical improvements.",
    benefits: ["Reduce website risk", "Keep content current", "Monitor forms and uptime", "Improve over time"],
    idealClients: ["Businesses after launch", "Teams without an in-house developer", "Websites that need reliability"],
    technologies: ["Monitoring", "Backups", "Dependency updates", "Analytics reports", "Performance checks"],
    packageKey: "websiteMaintenance",
    investment: "Best matched to Website Maintenance, priced monthly after scope and platform review.",
    relatedServices: ["business-websites", "website-redesign", "seo-optimization"],
  },
  {
    slug: "business-automation",
    title: "Business Process Automation",
    shortTitle: "Business automation",
    category: "automation",
    description: "Automation for repetitive admin, follow-up, reporting and operational workflows.",
    problem: "Teams lose hours copying data, sending repeated messages, checking spreadsheets and chasing status updates.",
    solution: "We map the workflow and connect the right forms, tools, APIs and notifications so routine tasks happen reliably.",
    benefits: ["Save manual admin time", "Reduce missed follow-up", "Standardize workflows", "Make operations easier to scale"],
    idealClients: ["SMEs", "Local service companies", "Agencies", "Operations-heavy teams"],
    technologies: ["APIs", "Webhooks", "Airtable", "Notion", "Google Workspace", "Microsoft 365"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade after a short audit of workflow volume, tools and edge cases.",
    relatedServices: ["crm-automation", "document-automation", "dashboard-development"],
  },
  {
    slug: "ai-workflow-automation",
    title: "AI Workflow Automation",
    shortTitle: "AI workflows",
    category: "automation",
    description: "AI-assisted workflows for classification, summaries, routing, drafting and decision support.",
    problem: "Manual workflows include text-heavy steps that are slow, inconsistent or hard to route.",
    solution: "We add controlled AI steps for extraction, classification, summarization or drafting, with human review where it matters.",
    benefits: ["Process information faster", "Reduce repetitive reading", "Route work more consistently", "Keep humans in control"],
    idealClients: ["Teams handling forms", "Support teams", "Document-heavy businesses", "Agencies"],
    technologies: ["OpenAI APIs", "Prompt workflows", "Webhooks", "Structured outputs", "Audit logs"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade with a proof-of-workflow before wider rollout.",
    relatedServices: ["document-intelligence", "data-extraction", "business-automation"],
  },
  {
    slug: "lead-generation",
    title: "Lead Generation Automation",
    shortTitle: "Lead generation",
    category: "automation",
    description: "Lead capture, routing, qualification and follow-up systems connected to your website.",
    problem: "Leads arrive through forms, calls, email or social channels without consistent qualification or follow-up.",
    solution: "We connect forms, tracking, CRM fields and automated first responses so leads are captured and handled faster.",
    benefits: ["Respond faster", "Capture better lead context", "Track lead sources", "Reduce lost inquiries"],
    idealClients: ["Service businesses", "Consultants", "Agencies", "Campaign teams"],
    technologies: ["GA4", "Forms", "CRM integrations", "Email automation", "UTM tracking"],
    packageKey: "growthSetup",
    investment: "Usually Growth Setup, with AI/Data Upgrade for qualification assistants or deeper CRM automation.",
    relatedServices: ["landing-pages", "crm-automation", "email-automation"],
  },
  {
    slug: "crm-automation",
    title: "CRM Automation",
    shortTitle: "CRM automation",
    category: "automation",
    description: "CRM updates, lead routing, pipeline hygiene and follow-up automation.",
    problem: "Customer and lead data is scattered, stale or manually copied between tools.",
    solution: "We connect forms, inboxes, spreadsheets and CRM fields so important records update with less manual work.",
    benefits: ["Cleaner customer data", "Faster follow-up", "Better pipeline visibility", "Fewer manual updates"],
    idealClients: ["Sales teams", "Consultants", "Local service providers", "Agencies"],
    technologies: ["HubSpot", "Pipedrive", "Airtable", "APIs", "Webhooks", "Google Sheets"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade after reviewing current CRM fields and follow-up rules.",
    relatedServices: ["lead-generation", "email-automation", "api-integrations"],
  },
  {
    slug: "email-automation",
    title: "Email Automation",
    shortTitle: "Email automation",
    category: "automation",
    description: "Automated email sequences for inquiries, onboarding, reminders and newsletters.",
    problem: "Important customer emails are written manually or sent too late.",
    solution: "We design practical templates, triggers and segmentation so routine emails happen at the right time.",
    benefits: ["Improve response consistency", "Support onboarding", "Reduce repetitive writing", "Keep leads warm"],
    idealClients: ["Service businesses", "Studios", "Consultants", "E-commerce teams"],
    technologies: ["Email platforms", "Forms", "CRM triggers", "UTM attribution", "Newsletter tools"],
    packageKey: "growthSetup",
    investment: "Usually Growth Setup, with AI/Data Upgrade when email drafting or classification needs AI.",
    relatedServices: ["lead-generation", "crm-automation", "customer-support-ai"],
  },
  {
    slug: "appointment-automation",
    title: "Appointment Automation",
    shortTitle: "Appointments",
    category: "automation",
    description: "Booking flows, reminders, calendar updates and no-show reduction systems.",
    problem: "Appointments require manual back-and-forth, reminders are inconsistent and bookings are hard to track.",
    solution: "We connect booking pages, calendars, reminders and contact records around a simple customer journey.",
    benefits: ["Reduce scheduling friction", "Send timely reminders", "Centralize booking context", "Improve mobile conversion"],
    idealClients: ["Clinics", "Studios", "Consultants", "Local services"],
    technologies: ["Calendar tools", "Booking systems", "Email/SMS reminders", "Forms", "Webhooks"],
    packageKey: "growthSetup",
    investment: "Usually Growth Setup, with custom software when booking rules are complex.",
    relatedServices: ["booking-systems", "lead-generation", "email-automation"],
  },
  {
    slug: "invoice-automation",
    title: "Invoice Automation",
    shortTitle: "Invoices",
    category: "automation",
    description: "Invoice creation, reminders, data transfer and reporting support.",
    problem: "Invoice data is copied by hand, reminders are inconsistent and reporting takes too long.",
    solution: "We connect the source data, invoice tool, reminders and reports so finance admin becomes more predictable.",
    benefits: ["Reduce copying errors", "Speed up invoicing", "Improve reminder consistency", "Make status visible"],
    idealClients: ["Service providers", "Agencies", "Trades", "Small finance teams"],
    technologies: ["Accounting tools", "APIs", "PDF generation", "Email automation", "Dashboards"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade after reviewing invoice sources, approval rules and accounting tools.",
    relatedServices: ["document-automation", "dashboard-development", "api-integrations"],
  },
  {
    slug: "document-automation",
    title: "Document Automation",
    shortTitle: "Documents",
    category: "automation",
    description: "Automated document intake, naming, classification, extraction and routing.",
    problem: "Documents arrive in email, forms or folders and must be renamed, checked, copied or routed by hand.",
    solution: "We build workflows that read metadata, classify files, extract fields and route documents to the right place.",
    benefits: ["Reduce manual document handling", "Improve consistency", "Find files faster", "Prepare data for reporting"],
    idealClients: ["Clinics", "Law firms", "Finance teams", "Operations teams"],
    technologies: ["OCR", "PDF parsing", "Cloud storage", "AI classification", "Webhooks"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, starting with a narrow document type before broader automation.",
    relatedServices: ["pdf-processing", "ocr", "document-intelligence"],
  },
  {
    slug: "pdf-processing",
    title: "PDF Processing",
    shortTitle: "PDF processing",
    category: "automation",
    description: "PDF extraction, splitting, renaming, validation and workflow automation.",
    problem: "Teams spend time opening PDFs, finding values and copying information into other tools.",
    solution: "We automate PDF intake, extraction and routing with validation steps for important fields.",
    benefits: ["Extract PDF data faster", "Reduce copy-paste work", "Route files consistently", "Support reporting"],
    idealClients: ["Document-heavy teams", "Finance teams", "Clinics", "Back offices"],
    technologies: ["PDF parsers", "OCR", "Structured outputs", "Cloud storage", "APIs"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade after reviewing sample PDFs and accuracy requirements.",
    relatedServices: ["document-automation", "ocr", "data-extraction"],
  },
  {
    slug: "data-extraction",
    title: "Data Extraction",
    shortTitle: "Data extraction",
    category: "automation",
    description: "Extract useful data from forms, emails, PDFs, spreadsheets and business systems.",
    problem: "Important information exists, but it is locked inside documents, inboxes or inconsistent spreadsheet columns.",
    solution: "We build extraction workflows that turn messy inputs into structured data ready for review or automation.",
    benefits: ["Turn files into usable data", "Reduce manual entry", "Improve reporting", "Prepare AI workflows"],
    idealClients: ["Operations teams", "Agencies", "Finance teams", "Administrative teams"],
    technologies: ["OCR", "AI extraction", "APIs", "CSV/Sheets", "Validation rules"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade with a sample-data assessment first.",
    relatedServices: ["pdf-processing", "document-intelligence", "spreadsheet-automation"],
  },
  {
    slug: "ocr",
    title: "OCR Automation",
    shortTitle: "OCR",
    category: "automation",
    description: "Optical character recognition workflows for scanned documents and image-based files.",
    problem: "Scans and photos cannot be searched, copied or processed reliably by normal business tools.",
    solution: "We add OCR and validation to convert scanned content into searchable, structured information.",
    benefits: ["Make scans searchable", "Extract fields from images", "Reduce typing", "Support document archives"],
    idealClients: ["Clinics", "Legal teams", "Real estate teams", "Back-office teams"],
    technologies: ["OCR engines", "PDF processing", "AI validation", "Cloud storage", "Search indexes"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, with pricing based on document volume and accuracy needs.",
    relatedServices: ["document-automation", "pdf-processing", "document-intelligence"],
  },
  {
    slug: "spreadsheet-automation",
    title: "Spreadsheet Automation",
    shortTitle: "Spreadsheets",
    category: "automation",
    description: "Automate spreadsheet imports, cleanup, reports, alerts and connected workflows.",
    problem: "The business runs on spreadsheets that need manual cleanup, copying and status updates.",
    solution: "We turn repetitive spreadsheet work into structured imports, formulas, scripts, validations and reporting flows.",
    benefits: ["Reduce spreadsheet busywork", "Improve data quality", "Send alerts automatically", "Create repeatable reports"],
    idealClients: ["Operations teams", "Agencies", "Finance teams", "Inventory-heavy businesses"],
    technologies: ["Google Sheets", "Excel", "Apps Script", "APIs", "CSV automation"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, starting with the spreadsheet that costs the most time.",
    relatedServices: ["google-workspace-automation", "microsoft-365-automation", "dashboard-development"],
  },
  {
    slug: "google-workspace-automation",
    title: "Google Workspace Automation",
    shortTitle: "Google Workspace",
    category: "automation",
    description: "Automation across Gmail, Sheets, Drive, Docs, Calendar and Forms.",
    problem: "Important Google Workspace tasks depend on manual copying, reminders, naming or folder organization.",
    solution: "We connect Workspace tools with scripts, forms, webhooks and structured workflows.",
    benefits: ["Automate routine Google tasks", "Organize files consistently", "Improve form follow-up", "Generate reports"],
    idealClients: ["Small teams using Google Workspace", "Agencies", "Schools", "Local businesses"],
    technologies: ["Google Apps Script", "Google Sheets", "Drive", "Gmail", "Calendar", "Forms"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, with scope based on tools, permissions and workflow complexity.",
    relatedServices: ["spreadsheet-automation", "document-automation", "appointment-automation"],
  },
  {
    slug: "microsoft-365-automation",
    title: "Microsoft 365 Automation",
    shortTitle: "Microsoft 365",
    category: "automation",
    description: "Automation across Outlook, Excel, SharePoint, OneDrive and Teams workflows.",
    problem: "Microsoft 365 data is useful, but routine updates, reminders and files still move manually.",
    solution: "We connect Microsoft workflows with structured automations, approvals and reporting steps.",
    benefits: ["Reduce manual Office work", "Improve file workflows", "Automate reminders", "Support team operations"],
    idealClients: ["Teams using Microsoft 365", "Professional services", "Construction", "Administrative teams"],
    technologies: ["Microsoft 365", "SharePoint", "Excel", "Outlook", "APIs", "Workflow automation"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade after reviewing tenant access, data sources and approval rules.",
    relatedServices: ["spreadsheet-automation", "document-automation", "crm-automation"],
  },
  {
    slug: "ai-chatbots",
    title: "AI Chatbots",
    shortTitle: "AI chatbots",
    category: "ai",
    description: "Website and support chatbots that answer repeated questions and collect useful lead context.",
    problem: "Customers ask the same questions repeatedly, and many inquiries arrive without enough context.",
    solution: "We build a controlled AI chatbot connected to approved content, handoff paths and lead capture.",
    benefits: ["Answer repeated questions faster", "Qualify inquiries", "Guide visitors to the right service", "Reduce support interruptions"],
    idealClients: ["Service businesses", "Clinics", "Agencies", "Local businesses"],
    technologies: ["OpenAI APIs", "Knowledge base", "RAG", "Lead forms", "Conversation analytics"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade after defining allowed answers, handoff rules and knowledge sources.",
    relatedServices: ["rag-chatbots", "customer-support-ai", "knowledge-base-search"],
  },
  {
    slug: "internal-ai-assistants",
    title: "Internal AI Assistants",
    shortTitle: "Internal AI",
    category: "ai",
    description: "Private AI assistants for team knowledge, operations and repeated internal questions.",
    problem: "Team knowledge lives in documents, messages and spreadsheets, so people interrupt each other for answers.",
    solution: "We build an internal assistant connected to selected knowledge sources with clear usage boundaries.",
    benefits: ["Find internal answers faster", "Reduce repeated questions", "Support onboarding", "Preserve institutional knowledge"],
    idealClients: ["Growing teams", "Agencies", "Operations teams", "Knowledge-heavy businesses"],
    technologies: ["RAG", "Embeddings", "Private knowledge base", "Access control", "Evaluation sets"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, starting with one team or knowledge area.",
    relatedServices: ["knowledge-base-search", "rag-chatbots", "semantic-search"],
  },
  {
    slug: "knowledge-base-search",
    title: "Knowledge Base Search",
    shortTitle: "Knowledge search",
    category: "ai",
    description: "Search across help docs, policies, procedures, PDFs and internal resources.",
    problem: "Useful answers exist, but staff and customers cannot find the right document quickly.",
    solution: "We structure your knowledge sources and build search that retrieves relevant answers, pages or documents.",
    benefits: ["Improve findability", "Reduce repeated support", "Support AI assistants", "Make documentation useful"],
    idealClients: ["Support teams", "Clinics", "Agencies", "Internal operations"],
    technologies: ["Search indexes", "Embeddings", "RAG", "Document processing", "Analytics"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, with cost depending on sources, permissions and update frequency.",
    relatedServices: ["internal-ai-assistants", "semantic-search", "document-intelligence"],
  },
  {
    slug: "rag-chatbots",
    title: "RAG Chatbots",
    shortTitle: "RAG chatbots",
    category: "ai",
    description: "Retrieval-augmented chatbots that answer from approved company content.",
    problem: "Generic chatbots can sound confident while using the wrong source or missing company-specific details.",
    solution: "We connect the chatbot to curated content retrieval, citations, guardrails and fallback handoff paths.",
    benefits: ["Use approved knowledge", "Reduce hallucination risk", "Keep answers more current", "Support traceable responses"],
    idealClients: ["Support teams", "Knowledge-heavy businesses", "B2B services", "Internal teams"],
    technologies: ["RAG", "Embeddings", "Vector search", "OpenAI APIs", "Evaluation prompts"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade with a narrow knowledge base first, then expansion after evaluation.",
    relatedServices: ["ai-chatbots", "knowledge-base-search", "semantic-search"],
  },
  {
    slug: "local-llm-solutions",
    title: "Local LLM Solutions",
    shortTitle: "Local LLM",
    category: "ai",
    description: "Privacy-conscious AI workflows using local or self-hosted language models where appropriate.",
    problem: "Some workflows need stronger control over data handling, deployment environment or model behavior.",
    solution: "We assess whether a local or hosted model is appropriate and design a practical architecture around it.",
    benefits: ["Improve data-control options", "Reduce external dependency in selected workflows", "Customize model behavior", "Support sensitive use cases"],
    idealClients: ["Privacy-conscious teams", "Regulated workflows", "Internal tools", "Technical SMEs"],
    technologies: ["Local LLMs", "Self-hosting", "APIs", "RAG", "Access controls"],
    packageKey: "aiDataUpgrade",
    investment: "Usually a custom AI/Data Upgrade after a feasibility review of data, hardware and quality needs.",
    relatedServices: ["internal-ai-assistants", "rag-chatbots", "document-intelligence"],
  },
  {
    slug: "customer-support-ai",
    title: "Customer Support AI",
    shortTitle: "Support AI",
    category: "ai",
    description: "AI support helpers for repeated questions, triage, summaries and handoff preparation.",
    problem: "Support work is interrupted by repeated questions and messy context before a human can help.",
    solution: "We build AI support workflows that answer approved questions, summarize context and route complex cases to people.",
    benefits: ["Reduce repetitive replies", "Improve first response", "Prepare better handoffs", "Capture support insights"],
    idealClients: ["Support teams", "Clinics", "Service businesses", "E-commerce teams"],
    technologies: ["AI chat", "Knowledge base", "Ticket summaries", "CRM integration", "Analytics"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, scoped around a specific support queue or FAQ set.",
    relatedServices: ["ai-chatbots", "email-automation", "knowledge-base-search"],
  },
  {
    slug: "ai-content-pipelines",
    title: "AI Content Pipelines",
    shortTitle: "Content pipelines",
    category: "ai",
    description: "AI-assisted systems for planning, drafting, repurposing and publishing content with human review.",
    problem: "Content production is inconsistent because research, drafting, formatting and publishing all happen manually.",
    solution: "We create a pipeline that turns approved inputs into drafts, summaries, social snippets or structured publishing tasks.",
    benefits: ["Speed up content operations", "Keep a consistent structure", "Repurpose long-form content", "Maintain human approval"],
    idealClients: ["Agencies", "Consultants", "Marketing teams", "Founders"],
    technologies: ["OpenAI APIs", "Content calendars", "CMS workflows", "Structured prompts", "Automation"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, starting with one repeatable content format.",
    relatedServices: ["business-automation", "seo-optimization", "internal-ai-assistants"],
  },
  {
    slug: "document-intelligence",
    title: "Document Intelligence",
    shortTitle: "Document AI",
    category: "ai",
    description: "AI workflows that classify, extract, summarize and search business documents.",
    problem: "Documents contain useful business information, but reviewing and extracting it manually is slow.",
    solution: "We combine OCR, extraction, classification, summaries and search so documents become usable workflow inputs.",
    benefits: ["Understand documents faster", "Extract structured fields", "Search across files", "Support review workflows"],
    idealClients: ["Legal teams", "Healthcare practices", "Finance teams", "Administrative teams"],
    technologies: ["OCR", "RAG", "Embeddings", "Structured extraction", "Document pipelines"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, priced after sample documents and accuracy targets are reviewed.",
    relatedServices: ["document-automation", "data-extraction", "knowledge-base-search"],
  },
  {
    slug: "semantic-search",
    title: "Semantic Search",
    shortTitle: "Semantic search",
    category: "ai",
    description: "Meaning-based search for documents, products, knowledge bases and internal resources.",
    problem: "Keyword search misses useful results when people describe the same idea in different words.",
    solution: "We build semantic search that retrieves related content by meaning and combines it with filters where needed.",
    benefits: ["Find relevant content faster", "Improve knowledge discovery", "Support AI assistants", "Reduce duplicate questions"],
    idealClients: ["Knowledge bases", "Product catalogs", "Internal documentation", "Support teams"],
    technologies: ["Embeddings", "Vector search", "RAG", "Metadata filters", "Search analytics"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, with scope based on content volume and freshness requirements.",
    relatedServices: ["knowledge-base-search", "rag-chatbots", "document-intelligence"],
  },
  {
    slug: "ai-integrations",
    title: "AI Integrations",
    shortTitle: "AI integrations",
    category: "ai",
    description: "Connect AI capabilities into websites, tools, forms, dashboards and business workflows.",
    problem: "AI experiments exist separately from the tools where work actually happens.",
    solution: "We integrate AI steps into forms, CRMs, dashboards, portals and automation flows with clear safeguards.",
    benefits: ["Bring AI into daily workflows", "Reduce context switching", "Automate text-heavy steps", "Keep outputs measurable"],
    idealClients: ["SMEs", "Agencies", "Operations teams", "Software-enabled services"],
    technologies: ["OpenAI APIs", "Webhooks", "APIs", "Dashboards", "Custom apps"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade or a custom software scope for deeper application integration.",
    relatedServices: ["business-automation", "custom-web-apps", "dashboard-development"],
  },
  {
    slug: "internal-tools",
    title: "Internal Tools",
    shortTitle: "Internal tools",
    category: "custom-software",
    description: "Private web tools that support operations, approvals, data entry and team workflows.",
    problem: "Teams rely on spreadsheets, inboxes and manual checklists because existing tools do not match the workflow.",
    solution: "We build a focused internal tool with the screens, data and actions your team actually needs.",
    benefits: ["Reduce scattered work", "Improve process visibility", "Standardize team actions", "Support growth without chaos"],
    idealClients: ["Operations teams", "Agencies", "Clinics", "Service companies"],
    technologies: ["TypeScript", "Astro", "APIs", "Databases", "Authentication", "Dashboards"],
    packageKey: "aiDataUpgrade",
    investment: "Usually a custom AI/Data Upgrade scope after workflow and user-role definition.",
    relatedServices: ["admin-panels", "workflow-systems", "dashboard-development"],
  },
  {
    slug: "dashboard-development",
    title: "Dashboard Development",
    shortTitle: "Dashboards",
    category: "custom-software",
    description: "Business dashboards for sales, marketing, operations, reporting and decision support.",
    problem: "Important numbers exist in different tools, but leadership cannot see what is happening quickly.",
    solution: "We connect data sources and build dashboards that focus on useful decisions rather than vanity metrics.",
    benefits: ["See performance faster", "Reduce manual reports", "Spot bottlenecks", "Support better decisions"],
    idealClients: ["Founders", "Operations teams", "Marketing teams", "Agencies"],
    technologies: ["GA4", "APIs", "Databases", "Charts", "Scheduled reports", "Data pipelines"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, priced by sources, refresh frequency and reporting complexity.",
    relatedServices: ["data-dashboards", "api-integrations", "business-automation"],
  },
  {
    slug: "admin-panels",
    title: "Admin Panels",
    shortTitle: "Admin panels",
    category: "custom-software",
    description: "Custom administration interfaces for content, users, bookings, orders or operations.",
    problem: "Important updates require developer help or awkward edits in tools that were not made for the process.",
    solution: "We build admin screens that make common edits, approvals and status changes safer and faster.",
    benefits: ["Reduce developer dependency", "Make updates safer", "Improve permissions", "Speed up operations"],
    idealClients: ["Content teams", "Service businesses", "SaaS prototypes", "Operations teams"],
    technologies: ["Authentication", "Databases", "Role-based access", "APIs", "Audit logs"],
    packageKey: "aiDataUpgrade",
    investment: "Usually a custom software scope inside AI/Data Upgrade after defining roles and actions.",
    relatedServices: ["internal-tools", "client-portals", "custom-web-apps"],
  },
  {
    slug: "booking-systems",
    title: "Booking Systems",
    shortTitle: "Booking systems",
    category: "custom-software",
    description: "Booking and scheduling systems for appointments, resources, services or events.",
    problem: "Standard booking tools do not match your rules, availability, approvals or customer journey.",
    solution: "We design a booking flow that fits your business logic and connects to calendars, reminders and reporting.",
    benefits: ["Reduce manual scheduling", "Handle custom rules", "Improve customer experience", "Track bookings clearly"],
    idealClients: ["Clinics", "Studios", "Consultants", "Venues", "Service teams"],
    technologies: ["Calendars", "Forms", "Databases", "Notifications", "Payment integrations"],
    packageKey: "growthSetup",
    investment: "Starts with Growth Setup for simple booking; custom software pricing applies when rules are complex.",
    relatedServices: ["appointment-automation", "client-portals", "business-websites"],
  },
  {
    slug: "client-portals",
    title: "Client Portals",
    shortTitle: "Client portals",
    category: "custom-software",
    description: "Secure portals for clients to submit information, track progress, view files and communicate.",
    problem: "Client work happens through scattered emails, attachments and status updates.",
    solution: "We build a portal that centralizes the client journey, documents, forms and progress visibility.",
    benefits: ["Improve client experience", "Reduce email back-and-forth", "Centralize files", "Make status visible"],
    idealClients: ["Agencies", "Consultants", "Legal teams", "Healthcare practices"],
    technologies: ["Authentication", "File storage", "Forms", "Notifications", "Dashboards"],
    packageKey: "aiDataUpgrade",
    investment: "Usually a custom software scope after defining client roles, permissions and data sensitivity.",
    relatedServices: ["business-portals", "document-automation", "admin-panels"],
  },
  {
    slug: "custom-saas",
    title: "Custom SaaS",
    shortTitle: "Custom SaaS",
    category: "custom-software",
    description: "Focused SaaS prototypes and internal products built around a clear business workflow.",
    problem: "A repeatable service or internal workflow could become software, but the first version needs discipline.",
    solution: "We scope and build a lean SaaS-style product around the core user journey, data model and feedback loop.",
    benefits: ["Validate a software idea", "Create repeatable workflows", "Support productized services", "Avoid overbuilding early"],
    idealClients: ["Founders", "Agencies", "Consultants", "Productized services"],
    technologies: ["TypeScript", "Databases", "Authentication", "Payments", "APIs", "Analytics"],
    packageKey: "aiDataUpgrade",
    investment: "Custom scope after product discovery, usually delivered in milestones.",
    relatedServices: ["custom-web-apps", "admin-panels", "api-integrations"],
  },
  {
    slug: "workflow-systems",
    title: "Workflow Systems",
    shortTitle: "Workflow systems",
    category: "custom-software",
    description: "Custom workflow systems for approvals, status tracking, task routing and operations.",
    problem: "Work moves through informal messages and spreadsheets, making status, ownership and next steps unclear.",
    solution: "We build a workflow system with roles, statuses, notifications and reporting around the real process.",
    benefits: ["Clarify responsibility", "Reduce status chasing", "Standardize approvals", "Make bottlenecks visible"],
    idealClients: ["Operations teams", "Construction", "Agencies", "Administrative teams"],
    technologies: ["Databases", "Workflow states", "Notifications", "Dashboards", "APIs"],
    packageKey: "aiDataUpgrade",
    investment: "Custom AI/Data Upgrade scope after mapping the process and edge cases.",
    relatedServices: ["internal-tools", "business-automation", "dashboard-development"],
  },
  {
    slug: "data-dashboards",
    title: "Data Dashboards",
    shortTitle: "Data dashboards",
    category: "custom-software",
    description: "Dashboards that turn business data into clear views for teams and leadership.",
    problem: "Data is available, but reporting depends on manual exports and spreadsheet cleanup.",
    solution: "We connect data sources, define useful metrics and build dashboards with refresh and reporting workflows.",
    benefits: ["Reduce reporting work", "Make metrics visible", "Compare channels or teams", "Support recurring decisions"],
    idealClients: ["Leadership teams", "Marketing teams", "Operations", "Agencies"],
    technologies: ["APIs", "Databases", "Charts", "Scheduled reports", "Data cleaning"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade, priced by source count, refresh needs and dashboard complexity.",
    relatedServices: ["dashboard-development", "api-integrations", "spreadsheet-automation"],
  },
  {
    slug: "api-integrations",
    title: "API Integrations",
    shortTitle: "API integrations",
    category: "custom-software",
    description: "Connect websites, CRMs, dashboards, business tools and custom workflows through APIs.",
    problem: "Important systems do not talk to each other, so people move data manually or accept stale information.",
    solution: "We design and build API connections that move the right data at the right time with monitoring and fallback paths.",
    benefits: ["Reduce duplicate entry", "Keep systems aligned", "Improve reporting", "Enable automation"],
    idealClients: ["Growing SMEs", "Agencies", "E-commerce teams", "Operations teams"],
    technologies: ["REST APIs", "Webhooks", "OAuth", "Data mapping", "Error monitoring"],
    packageKey: "aiDataUpgrade",
    investment: "Usually AI/Data Upgrade or custom software pricing based on API complexity and reliability needs.",
    relatedServices: ["crm-automation", "dashboard-development", "business-automation"],
  },
  {
    slug: "business-portals",
    title: "Business Portals",
    shortTitle: "Business portals",
    category: "custom-software",
    description: "Business portals for partners, clients, employees or operational workflows.",
    problem: "External and internal stakeholders need access to information, but email threads and files create confusion.",
    solution: "We build a portal with the right roles, content, forms, documents and dashboards for the audience.",
    benefits: ["Centralize access", "Improve partner or client experience", "Reduce repeated emails", "Control permissions"],
    idealClients: ["B2B services", "Agencies", "Associations", "Operations teams"],
    technologies: ["Authentication", "Role-based access", "File storage", "Forms", "Dashboards"],
    packageKey: "aiDataUpgrade",
    investment: "Custom scope after defining users, permissions, content and data sensitivity.",
    relatedServices: ["client-portals", "internal-tools", "admin-panels"],
  },
  {
    slug: "custom-web-apps",
    title: "Custom Web Applications",
    shortTitle: "Web applications",
    category: "custom-software",
    description: "Custom web applications for workflows that cannot be solved cleanly by a standard website.",
    problem: "The business needs an interactive tool, portal or workflow that off-the-shelf pages cannot provide.",
    solution: "We design and build a focused web app with the data model, interface and integrations needed for the workflow.",
    benefits: ["Create software around your process", "Reduce tool sprawl", "Improve team productivity", "Launch iteratively"],
    idealClients: ["SMEs", "Founders", "Agencies", "Operations-heavy businesses"],
    technologies: ["TypeScript", "Astro", "Databases", "APIs", "Authentication", "Analytics"],
    packageKey: "aiDataUpgrade",
    investment: "Custom scope after discovery, usually split into milestones with a clear first useful version.",
    relatedServices: ["internal-tools", "custom-saas", "api-integrations"],
  },
];

export const serviceSlugs = services.map((service) => service.slug);

export const featuredServiceSlugs = [
  "business-websites",
  "business-automation",
  "ai-chatbots",
  "custom-web-apps",
  "document-automation",
  "dashboard-development",
] as const;

export function getServiceBySlug(slug: string | undefined) {
  return services.find((service) => service.slug === slug);
}

export function getServicesByCategory(category: ServiceCategoryId) {
  return services.filter((service) => service.category === category);
}

export function getRelatedServices(service: ServicePage, limit = 4) {
  const related = service.relatedServices
    .map((slug) => getServiceBySlug(slug))
    .filter((item): item is ServicePage => Boolean(item));

  if (related.length >= limit) return related.slice(0, limit);

  return [
    ...related,
    ...services.filter((item) => item.category === service.category && item.slug !== service.slug && !related.some((relatedItem) => relatedItem.slug === item.slug)),
  ].slice(0, limit);
}

export function getServiceCategoryServices() {
  return serviceCategoryIds.map((id) => ({
    id,
    ...serviceCategoryDetails[id],
    services: getServicesByCategory(id),
  }));
}

export function getFeaturedServices() {
  return featuredServiceSlugs.map((slug) => getServiceBySlug(slug)).filter((service): service is ServicePage => Boolean(service));
}
